### ISSUE TITLE
panicked ring-0.16.11/src/rsa/signing.rs:422:13

### ISSUE THREAD

**Issue by silence-coding** [briansmith/ring#1295] opened 2021-05-14 04:05 UTC
**Platform**
Linux OMP-01 4.18.0-147.5.1.6.h451.eulerosv2r9.x86_64 #1 SMP Thu Apr 22 04:55:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Panic**
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Unspecified', ring-0.16.11/src/rsa/signing.rs:422:13


13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:101
  14: core::option::expect_none_failed
             at src/libcore/option.rs:1272
  15: ring::rsa::signing::RsaKeyPair::public_modulus_len
  16: <rustls::sign::RSASigner as rustls::sign::Signer>::sign
  17: <rustls::client::tls13::ExpectFinished as rustls::client::hs::State>::handle
  18: rustls::client::ClientSessionImpl::process_main_protocol
  19: <rustls::client::ClientSession as rustls::session::Session>::process_new_packets
  20: tokio_rustls::common::Stream<IO,S>::process_new_packets
  21: tokio_rustls::common::Stream<IO,S>::handshake
  22: <tokio_rustls::common::handshake::MidHandshake<IS> as core::future::future::Future>::poll
  23: <hbx::net::tls::TlsConnect as core::future::future::Future>::poll
  24: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  25: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  26: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  27: <hyper::service::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
  28: futures_util::future::try_future::try_chain::TryChain<Fut1,Fut2,Data>::poll
  29: <hyper::common::lazy::Lazy<F,R> as core::future::future::Future>::poll
  30: futures_util::future::future::chain::Chain<Fut1,Fut2,Data>::poll
  31: futures_util::future::try_future::try_chain::TryChain<Fut1,Fut2,Data>::poll
  32: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  33: <hyper::client::ResponseFuture as core::future::future::Future>::poll
  34: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  35: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  36: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  37: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
```

**Code**
![image](https://user-images.githubusercontent.com/32766901/118219586-606c0a80-b4ac-11eb-9865-389914570743.png)

**Comment by briansmith** [comment] 2021-05-14 15:56
@silence-coding Does it happen with 0.16.20?

**Comment by briansmith** [comment] 2021-05-14 15:58
@silence-coding Can you share the RSA public key it happens with?

**Comment by briansmith** [comment] 2021-05-15 14:39
@silence-coding Also, which version of Rust are you using? 1.53 nightly or 1.52 or older stable releases?

**Comment by silence-coding** [comment] 2021-05-18 05:32
I'm sorry, I didn't reserve the environment. I tried to reproduce the problem in the environment, but it didn't recur.

**Comment by briansmith** [comment] 2021-09-28 04:48
You were probably using a pre-Stable Rust release that had a bug: https://github.com/rust-lang/rust/issues/84958. I'm closing this since you can't reproduce it. Thanks for the bug report!

**Closed by briansmith** 2021-09-28 04:48 UTC
