### ISSUE TITLE
No s390 support ?

### ISSUE THREAD

**Issue by eaibmz** [briansmith/ring#1511] opened 2022-08-24 15:59 UTC
Hi,

s390 architecture is not supported yet, right ?

Regards
Alex

**Comment by ecnelises** [comment] 2022-08-25 08:46
If you mean s390 on Linux, there's https://github.com/briansmith/ring/pull/1297 in review (but seems no recent response).

**Comment by eaibmz** [comment] 2022-08-26 16:58
> If you mean s390 on Linux, there's #1297 in review (but seems no recent response).

Thank you, i missed that.

**Comment by briansmith** [comment] 2022-11-09 19:38
I'm going to close this as a duplicate of #1555, which is about making a generalized effort to support all big-endian architectures with a single codepath.

**Closed by briansmith** 2022-11-09 19:38 UTC
