### ISSUE TITLE
ring fail to cross compile on x86_64_ubuntu for mipsel_linux

### ISSUE THREAD

**Issue by Hualin-AUG** [briansmith/ring#1049] opened 2020-08-31 17:41 UTC
My build command: RUST_BACKTRACE=full cargo build --target=mipsel-unknown-linux-musl
`error: failed to run custom build command for `ring v0.14.6`

Caused by:
  process didn't exit successfully: `/home/hualin/LocalStorage/target/debug/build/ring-1c796d989d0eff14/build-script-build` (exit code: 101)
--- stdout
CARGO: /home/hualin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo
CARGO_CFG_TARGET_ARCH: mips
CARGO_CFG_TARGET_ENDIAN: little
CARGO_CFG_TARGET_ENV: musl
CARGO_CFG_TARGET_FAMILY: unix
CARGO_CFG_TARGET_OS: linux
CARGO_CFG_TARGET_POINTER_WIDTH: 32
CARGO_CFG_TARGET_VENDOR: unknown
CARGO_CFG_UNIX:
CARGO_FEATURE_DEFAULT: 1
CARGO_FEATURE_DEV_URANDOM_FALLBACK: 1
CARGO_FEATURE_USE_HEAP: 1
CARGO_HOME: /home/hualin/.cargo
CARGO_MAKEFLAGS: --jobserver-fds=5,6 -j --jobserver-auth=5,6 -j
CARGO_MANIFEST_DIR: /home/hualin/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6
CARGO_MANIFEST_LINKS: ring-asm
CARGO_PKG_AUTHORS: Brian Smith <brian@briansmith.org>
CARGO_PKG_DESCRIPTION: Safe, fast, small crypto using Rust.
CARGO_PKG_HOMEPAGE:
CARGO_PKG_NAME: ring
CARGO_PKG_REPOSITORY: https://github.com/briansmith/ring
CARGO_PKG_VERSION: 0.14.6
CARGO_PKG_VERSION_MAJOR: 0
CARGO_PKG_VERSION_MINOR: 14
CARGO_PKG_VERSION_PATCH: 6
CARGO_PKG_VERSION_PRE:
DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1003/bus
DEBUG: true
DISPLAY: localhost:10.0
HOME: /home/hualin
HOST: x86_64-unknown-linux-gnu
LANG: en_US.UTF-8
LD_LIBRARY_PATH: /home/hualin/LocalStorage/target/debug/deps:/home/hualin/LocalStorage/target/debug:/home/hualin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib:/home/hualin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib:/usr/lib/fft_v9_1:/usr/lib/fpo_v7_0:/usr/lib/fir_v7_0
LESSCLOSE: /usr/bin/lesspipe %s %s
LESSOPEN: | /usr/bin/lesspipe %s
LOGNAME: hualin
LS_COLORS: rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
MAIL: /var/mail/hualin
NUM_JOBS: 8
OLDPWD: /home/hualin/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6
OPT_LEVEL: 0
OUT_DIR: /home/hualin/LocalStorage/target/mipsel-unknown-linux-musl/debug/build/ring-f99d739b198db4bc/out
PATH: /home/hualin/.cargo/bin:/home/hualin/.cargo/bin:/home/hualin/snap/go:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
PROFILE: debug
PWD: /home/hualin/LocalStorage
RUSTC: rustc
RUSTC_LINKER: /home/hualin/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-7.3.0_musl/bin/mipsel-openwrt-linux-musl-gcc
RUSTDOC: rustdoc
RUSTUP_HOME: /home/hualin/.rustup
RUSTUP_TOOLCHAIN: stable-x86_64-unknown-linux-gnu
RUST_BACKTRACE: full
RUST_RECURSION_COUNT: 1
SHELL: /bin/bash
SHLVL: 1
SSH_CLIENT: 192.168.4.30 14137 22
SSH_CONNECTION: 192.168.4.30 14137 192.168.4.234 22
SSH_TTY: /dev/pts/0
SSL_CERT_DIR: /usr/lib/ssl/certs
SSL_CERT_FILE: /usr/lib/ssl/certs/ca-certificates.crt
S_COLORS: auto
TARGET: mipsel-unknown-linux-musl
TERM: xterm
USER: hualin
XDG_DATA_DIRS: /usr/local/share:/usr/share:/var/lib/snapd/desktop
XDG_RUNTIME_DIR: /run/user/1003
XDG_SESSION_ID: 8020
_: /home/hualin/.cargo/bin/cargo

--- stderr
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/hualin/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/build.rs:365:34
stack backtrace:
   0:     0x5613147adeb5 - backtrace::backtrace::libunwind::trace::ha215bbf14e328799
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x5613147adeb5 - backtrace::backtrace::trace_unsynchronized::h3384b099b135857a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x5613147adeb5 - std::sys_common::backtrace::_print_fmt::hfec93740f7294682
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x5613147adeb5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5fe20777f4174074
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x5613147d2fec - core::fmt::write::he14c3177144df275
                               at src/libcore/fmt/mod.rs:1076
   5:     0x5613147a9d63 - std::io::Write::write_fmt::h8e26323bfab8bcc5
                               at src/libstd/io/mod.rs:1537
   6:     0x5613147b0790 - std::sys_common::backtrace::_print::h9cfa4c87526ba064
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x5613147b0790 - std::sys_common::backtrace::print::h94936584848b3272
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x5613147b0790 - std::panicking::default_hook::{{closure}}::h733b20cc9b496e46
                               at src/libstd/panicking.rs:198
   9:     0x5613147b04dc - std::panicking::default_hook::h556d8cff6c12a651
                               at src/libstd/panicking.rs:218
  10:     0x5613147b0dc7 - std::panicking::rust_panic_with_hook::ha0c7ca5b39baa9d5
                               at src/libstd/panicking.rs:486
  11:     0x5613147b09cb - rust_begin_unwind
                               at src/libstd/panicking.rs:388
  12:     0x5613147d23f1 - core::panicking::panic_fmt::h106d7128cbbc7cd2
                               at src/libcore/panicking.rs:101
  13:     0x5613147d233d - core::panicking::panic::hfe03c118d2519816
                               at src/libcore/panicking.rs:56
  14:     0x56131473e358 - core::option::Option<T>::unwrap::h348e260064194f0a
                               at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libcore/macros/mod.rs:10
  15:     0x56131472a01e - build_script_build::build_c_code::h23f13d1e4f0e24f3
                               at /home/hualin/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/build.rs:365
  16:     0x5613147292a0 - build_script_build::ring_build_rs_main::h76c9dd8d7568c879
                               at /home/hualin/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/build.rs:294
  17:     0x5613147288f9 - build_script_build::main::h2e32dac8d8ab96e8
                               at /home/hualin/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/build.rs:256
  18:     0x56131473e95b - std::rt::lang_start::{{closure}}::h634c1aab0366f4d1
                               at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libstd/rt.rs:67
  19:     0x5613147b1198 - std::rt::lang_start_internal::{{closure}}::hefb489d56a389b75
                               at src/libstd/rt.rs:52
  20:     0x5613147b1198 - std::panicking::try::do_call::hb2bfa58b743656f1
                               at src/libstd/panicking.rs:297
  21:     0x5613147b1198 - std::panicking::try::haaa85a89ce3784c3
                               at src/libstd/panicking.rs:274
  22:     0x5613147b1198 - std::panic::catch_unwind::h49baa277f74e60cb
                               at src/libstd/panic.rs:394
  23:     0x5613147b1198 - std::rt::lang_start_internal::h7aa2f6739b31fe58
                               at src/libstd/rt.rs:51
  24:     0x56131473e937 - std::rt::lang_start::h5b71a7b756435453
                               at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libstd/rt.rs:67
  25:     0x56131472fd0a - main
  26:     0x7fc4df976b97 - __libc_start_main
  27:     0x56131472840a - _start
  28:                0x0 - <unknown>

warning: build failed, waiting for other jobs to finish...
error: build failed
`
I check the build.rs. It seems that the build.rs has a list of target, which does not contain the target I am using.
I am using a custom linker for this build. I try directly building the project for ubuntu and it successes.

**Comment by pietro** [comment] 2020-08-31 19:37
MIPS is not currently supported by ring. the currently supported platforms are the ones listed in build.rs.

**Comment by briansmith** [comment] 2020-11-24 08:17
Thanks for filing this issue. I'm going to close this as a duplicate of #562 so there's just one open issue tracking MIPS support.

**Closed by briansmith** 2020-11-24 08:17 UTC
