### ISSUE TITLE
build panic on ppc

### ISSUE THREAD

**Issue by frank6600** [briansmith/ring#1567] opened 2022-12-08 00:04 UTC
As title, build whill panic on ppc,
Option::unwrap() on a None value, build.rs:358:10

**Comment by he32** [comment] 2022-12-14 19:13
This is `ring`s way of telling you "not implemented for this platform".
I have the same itch, as bulk pkgsrc builder for NetBSD/powerpc, and I see an increasing number of rust packages fail to build due to the vendored inclusion of this module.
The list of supported platforms can be found around line 216 in `build.rs` in the `ASM_TARGETS` table.

**Comment by briansmith** [comment] 2023-08-23 18:22
Closing this as a duplicate of an earlier PPC issue.

**Closed by briansmith** 2023-08-23 18:22 UTC
