### ISSUE TITLE
How to serialize EphemeralPrivateKey?

### ISSUE THREAD

**Issue by shi-yan** [briansmith/ring#1761] opened 2023-10-18 17:32 UTC
I'm implementing an end-to-end encrypted group messaging system. The idea is for each message, there is an attached pool of encryption keys, one for each allowed reader.

I want to use ring's agreement implementation for this purpose. But I don't know how to serialize the EphemeralPrivateKey. I need to serialize it, because I need each reader to be able to save this key on disk, and share their publickey. And whenever a message comes in, a reader can deserialize the private key to decode the message.

But I found no API to allow that. It seems that only the public key can be serialized. I inspected the code, and only found a private method for serialization. 

I'm not an expert in cryptography. I wonder if this is a missing implementation, or this is on purpose? perhaps, the EphemeralPrivateKey should never be dumped into a file and should be fresh for each message exchange? However, in my system, syncing public keys can't happen frequently. Participants need to generate the key pair at the beginning and keep them for the rest of the time. 

Secondly, I wonder if the serialization interface for the signature keypair can be improved. Currently, the design is like the following:

```rust
let pkcs8_bytes = signature::Ed25519KeyPair::generate_pkcs8(&rng)?;

// Normally the application would store the PKCS#8 file persistently. Later
// it would read the PKCS#8 file from persistent storage to use it.

let key_pair = signature::Ed25519KeyPair::from_pkcs8(pkcs8_bytes.as_ref())?;
```

the pkcs8_bytes can only be saved at the time of generation. There is no way to convert key_pair back to pkcs8_bytes? therefore, I have to keep both pkcs8_bytes and key_pair? one for saving, and one for other operations? This feels like redundancy. Why can't we have key_pair -> pkcs8_bytes ?

Thanks

**Comment by briansmith** [comment] 2023-10-18 18:59
Hi, this is a duplicate of #331.

**Closed by briansmith** 2023-10-18 18:58 UTC
Labels: duplicate

**Comment by 988494** [comment] 2024-12-05 04:10
The same scenario is encountered: IM IM, end-to-end encryption, the peer party is not online, you need to store the private key
