### ISSUE TITLE
Fails to compile for `mips-unknown-linux-musl` target

### ISSUE THREAD

**Issue by drasko** [briansmith/ring#818] opened 2019-05-07 22:26 UTC
```
drasko@Marx:~/rust/ring$ cargo build --target mips-unknown-linux-musl
    Updating crates.io index
    Updating git repository `https://github.com/briansmith/untrusted`
  Downloaded spin v0.5.0
   Compiling libc v0.2.54
   Compiling cc v1.0.36
   Compiling lazy_static v1.3.0
   Compiling spin v0.5.0
   Compiling untrusted v0.6.2 (https://github.com/briansmith/untrusted?tag=ring-master#b06b3933)
   Compiling ring v0.14.6 (/home/drasko/rust/ring)
error: failed to run custom build command for `ring v0.14.6 (/home/drasko/rust/ring)`
process didn't exit successfully: `/home/drasko/rust/ring/target/debug/build/ring-76fab52866d5f2ea/build-script-build` (exit code: 101)
--- stdout
CARGO: /home/drasko/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo
CARGO_CFG_DEBUG_ASSERTIONS: 
CARGO_CFG_PROC_MACRO: 
CARGO_CFG_TARGET_ARCH: mips
CARGO_CFG_TARGET_ENDIAN: big
CARGO_CFG_TARGET_ENV: musl
CARGO_CFG_TARGET_FAMILY: unix
CARGO_CFG_TARGET_OS: linux
CARGO_CFG_TARGET_POINTER_WIDTH: 32
CARGO_CFG_TARGET_VENDOR: unknown
CARGO_CFG_UNIX: 
CARGO_FEATURE_DEFAULT: 1
CARGO_FEATURE_DEV_URANDOM_FALLBACK: 1
CARGO_FEATURE_USE_HEAP: 1
CARGO_HOME: /home/drasko/.cargo
CARGO_MAKEFLAGS: --jobserver-fds=3,11 -j --jobserver-auth=3,11 -j
CARGO_MANIFEST_DIR: /home/drasko/rust/ring
CARGO_MANIFEST_LINKS: ring-asm
CARGO_PKG_AUTHORS: Brian Smith <brian@briansmith.org>
CARGO_PKG_DESCRIPTION: Safe, fast, small crypto using Rust.
CARGO_PKG_HOMEPAGE: 
CARGO_PKG_NAME: ring
CARGO_PKG_REPOSITORY: https://github.com/briansmith/ring
CARGO_PKG_VERSION: 0.14.6
CARGO_PKG_VERSION_MAJOR: 0
CARGO_PKG_VERSION_MINOR: 14
CARGO_PKG_VERSION_PATCH: 6
CARGO_PKG_VERSION_PRE: 
COLORTERM: truecolor
DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
DEBUG: true
DESKTOP_SESSION: gnome
DISPLAY: :0
GDMSESSION: gnome
GJS_DEBUG_OUTPUT: stderr
GJS_DEBUG_TOPICS: JS ERROR;JS LOG
GNOME_DESKTOP_SESSION_ID: this-is-deprecated
GNOME_TERMINAL_SCREEN: /org/gnome/Terminal/screen/a97e8e6d_f05a_4cb2_acf8_8dc421133e5f
GNOME_TERMINAL_SERVICE: :1.67
GOBIN: /home/drasko/go/bin
GOPATH: /home/drasko/go
GPG_AGENT_INFO: /run/user/1000/gnupg/S.gpg-agent:0:1
GTK_MODULES: gail:atk-bridge
HOME: /home/drasko
HOST: x86_64-unknown-linux-gnu
LANG: en_US.UTF-8
LANGUAGE: en_US:en
LD_LIBRARY_PATH: /home/drasko/rust/ring/target/debug/deps:/home/drasko/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib:/home/drasko/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib
LOGNAME: drasko
LS_COLORS: rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
NUM_JOBS: 8
OLDPWD: /home/drasko/rust
OPT_LEVEL: 0
OUT_DIR: /home/drasko/rust/ring/target/mips-unknown-linux-musl/debug/build/ring-012e4a56eefe7470/out
PATH: /home/drasko/.cargo/bin:/home/drasko/.npm-global/bin:/home/drasko/.nimble/bin:/home/drasko/fabric/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/go/bin:/home/drasko/go/bin:/home/drasko/linaro/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf/bin:/home/drasko/.cargo/bin
PROFILE: debug
PWD: /home/drasko/rust/ring
QT_ACCESSIBILITY: 1
RUSTC: rustc
RUSTC_LINKER: mips-openwrt-linux-musl-gcc
RUSTDOC: rustdoc
RUSTUP_HOME: /home/drasko/.rustup
RUSTUP_TOOLCHAIN: stable-x86_64-unknown-linux-gnu
RUST_RECURSION_COUNT: 1
SESSION_MANAGER: local/Marx:@/tmp/.ICE-unix/2509,unix/Marx:/tmp/.ICE-unix/2509
SHELL: /bin/bash
SHLVL: 1
SSH_AGENT_PID: 2543
SSH_AUTH_SOCK: /run/user/1000/keyring/ssh
SSL_CERT_DIR: /usr/lib/ssl/certs
SSL_CERT_FILE: /usr/lib/ssl/certs/ca-certificates.crt
TARGET: mips-unknown-linux-musl
TERM: xterm-256color
USER: drasko
VTE_VERSION: 5402
XAUTHORITY: /home/drasko/.Xauthority
XDG_CURRENT_DESKTOP: GNOME
XDG_DATA_DIRS: /usr/share/gnome:/usr/local/share/:/usr/share/
XDG_GREETER_DATA_DIR: /var/lib/lightdm/data/drasko
XDG_MENU_PREFIX: gnome-
XDG_RUNTIME_DIR: /run/user/1000
XDG_SEAT: seat0
XDG_SEAT_PATH: /org/freedesktop/DisplayManager/Seat0
XDG_SESSION_CLASS: user
XDG_SESSION_DESKTOP: gnome
XDG_SESSION_ID: 2
XDG_SESSION_PATH: /org/freedesktop/DisplayManager/Session0
XDG_SESSION_TYPE: x11
XDG_VTNR: 7
_: /home/drasko/.cargo/bin/cargo

--- stderr
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

```

**Comment by pietro** [comment] 2019-05-08 15:23
Mips is not supported by ring. See #562 and #804.

**Comment by briansmith** [comment] 2020-02-03 22:46
Closing as a duplicate of #562.

**Closed by briansmith** 2020-02-03 22:46 UTC
Labels: duplicate
