### ISSUE TITLE
Cross-compiling targeting macOS on a Linux host fails with GCC as the compiler

### ISSUE THREAD

**Issue by elichai** [briansmith/ring#832] opened 2019-06-06 15:40 UTC
Running `cargo build --release --target x86_64-apple-darwin` with latest stable (`rustc 1.35.0`) fails: 
```
   Compiling libc v0.2.58
   Compiling cc v1.0.37
   Compiling spin v0.5.0
   Compiling untrusted v0.6.2 (https://github.com/briansmith/untrusted?tag=ring-master#b06b3933)
   Compiling ring v0.14.6 (/home/elichai2/gits/ring)
error: failed to run custom build command for `ring v0.14.6 (/home/elichai2/gits/ring)`
process didn't exit successfully: `/home/elichai2/gits/ring/target/release/build/ring-37be99af40d3ae2a/build-script-build` (exit code: 101)
--- stdout
BYOBU_ACCENT: \#75507B
BYOBU_BACKEND: tmux
BYOBU_CHARMAP: UTF-8
BYOBU_CONFIG_DIR: /home/elichai2/.byobu
BYOBU_DARK: \#333333
BYOBU_DATE: %Y-%m-%d 
BYOBU_DISTRO: Arch Linux
BYOBU_EDITOR: vim
BYOBU_HIGHLIGHT: \#DD4814
BYOBU_LIGHT: \#EEEEEE
BYOBU_PAGER: less
BYOBU_PREFIX: /usr
BYOBU_PYTHON: python3
BYOBU_READLINK: readlink
BYOBU_RUN_DIR: /dev/shm/byobu-elichai2-lKA0eHN5
BYOBU_SED: sed
BYOBU_TERM: screen-256color
BYOBU_TIME: %H:%M:%S
BYOBU_TTY: /dev/pts/0
BYOBU_ULIMIT: ulimit
BYOBU_WINDOW_NAME: -
CARGO: /home/elichai2/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo
CARGO_CFG_DEBUG_ASSERTIONS: 
CARGO_CFG_PROC_MACRO: 
CARGO_CFG_TARGET_ARCH: x86_64
CARGO_CFG_TARGET_ENDIAN: little
CARGO_CFG_TARGET_ENV: 
CARGO_CFG_TARGET_FAMILY: unix
CARGO_CFG_TARGET_FEATURE: fxsr,sse,sse2,sse3,ssse3
CARGO_CFG_TARGET_OS: macos
CARGO_CFG_TARGET_POINTER_WIDTH: 64
CARGO_CFG_TARGET_VENDOR: apple
CARGO_CFG_UNIX: 
CARGO_FEATURE_DEFAULT: 1
CARGO_FEATURE_DEV_URANDOM_FALLBACK: 1
CARGO_FEATURE_USE_HEAP: 1
CARGO_HOME: /home/elichai2/.cargo
CARGO_MAKEFLAGS: --jobserver-fds=3,10 -j --jobserver-auth=3,10 -j
CARGO_MANIFEST_DIR: /home/elichai2/gits/ring
CARGO_MANIFEST_LINKS: ring-asm
CARGO_PKG_AUTHORS: Brian Smith <brian@briansmith.org>
CARGO_PKG_DESCRIPTION: Safe, fast, small crypto using Rust.
CARGO_PKG_HOMEPAGE: 
CARGO_PKG_NAME: ring
CARGO_PKG_REPOSITORY: https://github.com/briansmith/ring
CARGO_PKG_VERSION: 0.14.6
CARGO_PKG_VERSION_MAJOR: 0
CARGO_PKG_VERSION_MINOR: 14
CARGO_PKG_VERSION_PATCH: 6
CARGO_PKG_VERSION_PRE: 
COLORFGBG: 15;0
COLORTERM: truecolor
DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
DEBUG: false
DESKTOP_SESSION: /usr/share/xsessions/plasma
DISPLAY: :0
EDITOR: vim
GPG_TTY: /dev/pts/3
GS_LIB: /home/elichai2/.fonts
GTK2_RC_FILES: /etc/gtk-2.0/gtkrc:/home/elichai2/.gtkrc-2.0:/home/elichai2/.config/gtkrc-2.0
GTK_MODULES: canberra-gtk-module
GTK_RC_FILES: /etc/gtk/gtkrc:/home/elichai2/.gtkrc:/home/elichai2/.config/gtkrc
HOME: /home/elichai2
HOST: x86_64-unknown-linux-gnu
KDE_FULL_SESSION: true
KDE_SESSION_UID: 1000
KDE_SESSION_VERSION: 5
KONSOLE_DBUS_SERVICE: :1.40
KONSOLE_DBUS_SESSION: /Sessions/1
KONSOLE_PROFILE_NAME: Default
KONSOLE_VERSION: 190401
LANG: en_US.UTF-8
LANGUAGE: 
LD_LIBRARY_PATH: /home/elichai2/gits/ring/target/release/deps:/home/elichai2/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib:/home/elichai2/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib
LOGNAME: elichai2
MAIL: /var/spool/mail/elichai2
NUM_JOBS: 8
OLDPWD: /home/elichai2/gits
OPT_LEVEL: 3
OUT_DIR: /home/elichai2/gits/ring/target/x86_64-apple-darwin/release/build/ring-4107c324bda3fc8b/out
PAM_KWALLET5_LOGIN: /run/user/1000/kwallet5.socket
PATH: /home/elichai2/.cargo/bin:/home/elichai2/.local/bin:/home/elichai2/.local/bin:/home/elichai2/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
PROFILE: release
PROFILEHOME: 
PS1: \[\e[31m\]$(byobu_prompt_status)\[\e[38;5;69m\]\u\[\e[38;5;214m\]@\[\e[38;5;167m\]\h\[\e[38;5;214m\]:\[\e[38;5;71m\]\w\[\e[38;5;214m\]$(byobu_prompt_symbol)\[\e[00m\] 
PWD: /home/elichai2/gits/ring
QT_AUTO_SCREEN_SCALE_FACTOR: 0
RUSTC: rustc
RUSTDOC: rustdoc
RUSTUP_HOME: /home/elichai2/.rustup
RUSTUP_TOOLCHAIN: stable-x86_64-unknown-linux-gnu
RUST_RECURSION_COUNT: 1
SESSION_MANAGER: local/nphard-core:@/tmp/.ICE-unix/745,unix/nphard-core:/tmp/.ICE-unix/745
SHELL: /bin/bash
SHELL_SESSION_ID: 565fe9d5432d42fbbca025ca38592569
SHLVL: 3
SSL_CERT_DIR: /etc/ssl/certs
SSL_CERT_FILE: /etc/ssl/cert.pem
TARGET: x86_64-apple-darwin
TERM: screen-256color
TMUX: /tmp/tmux-1000/default,2553,1
TMUX_PANE: %1
USER: elichai2
WINDOWID: 52428807
XAUTHORITY: /tmp/xauth-1000-_0
XCURSOR_THEME: breeze_cursors
XDG_CURRENT_DESKTOP: KDE
XDG_DATA_DIRS: /usr/share:/usr/share:/usr/local/share
XDG_RUNTIME_DIR: /run/user/1000
XDG_SEAT: seat0
XDG_SEAT_PATH: /org/freedesktop/DisplayManager/Seat0
XDG_SESSION_CLASS: user
XDG_SESSION_DESKTOP: KDE
XDG_SESSION_ID: 2
XDG_SESSION_PATH: /org/freedesktop/DisplayManager/Session1
XDG_SESSION_TYPE: x11
XDG_VTNR: 1
_: /home/elichai2/.cargo/bin/cargo
running "perl" "crypto/fipsmodule/aes/asm/aes-x86_64.pl" "macosx" "/home/elichai2/gits/ring/target/x86_64-apple-darwin/release/build/ring-4107c324bda3fc8b/out/aes-x86_64-macosx.S"
running "perl" "crypto/fipsmodule/aes/asm/aesni-x86_64.pl" "macosx" "/home/elichai2/gits/ring/target/x86_64-apple-darwin/release/build/ring-4107c324bda3fc8b/out/aesni-x86_64-macosx.S"
running "perl" "crypto/fipsmodule/aes/asm/vpaes-x86_64.pl" "macosx" "/home/elichai2/gits/ring/target/x86_64-apple-darwin/release/build/ring-4107c324bda3fc8b/out/vpaes-x86_64-macosx.S"
running "perl" "crypto/fipsmodule/bn/asm/x86_64-mont.pl" "macosx" "/home/elichai2/gits/ring/target/x86_64-apple-darwin/release/build/ring-4107c324bda3fc8b/out/x86_64-mont-macosx.S"
running "perl" "crypto/fipsmodule/bn/asm/x86_64-mont5.pl" "macosx" "/home/elichai2/gits/ring/target/x86_64-apple-darwin/release/build/ring-4107c324bda3fc8b/out/x86_64-mont5-macosx.S"
running "perl" "crypto/chacha/asm/chacha-x86_64.pl" "macosx" "/home/elichai2/gits/ring/target/x86_64-apple-darwin/release/build/ring-4107c324bda3fc8b/out/chacha-x86_64-macosx.S"
running "perl" "crypto/fipsmodule/ec/asm/p256-x86_64-asm.pl" "macosx" "/home/elichai2/gits/ring/target/x86_64-apple-darwin/release/build/ring-4107c324bda3fc8b/out/p256-x86_64-asm-macosx.S"
running "perl" "crypto/fipsmodule/modes/asm/aesni-gcm-x86_64.pl" "macosx" "/home/elichai2/gits/ring/target/x86_64-apple-darwin/release/build/ring-4107c324bda3fc8b/out/aesni-gcm-x86_64-macosx.S"
running "perl" "crypto/fipsmodule/modes/asm/ghash-x86_64.pl" "macosx" "/home/elichai2/gits/ring/target/x86_64-apple-darwin/release/build/ring-4107c324bda3fc8b/out/ghash-x86_64-macosx.S"
running "perl" "crypto/poly1305/asm/poly1305-x86_64.pl" "macosx" "/home/elichai2/gits/ring/target/x86_64-apple-darwin/release/build/ring-4107c324bda3fc8b/out/poly1305-x86_64-macosx.S"
running "perl" "crypto/fipsmodule/sha/asm/sha512-x86_64.pl" "macosx" "/home/elichai2/gits/ring/target/x86_64-apple-darwin/release/build/ring-4107c324bda3fc8b/out/sha512-x86_64-macosx.S"
running "perl" "crypto/fipsmodule/sha/asm/sha512-x86_64.pl" "macosx" "/home/elichai2/gits/ring/target/x86_64-apple-darwin/release/build/ring-4107c324bda3fc8b/out/sha256-x86_64-macosx.S"
OPT_LEVEL = Some("3")
TARGET = Some("x86_64-apple-darwin")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-apple-darwin = None
CC_x86_64_apple_darwin = None
TARGET_CC = None
CC = None
CROSS_COMPILE = None
CFLAGS_x86_64-apple-darwin = None
CFLAGS_x86_64_apple_darwin = None
TARGET_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("false")
CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2,sse3,ssse3")
running "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-gfull" "-Werror" "-DNDEBUG" "-D_XOPEN_SOURCE=700" "-c" "-o/home/elichai2/gits/ring/target/x86_64-apple-darwin/release/build/ring-4107c324bda3fc8b/out/aes-x86_64-macosx.o" "/home/elichai2/gits/ring/target/x86_64-apple-darwin/release/build/ring-4107c324bda3fc8b/out/aes-x86_64-macosx.S"

--- stderr
cc: error: unrecognized debug output level ‘full’
thread 'main' panicked at 'execution failed', build.rs:657:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

```

**Comment by briansmith** [comment] 2019-06-06 18:02
> Running `cargo build --release --target x86_64-apple-darwin` with latest stable (`rustc 1.35.0`) fails:

I understand your host is Linux. Did this cross-compiling ever work before?

**Comment by briansmith** [comment] 2019-06-06 18:03
Please share `cc --version`.

**Comment by elichai** [comment] 2019-06-06 20:53
Yeah, I realized that it's a cross compiling problem and not compiling to mac problem.

I'm trying to use travis to compiler for different OS's

if you're interested anyway `cc (GCC) 8.3.0`

**Comment by briansmith** [comment] 2019-06-06 21:16
I would like to support cross-compiling to mac. The problem seems to be that GCC doesn't understand `-gfull`. I'm open to doing something to address that, but I don't have time to do the research right now. If somebody does do the research and they can type up a clear explanation of what the best change is, we can go ahead and make that change.

**Comment by briansmith** [comment] 2019-07-12 18:51
> I'm trying to use travis to compiler for different OS's

You can have Travis CI run on Mac as well as Linux (and Windows too, now, I've heard). We do that in *ring*'s Travis CI.

I'm going to close this as "unfortunately this is expected behavior."

**Closed by briansmith** 2019-07-12 18:51 UTC
