### ISSUE TITLE
PKCS#8 parsing of RSA public keys

### ISSUE THREAD

**Issue by heartsucker** [briansmith/ring#530] opened 2017-05-06 10:45 UTC
Currently RSA keys are parsed with this from `src/rsa/rsa.rs`.

```rust
fn parse_public_key(input: untrusted::Input)
                    -> Result<(untrusted::Input, untrusted::Input),
                              error::Unspecified> {
    input.read_all(error::Unspecified, |input| {
        der::nested(input, der::Tag::Sequence, error::Unspecified, |input| {
            let n = try!(der::positive_integer(input));
            let e = try!(der::positive_integer(input));
            Ok((n, e)) 
        })
    })  
}
```

This only parses PKCS#1 keys and not the more generic PKCS#8 format that is common. I think it would be useful to support the other format so that someone can call `signature::verify(RSA_*, pub, msg, sig)` and have it "just work" regardless of the format of the public key.

**Comment by briansmith** [comment] 2017-05-06 10:50
> This only parses PKCS#1 keys and not the more generic PKCS#8 format that is common. 

Is it actually common to store public keys in PKCS#8 files? If so, it would be no problem for us to support something like that, maybe with a new `verify_pkcs8()` or similar.

> I think it would be useful to support the other format so that someone can call signature::verify(RSA_*, pub, msg, sig) and have it "just work" regardless of the format of the public key.

`signature::verify()` needs to be restricted to the "bare" public key formats because some protocols/formats only allow the bare public key format.

Maybe it would be useful to have a `signature::verify_whatever()` too, though. I'm not sure.

**Comment by heartsucker** [comment] 2017-05-06 10:52
Right now I'm using python libs to generate test casts for the `rust-tuf` project, and it spits out the public keys in PKCS#8 format. Bouncy Castle which is being used for a server side implementation at work uses PKCS#8 too. I'm not sure if that's the default, but that's what our devs implemented.

**Comment by briansmith** [comment] 2017-05-06 11:02
I think those projects are more likely exporting the `SubjectPublicKeyInfo` format, not PKCS#8. Could you double-check? Maybe you could attach one or paste the Base64/PEM here.

**Comment by heartsucker** [comment] 2017-05-06 11:06
```
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAndqFFxVnq7FjihMB7sBj
fMMIS2112HB0PauY7wDQ8gTnfbWkCOOQ2kvh0f8Ph41rQ1iZiPaZq+eQ+yqhPCsP
JKSeq9H8oOCon4JI5afSTUTkC0NmA1SN3cMMJvUgNr+uBWOc+IHr90o6xBTuzplm
nzzjGCGNaOMLt7P3yuF8q9UXb1DBOBvqYutGB5UB+9Ma0K4c5lMnUy0IVb6j1tEC
FKSi4RTepA5UAOV5LE2T6Gs89kRjhTxvVsKAAj92z3VGX5pJR9zm6ZrAbjSen9Lf
vFWgd2Hz1Qy4d9Jm0iSaJb5VG06/O4JMT1FXfIv2OP5NlzKoyDxp5ZEVLHWNksHH
awIDAQAB
-----END PUBLIC KEY-----
```

**Comment by briansmith** [comment] 2017-05-06 11:09
OK, yes, that's `SubjectPublickeyInfo`, not PKCS#8. So merging the other work to add `SubjectPublickeyInfo` support will resolve this satisfactorily, I think.

**Comment by heartsucker** [comment] 2017-05-06 11:10
What commands are you using to run that check? Openssl is still some horrible black box for half its operations.

**Comment by briansmith** [comment] 2017-05-06 11:12
I put it into https://lapo.it/asn1js/#30820122300D06092A864886F70D01010105000382010F003082010A02820101009DDA85171567ABB1638A1301EEC0637CC3084B6D75D870743DAB98EF00D0F204E77DB5A408E390DA4BE1D1FF0F878D6B43589988F699ABE790FB2AA13C2B0F24A49EABD1FCA0E0A89F8248E5A7D24D44E40B436603548DDDC30C26F52036BFAE05639CF881EBF74A3AC414EECE99669F3CE318218D68E30BB7B3F7CAE17CABD5176F50C1381BEA62EB46079501FBD31AD0AE1CE65327532D0855BEA3D6D10214A4A2E114DEA40E5400E5792C4D93E86B3CF64463853C6F56C280023F76CF75465F9A4947DCE6E99AC06E349E9FD2DFBC55A07761F3D50CB877D266D2249A25BE551B4EBF3B824C4F51577C8BF638FE4D9732A8C83C69E591152C758D92C1C76B0203010001 and recognized it as a SPKI and not a PKCS#8 from memory.

**Comment by heartsucker** [comment] 2017-05-06 11:16
Got it. Is this something you can tackle yourself? Or do you need me to make a PR for it?

**Comment by briansmith** [comment] 2017-05-06 11:17
Are you sure that TUF wants the public keys in this format? The info at https://github.com/theupdateframework/tuf/blob/develop/docs/tuf-spec.txt seems to indicate that it has its own JSON metadata wrapper around the bare public key (i.e. a JSON wrapper around the format *ring* already supports).

**Comment by heartsucker** [comment] 2017-05-06 11:19
The TUF spec only states "in PEM format" which really leaves a lot of possibilities.

**Comment by briansmith** [comment] 2017-05-06 11:22
Yes, but considering the type is specified in the JSON I think they probably weren't intending SPKI format, since SPKI format is a wrapper around the bare key that adds the type information. So, unless you find out that the SPKI format is the only format you're supposed to support, I recommend just converting your SPKI format keys to the bare form for now (maybe forever).

**Comment by briansmith** [comment] 2017-05-06 11:24
Also, FYI, the openssl command to convert SPKI format to the unwrapped format is in the *ring* documentation already: https://briansmith.org/rustdoc/ring/signature/index.html#signing-and-verifying-with-rsa-pkcs1-15-padding.

I'm going to close this since it's a dupe of #370.

**Closed by briansmith** 2017-05-06 11:24 UTC
