### ISSUE TITLE
ring v0.16.20 building on target  board on riscv64 platform

### ISSUE THREAD

**Issue by kush930** [briansmith/ring#1615] opened 2023-06-20 07:26 UTC
Hi all,

```
I am using gcc-10.1.0 and glibc-3.2.1 , and using ring from link: https://github.com/briansmith/ring.git

I am building on target board, this source not having riscv support,  i modified inside source from the link:-  https://github.com/briansmith/ring/pull/1556/commits/22fae8e15edddac0891404ddb5a621bb6301e234

when i prefer this link there i got these changes  inside mk/cargo.sh 

**qemu_riscv64="qemu-riscv64 -L /usr/riscv64-linux-gnu"
riscv64gc-unknown-linux-gnu)
    export CC_riscv64gc_unknown_linux_gnu=riscv64-linux-gnu-gcc
    export AR_riscv64gc_unknown_linux_gnu=riscv64-linux-gnu-gcc-ar
    export CARGO_TARGET_RISCV64GC_UNKNOWN_LINUX_GNU_LINKER=riscv64-linux-gnu-gcc
    export CARGO_TARGET_RISCV64GC_UNKNOWN_LINUX_GNU_RUNNER="$qemu_riscv64"**
    ;;

i donot need for qemu, i am building on target board, Can anyone help me to build ring 0.16.20 on target board.
```

T&R
luvkhush

**Comment by briansmith** [comment] 2023-08-22 20:45
Closing as a duplicate of #1612. Please see that issue.

**Closed by briansmith** 2023-08-22 20:45 UTC
Labels: duplicate
