### ISSUE TITLE
`RSAPadding` isn't accessible to users of *ring*

### ISSUE THREAD

**Issue by bt** [briansmith/ring#310] opened 2016-10-06 05:33 UTC
Is it intentional that the `rsa` module is private?

My use-case currently is that I have my own application `Algorithm` enum that I use to match against `RSAPadding` in `ring`.

```
fn get_rsa_algorithm(alg: Algorithm) -> &'static ring::rsa::RSAPadding {
    match alg {
        Algorithm::RSA256 => &signature::RSA_PKCS1_SHA256,
    }
}
```

That seems to give me an error:

```
error: module `rsa` is private
 --> crypt.rs
  |
2 | use ring::rsa::RSAPadding;
  |     ^^^^^^^^^^^^^^^^^^^^^
```

**Comment by briansmith** [comment] 2016-10-06 20:18
The problem is just that you can't use `RSAPadding`, and not all of RSA, right? I agree `RSAPadding` should be public. However, I'd rather not make the whole `ring::rsa` submodule public if we can avoid it.

Note that in the next (Git master) version, these things have been renamed. I'll update this issue with the new names when they are exposed publicly.

**Comment by bt** [comment] 2016-10-07 11:16
Hey @briansmith thanks for answering my question.

What's the ETA for the new version? I'm starting a new project and forked to make the `rsa` module public for now but given that you're going through a refactor, I might work on other areas of my app for the time being.

**Comment by briansmith** [comment] 2016-10-18 05:53
> Hey @briansmith thanks for answering my question.
> 
> What's the ETA for the new version? I'm starting a new project and forked to make the rsa module public for now but given that you're going through a refactor, I might work on other areas of my app for the time being.

Within October, for sure. Hopefully this week.

**Comment by briansmith** [comment] 2016-11-15 01:09
Hi,

Do you need this for signature verification, signing, or both?

If you only need it for signature verification, it is already possible to do by mapping your enum to `&ring::signature::VerificationAlgorithm`.

If you need signing then that requires more work.

**Comment by briansmith** [comment] 2016-11-15 02:36
> ```rust
> fn get_rsa_algorithm(alg: Algorithm) -> &'static ring::rsa::RSAPadding {
>     match alg {
>         Algorithm::RSA256 => &signature::RSA_PKCS1_SHA256,
>     }
> }
> ```

I think in the short term, at least, you'll need to write this as something like:

```rust
fn get_signature_verification_algorithm(alg: Algorithm)
        -> &'static ring::signature::VerificationAlgorithm {
    match alg {
        Algorithm::ES256 => &signature::ECDSA_P256_SHA256,
        Algorithm::ES384 => &signature::ECDSA_P384_SHA384,
        Algorithm::RSA256 => &signature::RSA_PKCS1_SHA256_2048_8192,
        Algorithm::RSA384 => &signature::RSA_PKCS1_SHA384_2048_8192,
        Algorithm::RSA512 => &signature::RSA_PKCS1_SHA512_2048_8192,
        ...
    }
}

fn get_rsa_signing_encoding(alg: Algorithm)
        -> Optoin<&'static ring::signature::RSAEncoding> {
    match alg {
        Algorithm::RSA256 => Some(&signature::RSA_PKCS1_SHA256,
        Algorithm::RSA384 => Some(&signature::RSA_PKCS1_SHA384,
        Algorithm::RSA512 => Some(&signature::RSA_PKCS1_SHA512,
        _ => None
    }
}
```

Note in particular that we have different types for signing operations and verification operations.

Are you able to use *ring* from Git, instead of from crates.io? If so, can you test out the code in the padding_public branch? I think the code on that branch is likely to work for code as written above.

**Comment by briansmith** [comment] 2016-11-15 02:39
I made the code in that branch into a PR: https://github.com/briansmith/ring/pull/349.

Note that `RSAPadding` was renamed to `RSAEncoding`.

**Comment by briansmith** [comment] 2016-11-15 22:24
I've now merged this into the master branch. I've also release *ring* 0.6.0-alpha (`ring = "0.6.0-alpha"`) so that it is easier to test this.

**Comment by bt** [comment] 2016-11-19 01:07
Hey @briansmith, thanks for fixing this and sorry for the late reply. Unfortunately, I've been moved to a different project within my division and hence I won't be able to test this at the current time ☹️

**Comment by briansmith** [comment] 2016-11-19 01:15
No trouble! Thanks for letting me know!

**Closed by briansmith** 2016-11-19 01:15 UTC
