### ISSUE TITLE
Ring build fails as sub dependency on rust nightly

### ISSUE THREAD

**Issue by haync** [briansmith/ring#1527] opened 2022-10-20 21:44 UTC
I'm getting a failed to run custom build command for `ring v0.16.20`

caused by `../target/debug/build/ring-ffac7../build-script-build` exit status `101`
-- stderr
thread 'main' panicked at called `Option::unwrap()`  on a `None` value `... /ring-0.16.20/build.rs:358:10`

**Comment by wiryfuture** [comment] 2022-10-29 18:10
Can confirm I've also run into this with ring 0.16.20, when i was trying to build ring.

**Comment by briansmith** [comment] 2022-10-29 19:15
Please provide some steps to reproduce starting with `git pull` and including `cargo build` or `cargo test` if possible.

**Comment by briansmith** [comment] 2022-10-31 16:47
Also, which target are you building for? When I do `cargo +nightly test` to build crates that use *ring* 0.16.20 and run their tests, on x86-64 Linux, they are working fine.

**Comment by briansmith** [comment] 2022-11-09 19:27
Thanks for the report. I'm going to close this since I've not heard anything back and we can't make any progress reproducing it. Please let me know if you have any more details that would help with reproducing the issue; then I would be happy to re-open it.

**Closed by briansmith** 2022-11-09 19:27 UTC
