### ISSUE TITLE
Support post-quantum key exchange

### ISSUE THREAD

**Issue by DemiMarie** [briansmith/ring#1045] opened 2020-08-16 17:12 UTC
DJB recommends NTRU Prime, but other algorithms are worth considering too.  For maximum robustness, we might want to take a bunch of different algorithms and hash the results.

**Comment by saolof** [comment] 2022-07-12 14:59
After the NIST standardization, CRYSTALS looks like the best option for general purpose, with the two other algorithms being useful for specific niches: https://pq-crystals.org/

**Comment by nashley** [comment] 2022-07-12 16:29
Link to NIST publication: https://csrc.nist.gov/Projects/post-quantum-cryptography/selected-algorithms-2022

**Comment by briansmith** [comment] 2023-10-14 04:00
Closing as a duplicate of #1685.

**Closed by briansmith** 2023-10-14 04:00 UTC
Labels: duplicate
