### ISSUE TITLE
confusing documentation on NonceSequence

### ISSUE THREAD

**Issue by Silur** [briansmith/ring#928] opened 2019-12-27 19:03 UTC
Trying to decipher the documentation around AEAD is already a cryptanalytic task, which gets worse by the fact that the required `NonceSequence` trait for an Opening/Sealing key is not implemented by any of the internal types in the crate.
https://github.com/briansmith/ring/blob/master/src/aead.rs#L74

Are we supposed to make a wrapper type for a nonce and implement it manually? (yikes)

**Comment by triska** [comment] 2020-05-19 08:12
It seems so! In my code, I have defined a a `OneNonceSequence` like this:

<pre>
struct OneNonceSequence(Option<aead::Nonce>);

impl OneNonceSequence {
    fn new(nonce: aead::Nonce) -> Self {
        Self(Some(nonce))
    }
}

impl aead::NonceSequence for OneNonceSequence {
    fn advance(&mut self) -> Result<aead::Nonce, error::Unspecified> {
        self.0.take().ok_or(error::Unspecified)
    }
}
</pre>

For decryption, with `key` and `iv` defined as vectors of bytes or integers, I managed to construct an opening key with:
<pre>
let unbound_key = aead::UnboundKey::new(&aead::CHACHA20_POLY1305, &key).unwrap();
let nonce_sequence = OneNonceSequence::new(aead::Nonce::try_assume_unique_for_key(&iv).unwrap());
let mut key: aead::OpeningKey<OneNonceSequence> = aead::BoundKey::new(unbound_key, nonce_sequence);
</pre>

I deduced this only from reading the implementation and the test cases, it was not apparent from the documentation.

**Comment by briansmith** [comment] 2020-05-21 21:28
`NonceSequence` is supposed to encapsulate the design of nonce generation described in TLS 1.3 and in the OpenSSH ChaCha20-Poly1305 (and maybe AES-GCM? I forget) designs: You construct your `NonceSequence` implementation with a certain value that will be the first nonce. `advance()` computes the next value of the nonce, saves it, and returns the old value.

**Comment by briansmith** [comment] 2020-05-21 21:29
Closing this as a dupe of #899.

**Closed by briansmith** 2020-05-21 21:29 UTC
