### ISSUE TITLE
Ring 0.11.0 failing to compile as a dependency on rustc 1.30.0-nightly (f49f6e73a 2018-09-23) on Windows

### ISSUE THREAD

**Issue by ncoish** [briansmith/ring#692] opened 2018-09-24 05:26 UTC
While trying to build Rocket with the latest nightly (1.30.0-nightly (f49f6e73a 2018-09-23)), when cargo attempted to build ring as a dependency, a large chain of failures occurred, which I have attached as a file to this report: 
[ring_build_failure.log](https://github.com/briansmith/ring/files/2409652/ring_build_failure.log).

Additional metadata:
$ rustc --version
rustc 1.30.0-nightly (f49f6e73a 2018-09-23)
$ cargo --version
cargo 1.31.0-nightly (de314a8b2 2018-09-21)
toolchain:
nightly-x86_64-pc-windows-msvc

If there is any other information I can provide, please let me know

**Comment by mati865** [comment] 2018-09-25 13:21
Possibly duplicate of https://github.com/briansmith/ring/issues/686

**Comment by andrewtj** [comment] 2018-09-26 00:10
0.11 isn't supported. See the [readme](https://github.com/briansmith/ring#versioning--stability) for the reason and search closed issues containing 0.11 for previous discussion.

**Comment by briansmith** [comment] 2018-10-05 01:01
I'm closing this as either a duplicate of #686 or "0.11 isn't supported." Thanks everybody!

**Closed by briansmith** 2018-10-05 01:01 UTC
