### ISSUE TITLE
cargo build --release --target=aarch64-linux-android error: ring-0.16.20/pregenerated/aesv8-armx-linux64.S"]: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by Ruijuan-Cao** [briansmith/ring#1193] opened 2021-02-07 19:40 UTC
host on linux
having install  Android SDK and NDK, and set ar and linker, like that in ~/.cargo/config

`[target.aarch64-linux-android] 
ar = "android-ndk-r22/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ar" 
linker = "android-ndk-r22/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android22-clang"`

but still build failed, try a lot, need some help

**Comment by briansmith** [comment] 2021-02-10 01:59
Are you building *ring* from a Git checkout? Are you building the release from crates.io? Have you vendored a copy of *ring*?

Please either post the ring dependency information from your Cargo.toml, or if you're building *ring* directly, please post the steps you used to acquire ring (`git clone` or whatever).

If yo are using *ring* from Git, does your checkout include the `.git` directory? If not, *ring* will look for the pregenerated assembly, which you won't have. The solution to this is to `cargo vendor` from crates.io instead of a Git checkout.

**Comment by mhill-holoplot** [comment] 2021-02-15 14:24
I have a similar issue with even after I ran a `cargo vendor` 

```
   Compiling ring v0.16.20
error: failed to run custom build command for `ring v0.16.20`

Caused by:
  process didn't exit successfully: `/home/morgan/workspace/vector/target/debug/build/ring-30f67b8446f8dcc8/build-script-build` (exit code: 101)
  --- stdout
  OPT_LEVEL = Some("0")
  TARGET = Some("arm-unknown-linux-gnueabihf")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_arm-unknown-linux-gnueabihf = None
  CC_arm_unknown_linux_gnueabihf = None
  TARGET_CC = None
  CC = None
  CROSS_COMPILE = None
  CFLAGS_arm-unknown-linux-gnueabihf = None
  CFLAGS_arm_unknown_linux_gnueabihf = None
  TARGET_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = None

  --- stderr
  running "arm-linux-gnueabihf-gcc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-march=armv6" "-marm" "-mfpu=vfp" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-DNDEBUG" "-c" "-o/home/morgan/workspace/vector/target/arm-unknown-linux-gnueabihf/debug/build/ring-670ae95a9f35627c/out/aesv8-armx-linux32.o" "/home/morgan/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/pregenerated/aesv8-armx-linux32.S"
  thread 'main' panicked at 'failed to execute ["arm-linux-gnueabihf-gcc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-march=armv6" "-marm" "-mfpu=vfp" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-DNDEBUG" "-c" "-o/home/morgan/workspace/vector/target/arm-unknown-linux-gnueabihf/debug/build/ring-670ae95a9f35627c/out/aesv8-armx-linux32.o" "/home/morgan/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/pregenerated/aesv8-armx-linux32.S"]: No such file or directory (os error 2)', /home/morgan/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/build.rs:653:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by ethanshry** [comment] 2021-02-15 21:08
I have the same issue with ring, trying to cross compile on an x86_64 ubuntu to target 64-bit ARM.

```bash
Compiling ring v0.16.20
error: failed to run custom build command for `ring v0.16.20`

Caused by:
  process didn't exit successfully: `[project-path]/target/release/build/ring-4ac6fc05b61d88ea/build-script-build` (exit code: 101)
  --- stdout
  OPT_LEVEL = Some("3")
  TARGET = Some("aarch64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_aarch64-unknown-linux-gnu = None
  CC_aarch64_unknown_linux_gnu = None
  TARGET_CC = None
  CC = None
  CROSS_COMPILE = None
  CFLAGS_aarch64-unknown-linux-gnu = None
  CFLAGS_aarch64_unknown_linux_gnu = None
  TARGET_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fp,neon")

  --- stderr
  running "aarch64-linux-gnu-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-DNDEBUG" "-c" "-o/[project-path]/target/aarch64-unknown-linux-gnu/release/build/ring-5b355de538f92288/out/aesv8-armx-linux64.o" "/[user-dir]/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/pregenerated/aesv8-armx-linux64.S"
  thread 'main' panicked at 'failed to execute ["aarch64-linux-gnu-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-DNDEBUG" "-c" "-o/[project-path]/target/aarch64-unknown-linux-gnu/release/build/ring-5b355de538f92288/out/aesv8-armx-linux64.o" "/[user-dir]/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/pregenerated/aesv8-armx-linux64.S"]: No such file or directory (os error 2)', /[user-dir]/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/build.rs:653:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
In my case the dependenct on ring comes from the`sct` crate, which seems to be using the crates.io `ring v0.16.20`

**Comment by lubovaskov** [comment] 2021-02-25 08:16
I have the same issue, trying to cross compile on x86_64 Windows to target ARMV7 Linux

```
Compiling ring v0.16.20
error: failed to run custom build command for `ring v0.16.20`

Caused by:
  process didn't exit successfully: `C:\Source\Rust\Projects\iota_core\target\release\build\ring-d2f2c6d5b902281d\build-script-build` (exit code: 101)
  --- stdout
  OPT_LEVEL = Some("3")
  TARGET = Some("armv7-unknown-linux-gnueabihf")
  HOST = Some("x86_64-pc-windows-msvc")
  CC_armv7-unknown-linux-gnueabihf = None
  CC_armv7_unknown_linux_gnueabihf = None
  TARGET_CC = None
  CC = None
  CROSS_COMPILE = None
  CFLAGS_armv7-unknown-linux-gnueabihf = None
  CFLAGS_armv7_unknown_linux_gnueabihf = None
  TARGET_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = None

  --- stderr
  running "arm-linux-gnueabihf-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-march=armv7-a" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-DNDEBUG" "-c" "-oC:\\Source\\Rust\\Projects\\iota_core\\target\\armv7-unknown-linux-gnueabihf\\release\\build\\ring-16ea47eab8ef28f2\\out\\aesv8-armx-linux32.o" "C:\\Source\\SDKs\\Rust\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\ring-0.16.20\\pregenerated\\aesv8-armx-linux32.S"
  thread 'main' panicked at 'failed to execute ["arm-linux-gnueabihf-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-march=armv7-a" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-DNDEBUG" "-c" "-oC:\\Source\\Rust\\Projects\\iota_core\\target\\armv7-unknown-linux-gnueabihf\\release\\build\\ring-16ea47eab8ef28f2\\out\\aesv8-armx-linux32.o" "C:\\Source\\SDKs\\Rust\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\ring-0.16.20\\pregenerated\\aesv8-armx-linux32.S"]: The system cannot find the file specified. (os error 2)', C:\Source\SDKs\Rust\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.16.20\build.rs:653:9
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b\/library\std\src\panicking.rs:493
     1: std::panicking::begin_panic_fmt
               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b\/library\std\src\panicking.rs:435
     2: build_script_build::run_command::{{closure}}
     3: core::result::Result<T,E>::unwrap_or_else
     4: build_script_build::build_library::{{closure}}
     5: build_script_build::build_library::{{closure}}
     6: build_script_build::build_c_code::{{closure}}
     7: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
     8: core::option::Option<T>::map
     9: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
    10: <alloc::vec::IntoIter<T,A> as core::iter::adapters::SourceIter>::as_inner
    11: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
    12: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
    13: core::iter::traits::iterator::Iterator::collect
    14: build_script_build::build_c_code::{{closure}}
    15: build_script_build::build_c_code::{{closure}}
    16: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::for_each
    17: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
    18: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
    19: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
    20: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by bdbai** [comment] 2021-02-26 09:48
Same problem here when compiling for `thumbv7a-uwp-windows-msvc` (see [output](https://gist.github.com/bdbai/ff93935e702407bc3125a79ae28b4e31)). 

In `Cargo.toml`, *ring* is specified as
```toml
# Ring
ring = { version = "0.16", optional = true }
```
which resolves to
```toml
[[package]]
name = "ring"
version = "0.16.20"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "3053cf52e236a3ed746dfc745aa9cacf1b791d846bdaf412f60a8d7d6e17c8fc"
dependencies = [
 "cc",
 "libc",
 "once_cell",
 "spin",
 "untrusted",
 "web-sys",
 "winapi 0.3.9",
]
```

**Comment by briansmith** [comment] 2021-02-26 19:15
@Ruijuan-Cao I inferred from the commit subject line that the problem was a missing `aesv8-armx-linux64.S` file. However, I suspect that the "No such file or directory" is actually caused by a missing compiler executable. Unfortunately, the error message in the build log doesn't distinguish between these two cases clearly. Please post the full error message that the build outputs.

**Comment by briansmith** [comment] 2021-02-26 19:17
@mhill-holoplot wrote:
> I have a similar issue with even after I ran a `cargo vendor`
>   process didn't exit successfully: `/home/morgan/workspace/vector/target/debug/build/ring-30f67b8446f8dcc8/build-script-build` (exit code: 101)
>   --- stdout
>   OPT_LEVEL = Some("0")
>   TARGET = Some("arm-unknown-linux-gnueabihf")

What happens when you run `which arm-linux-gnueabihf-gcc`?

Look at ring's `mk/install-build-tools.sh` and `mk/cargo.sh` to see one way to set up cross compiling, which is tested by this project every build.

**Comment by briansmith** [comment] 2021-02-26 19:18
@bdbai wrote:
> Same problem here when compiling for thumbv7a-uwp-windows-msvc

Please see issue #960. I'll follow up there.

**Comment by briansmith** [comment] 2021-02-26 19:25
FYI, I verified that *ring* 0.16.20 does include that file in its bundle. I also did successfully cross-compile Rustls using `cargo build --target=aarch64-linux-android` when `ANDROID_SDK_ROOT` was set correctly, Android NDK was installed, and the TARGET_CC, TARGET_AR, and linker were configured correctly as done by `mk/install-build-tools.sh --target=aarch64-linux-android` and `mk/cargo.sh --target=aarch64-linux-android`.

**Comment by mhill-holoplot** [comment] 2021-03-01 08:57
@briansmith 
> Look at ring's `mk/install-build-tools.sh` and `mk/cargo.sh` to see one way to set up cross compiling, which is tested by this project every build.

Yeah the looks like I'm missing 'arm-linux-gnueabihf-gcc' as I'm on fedora where the arm cross tool chain is only intended for kernel builds.

I guess building in a container is the easiest option for me.

**Comment by lee-emqx** [comment] 2021-05-13 04:23
Try this tool https://github.com/rust-embedded/cross

**Comment by briansmith** [comment] 2021-08-16 19:41
Closing this since I've verified that this works in multiple projects.

**Closed by briansmith** 2021-08-16 19:41 UTC
