### ISSUE TITLE
mips64el-unknown-linux-muslabi64  cross compile error on v0.16.20

### ISSUE THREAD

**Issue by RickSKy** [briansmith/ring#1585] opened 2023-02-08 10:19 UTC
```
error: failed to run custom build command for `ring v0.16.20`

Caused by:
  process didn't exit successfully: `/home/ub/target/release/build/ring-c17fa5ea40a1072c/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/test/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/build.rs:358:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by BryanKadzban** [comment] 2023-03-09 07:38
I'm seeing the same error when trying to cross-compile on an x86-64 machine, building for riscv32imc-unknown-none-elf.

It almost looks like the code is taking the target architecture and matching it to the list of host architectures?  Or maybe the list it's matching against isn't host architectures, but this crate doesn't have a native-rust version of all the crypto code, so it requires assembly for each target?

**Comment by briansmith** [comment] 2023-08-23 21:16
Closing as a duplicate of the existing mips64el issues/PRs. I expect the support to be added soon.

**Closed by briansmith** 2023-08-23 21:16 UTC
