### ISSUE TITLE
Support for mipsel-unknown-linux-gnu

### ISSUE THREAD

**Issue by detly** [briansmith/ring#1367] opened 2021-08-26 04:24 UTC
I am deploying code on the MT7628, which falls under the `mipsel-unknown-linux-gnu` which is a [Tier 2](https://doc.rust-lang.org/nightly/rustc/platform-support.html#tier-2-with-host-tools) target. I'd like to be able to use crates that depend on *ring* (eg. [*rumqtt*](https://github.com/bytebeamio/rumqtt/), many request libraries). Unfortunately it fails to compile for such a target with:

```text
error: failed to run custom build command for `ring v0.16.20`

Caused by:
  process didn't exit successfully: `/home/jason/Code/[redacted]/openwrt/build_dir/target-mipsel_24kc_musl/[redacted]/[redacted]/target/release/build/ring-5643028c8edad309/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/jason/Code/[redacted]/openwrt/build_dir/hostpkg/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/build.rs:358:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```

(I have not dug into this yet, see my comments below.)

I don't currently have the bandwidth to support this, but I might eventually, so I thought I'd open this issue so that (a) I can gauge interest (b) there's a focal point for development on it and (c) I can ask you about it.

Questions:

- If someone else were to bootstrap it (initial implementation and CI), would you be happy to support it going forward, or would you need someone to commit platform-specific support long-term? (Specifically, I could find time for this kind of initial work, but I don't want to promise perpetual support when I know i can't follow through .)
- Where would someone start to achieve this? What needs to be done?
- Would feature gating difficult-to-port features and having partial support be acceptable (if it's relevant)?

**Comment by briansmith** [comment] 2023-10-14 03:45
Closing as a duplicate of #562

**Closed by briansmith** 2023-10-14 03:45 UTC
Labels: duplicate
