### ISSUE TITLE
Failing to build on PPC64 Linux

### ISSUE THREAD

**Issue by SerpentChris** [briansmith/ring#906] opened 2019-10-15 07:02 UTC
This is the output when I clone this repo and try to build it:
```
christian@PowerMac-G5-Quad:~/ring$ CARGO_BUILD_PIPELINING=false RUST_BACKTRACE=full cargo build
    Updating crates.io index
   Compiling cc v1.0.45
   Compiling libc v0.2.62
   Compiling lazy_static v1.4.0
   Compiling untrusted v0.7.0
   Compiling ring v0.16.9 (/home/christian/ring)
error: failed to run custom build command for `ring v0.16.9 (/home/christian/ring)`

Caused by:
  process didn't exit successfully: `/home/christian/ring/target/debug/build/ring-dff8456277e9791c/build-script-build` (exit code: 101)
--- stdout
CARGO: /home/christian/cargo/target/release/cargo
CARGO_BUILD_PIPELINING: false
CARGO_CFG_DEBUG_ASSERTIONS: 
CARGO_CFG_PROC_MACRO: 
CARGO_CFG_TARGET_ARCH: powerpc64
CARGO_CFG_TARGET_ENDIAN: big
CARGO_CFG_TARGET_ENV: gnu
CARGO_CFG_TARGET_FAMILY: unix
CARGO_CFG_TARGET_OS: linux
CARGO_CFG_TARGET_POINTER_WIDTH: 64
CARGO_CFG_TARGET_VENDOR: unknown
CARGO_CFG_UNIX: 
CARGO_FEATURE_ALLOC: 1
CARGO_FEATURE_DEFAULT: 1
CARGO_FEATURE_DEV_URANDOM_FALLBACK: 1
CARGO_FEATURE_LAZY_STATIC: 1
CARGO_MAKEFLAGS: --jobserver-fds=3,5 -j --jobserver-auth=3,5 -j
CARGO_MANIFEST_DIR: /home/christian/ring
CARGO_MANIFEST_LINKS: ring-asm
CARGO_PKG_AUTHORS: Brian Smith <brian@briansmith.org>
CARGO_PKG_DESCRIPTION: Safe, fast, small crypto using Rust.
CARGO_PKG_HOMEPAGE: 
CARGO_PKG_NAME: ring
CARGO_PKG_REPOSITORY: https://github.com/briansmith/ring
CARGO_PKG_VERSION: 0.16.9
CARGO_PKG_VERSION_MAJOR: 0
CARGO_PKG_VERSION_MINOR: 16
CARGO_PKG_VERSION_PATCH: 9
CARGO_PKG_VERSION_PRE: 
COLORTERM: truecolor
DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
DEBUG: true
DESKTOP_SESSION: lightdm-xsession
DISPLAY: :0.0
GDMSESSION: lightdm-xsession
GPG_AGENT_INFO: /run/user/1000/gnupg/S.gpg-agent:0:1
GTK_MODULES: gail:atk-bridge
GTK_OVERLAY_SCROLLING: 0
HOME: /home/christian
HOST: powerpc64-unknown-linux-gnu
LANG: en_US.UTF-8
LD_LIBRARY_PATH: /home/christian/ring/target/debug/deps:/usr/lib
LOGNAME: christian
LS_COLORS: rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
MATE_DESKTOP_SESSION_ID: this-is-deprecated
NUM_JOBS: 4
OLDPWD: /home/christian
OPT_LEVEL: 0
OUT_DIR: /home/christian/ring/target/debug/build/ring-cf2575381cf19419/out
PATH: /usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/christian/.local/bin
PROFILE: debug
PWD: /home/christian/ring
QT_ACCESSIBILITY: 1
QT_AUTO_SCREEN_SCALE_FACTOR: 0
QT_SCALE_FACTOR: 1
RUSTC: rustc
RUSTDOC: rustdoc
RUST_BACKTRACE: full
SESSION_MANAGER: local/PowerMac-G5-Quad:@/tmp/.ICE-unix/1429,unix/PowerMac-G5-Quad:/tmp/.ICE-unix/1429
SHELL: /bin/bash
SHLVL: 1
SSH_AGENT_PID: 1456
SSH_AUTH_SOCK: /run/user/1000/keyring/ssh
SSL_CERT_DIR: /usr/lib/ssl/certs
SSL_CERT_FILE: /usr/lib/ssl/certs/ca-certificates.crt
TARGET: powerpc64-unknown-linux-gnu
TERM: xterm-256color
USER: christian
VTE_VERSION: 5802
WINDOWID: 56630396
XAUTHORITY: /home/christian/.Xauthority
XDG_CURRENT_DESKTOP: MATE
XDG_DATA_DIRS: /usr/share/mate:/usr/local/share/:/usr/share/
XDG_GREETER_DATA_DIR: /var/lib/lightdm/data/christian
XDG_RUNTIME_DIR: /run/user/1000
XDG_SEAT: seat0
XDG_SEAT_PATH: /org/freedesktop/DisplayManager/Seat0
XDG_SESSION_CLASS: user
XDG_SESSION_DESKTOP: lightdm-xsession
XDG_SESSION_ID: 5
XDG_SESSION_PATH: /org/freedesktop/DisplayManager/Session1
XDG_SESSION_TYPE: x11
XDG_VTNR: 7
_: /home/christian/cargo/target/release/cargo

--- stderr
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:347:21
stack backtrace:
   0:        0x1266374a0 - std::sys_common::backtrace::print::h1cfdcdfd50dc99d5
   1:        0x12663e7f4 - std::panicking::default_hook::{{closure}}::hb02ee15e0f4148aa
   2:        0x12663e498 - std::panicking::default_hook::ha4e81d5d1849f7c8
   3:        0x12663f23c - std::panicking::rust_panic_with_hook::h1596eb28f47e2c61
   4:        0x12663ec58 - std::panicking::continue_panic_fmt::he7cb0ecf712c7fce
   5:        0x12663eaf0 - rust_begin_unwind
   6:        0x12665a1a8 - core::panicking::panic_fmt::hc2983adf885c9fdd
   7:        0x12665a0cc - core::panicking::panic::h1b7f621625a92ee1
   8:        0x12659ce6c - core::option::Option<T>::unwrap::hcd728104f2bffe3c
                               at /usr/src/rustc-1.37.0/src/libcore/macros.rs:12
   9:        0x1265a8cf8 - build_script_build::build_c_code::hed5740b45cc2f884
                               at /home/christian/ring/build.rs:364
  10:        0x1265a80e8 - build_script_build::ring_build_rs_main::hdafc78af7f04975b
                               at /home/christian/ring/build.rs:296
  11:        0x1265a78e4 - build_script_build::main::h383b02e79673aa26
                               at /home/christian/ring/build.rs:253
  12:        0x12659ac74 - std::rt::lang_start::{{closure}}::h06a969888303a0a4
                               at /usr/src/rustc-1.37.0/src/libstd/rt.rs:64
  13:        0x1266375d0 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf4026783dc0180ec
  14:        0x12663ea34 - std::panicking::try::do_call::hdfa0a4b296f8c82f
  15:        0x126645be8 - __rust_maybe_catch_panic
  16:        0x1266434f4 - std::rt::lang_start_internal::h9a26ecfe7dd3d0e0
  17:        0x12659ac14 - std::rt::lang_start::h25e3538f88a99908
                               at /usr/src/rustc-1.37.0/src/libstd/rt.rs:64
  18:        0x1265ac5f8 - main
  19:     0x7fffbdb9cbb0 - <unknown>
  20:     0x7fffbdb9cdc4 - __libc_start_main
  21:                0x0 - <unknown>

```

**Comment by andrewtj** [comment] 2019-10-15 08:30
#389 tracks PowerPC support

**Comment by runlevel5** [comment] 2020-04-02 22:27
I could also confirm the same issue on the LE variant (ppc64le)

**Comment by briansmith** [comment] 2020-04-29 20:56
Closing this as a dupe of #389. Thanks for reporting

**Closed by briansmith** 2020-04-29 20:56 UTC
