### ISSUE TITLE
x86_64-fortanix-unknown-sgx only built on nightly

### ISSUE THREAD

**Issue by jethrogb** [briansmith/ring#779] opened 2019-01-30 12:56 UTC
Since the `x86_64-fortanix-unknown-sgx` target is only available on nightly, *ring* CI only builds for that target on nightly.

If https://github.com/rust-lang/rust/pull/57659 is accepted, the target will land in beta, which will make it available on stable at 1.33.0. If it is not accepted, it will land in stable at 1.34.0.

**Comment by briansmith** [comment] 2023-10-31 00:27
Closing as a duplicate of #779.

**Closed by briansmith** 2023-10-31 00:27 UTC
Labels: duplicate
