### ISSUE TITLE
ring-0.16.20 compile error 

### ISSUE THREAD

**Issue by ArunGust** [briansmith/ring#1471] opened 2022-03-26 05:19 UTC
I got below error.(env:  rustc 1.61.0-nightly (d53246fed 2022-03-25))

registry\src\github.com-1ecc6299db9ec823\ring-0.16.20\src\cpu.rs:257:13
    |
165 |     macro_rules! features {
    |     --------------------- when calling this macro
...
257 |             aarch64_apple: true,
    |             ^^^^^^^^^^^^^ no rules expected this token in macro call

   Compiling h2 v0.1.26
error[E0425]: cannot find value `AES` in module `cpu::arm`
   --> registry\src\github.com-1ecc6299db9ec823\ring-0.16.20\src\aead\aes.rs:381:65
    |
381 |         if cpu::intel::AES.available(cpu_features) || cpu::arm::AES.available(cpu_features) {
    |                                                                 ^^^ not found in `cpu::arm`
    |
help: consider importing this constant
    |
15  | use crate::cpu::intel::AES;
    |

error[E0425]: cannot find value `PMULL` in module `cpu::arm`
   --> registry\src\github.com-1ecc6299db9ec823\ring-0.16.20\src\aead\gcm.rs:315:26
    |
315 |             || cpu::arm::PMULL.available(cpu_features)
    |                          ^^^^^ not found in `cpu::arm`

error[E0425]: cannot find value `ARMCAP_STATIC` in this scope
   --> \registry\src\github.com-1ecc6299db9ec823\ring-0.16.20\src\cpu.rs:235:41
    |
235 |             if self.mask == self.mask & ARMCAP_STATIC {
    |                                         ^^^^^^^^^^^^^ not found in this scope

   Compiling flate2 v0.2.20
For more information about this error, try `rustc --explain E0425`.
error: could not compile `ring` due to 4 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by Liu-WeiHu** [comment] 2022-03-26 10:39
I have the same problem

**Comment by spa5k** [comment] 2022-03-26 13:42
Same problem

**Comment by Antiarchitect** [comment] 2022-03-27 01:58
Same

**Comment by Jerrody** [comment] 2022-03-27 06:13
Yep, the same problem.

**Comment by Samuel-B-D** [comment] 2022-03-28 00:16
Same here. Seems broken on nightly 1.61.0-nightly; it worked for me on 1.60.0-nightly this morning.

**Comment by ArunGust** [comment] 2022-03-28 04:27
> Same here. Seems broken on nightly 1.61.0-nightly; it worked for me on 1.60.0-nightly this morning.

thanks, will test

**Comment by kekeimiku** [comment] 2022-03-28 05:13
Same problem.

**Comment by HTG-YT** [comment] 2022-03-28 06:06
I just encountered this issue today with this workflow: https://github.com/HarTexTeam/HarTex-rust-discord-bot/runs/5715118385?check_suite_focus=true

**Comment by HTG-YT** [comment] 2022-03-28 06:08
See also issue on upstream Rust: https://github.com/rust-lang/rust/issues/95267

**Comment by briansmith** [comment] 2022-03-28 22:30
Thanks for the report. This is a duplicate of #1469, so closing in favor of that issue, which notes in its description that this is an issue specifically about building with Nightly Rust.

**Closed by briansmith** 2022-03-28 22:30 UTC
