### ISSUE TITLE
Got "requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC" error on android armv7

### ISSUE THREAD

**Issue by bachue** [briansmith/ring#1110] opened 2020-11-19 05:15 UTC
I got this error when try to compile [quiche](https://github.com/cloudflare/quiche)(which requires ring) for android armv7, the ring version is v0.16.16

```
error: linking with `/tmp/android-ndk-r20b/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang` failed: exit code: 1
  |
  = note: "/tmp/android-ndk-r20b/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-Wl,--allow-multiple-definition" "-march=armv7-a" "-Wl,--eh-frame-hdr" "-L" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-linux-androideabi/lib" "/root/Build-cURL-nghttp2-quiche-android/quiche/quiche/target/armv7-linux-androideabi/release/deps/quiche.quiche.616kf1ay-cgu.0.rcgu.o" "/root/Build-cURL-nghttp2-quiche-android/quiche/quiche/target/armv7-linux-androideabi/release/deps/quiche.quiche.616kf1ay-cgu.1.rcgu.o" "/root/Build-cURL-nghttp2-quiche-android/quiche/quiche/target/armv7-linux-androideabi/release/deps/quiche.quiche.616kf1ay-cgu.10.rcgu.o" "/root/Build-cURL-nghttp2-quiche-android/quiche/quiche/target/armv7-linux-androideabi/release/deps/quiche.quiche.616kf1ay-cgu.11.rcgu.o" "/root/Build-cURL-nghttp2-quiche-android/quiche/quiche/target/armv7-linux-androideabi/release/deps/quiche.quiche.616kf1ay-cgu.12.rcgu.o" "/root/Build-cURL-nghttp2-quiche-android/quiche/quiche/target/armv7-linux-androideabi/release/deps/quiche.quiche.616kf1ay-cgu.13.rcgu.o" "/root/Build-cURL-nghttp2-quiche-android/quiche/quiche/target/armv7-linux-androideabi/release/deps/quiche.quiche.616kf1ay-cgu.14.rcgu.o" "/root/Build-cURL-nghttp2-quiche-android/quiche/quiche/target/armv7-linux-androideabi/release/deps/quiche.quiche.616kf1ay-cgu.15.rcgu.o" "/root/Build-cURL-nghttp2-quiche-android/quiche/quiche/target/armv7-linux-androideabi/release/deps/quiche.quiche.616kf1ay-cgu.2.rcgu.o" "/root/Build-cURL-nghttp2-quiche-android/quiche/quiche/target/armv7-linux-androideabi/release/deps/quiche.quiche.616kf1ay-cgu.3.rcgu.o" "/root/Build-cURL-nghttp2-quiche-android/quiche/quiche/target/armv7-linux-androideabi/release/deps/quiche.quiche.616kf1ay-cgu.4.rcgu.o" "/root/Build-cURL-nghttp2-quiche-android/quiche/quiche/target/armv7-linux-androideabi/release/deps/quiche.quiche.616kf1ay-cgu.5.rcgu.o" "/root/Build-cURL-nghttp2-quiche-android/quiche/quiche/target/armv7-linux-androideabi/release/deps/quiche.quiche.616kf1ay-cgu.6.rcgu.o" "/root/Build-cURL-nghttp2-quiche-android/quiche/quiche/target/armv7-linux-androideabi/release/deps/quiche.quiche.616kf1ay-cgu.7.rcgu.o" "/root/Build-cURL-nghttp2-quiche-android/quiche/quiche/target/armv7-linux-androideabi/release/deps/quiche.quiche.616kf1ay-cgu.8.rcgu.o" "/root/Build-cURL-nghttp2-quiche-android/quiche/quiche/target/armv7-linux-androideabi/release/deps/quiche.quiche.616kf1ay-cgu.9.rcgu.o" "-o" "/root/Build-cURL-nghttp2-quiche-android/quiche/quiche/target/armv7-linux-androideabi/release/deps/libquiche.so" "-Wl,--version-script=/tmp/rustcdxE5Qm/list" "/root/Build-cURL-nghttp2-quiche-android/quiche/quiche/target/armv7-linux-androideabi/release/deps/quiche.1arz1cl9x55dxxaj.rcgu.o" "-Wl,--gc-sections" "-shared" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/root/Build-cURL-nghttp2-quiche-android/quiche/quiche/target/armv7-linux-androideabi/release/deps" "-L" "/root/Build-cURL-nghttp2-quiche-android/quiche/quiche/target/release/deps" "-L" "/root/Build-cURL-nghttp2-quiche-android/quiche/quiche/target/armv7-linux-androideabi/release/build/quiche-cffe245ef3e61833/out/build/" "-L" "/root/Build-cURL-nghttp2-quiche-android/quiche/quiche/target/armv7-linux-androideabi/release/build/ring-2148c99d7c7709ff/out" "-L" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-linux-androideabi/lib" "-Wl,-Bstatic" "-Wl,--whole-archive" "-lcrypto" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "-lssl" "-Wl,--no-whole-archive" "/root/Build-cURL-nghttp2-quiche-android/quiche/quiche/target/armv7-linux-androideabi/release/deps/liblibm-ba7d965c063288e3.rlib" "/root/Build-cURL-nghttp2-quiche-android/quiche/quiche/target/armv7-linux-androideabi/release/deps/libqlog-1ccefaca94ba9922.rlib" "/root/Build-cURL-nghttp2-quiche-android/quiche/quiche/target/armv7-linux-androideabi/release/deps/libserde_json-3526088bbc0fd83f.rlib" "/root/Build-cURL-nghttp2-quiche-android/quiche/quiche/target/armv7-linux-androideabi/release/deps/libryu-650838155cf5ae72.rlib" "/root/Build-cURL-nghttp2-quiche-android/quiche/quiche/target/armv7-linux-androideabi/release/deps/libitoa-f2c2f5abecce85ef.rlib" "/root/Build-cURL-nghttp2-quiche-android/quiche/quiche/target/armv7-linux-androideabi/release/deps/libserde_with-ac96b1f6d07381fe.rlib" "/root/Build-cURL-nghttp2-quiche-android/quiche/quiche/target/armv7-linux-androideabi/release/deps/libserde-2fe5635aae208330.rlib" "/root/Build-cURL-nghttp2-quiche-android/quiche/quiche/target/armv7-linux-androideabi/release/deps/liblazy_static-c2f7362ae4c6d87b.rlib" "/root/Build-cURL-nghttp2-quiche-android/quiche/quiche/target/armv7-linux-androideabi/release/deps/libring-49986a660d8f2351.rlib" "/root/Build-cURL-nghttp2-quiche-android/quiche/quiche/target/armv7-linux-androideabi/release/deps/libspin-216b8e102d8d0166.rlib" "/root/Build-cURL-nghttp2-quiche-android/quiche/quiche/target/armv7-linux-androideabi/release/deps/libuntrusted-7bb202ee0c5c54d7.rlib" "/root/Build-cURL-nghttp2-quiche-android/quiche/quiche/target/armv7-linux-androideabi/release/deps/libonce_cell-55da8117e1309126.rlib" "/root/Build-cURL-nghttp2-quiche-android/quiche/quiche/target/armv7-linux-androideabi/release/deps/liblibc-4b203f683787ba82.rlib" "/root/Build-cURL-nghttp2-quiche-android/quiche/quiche/target/armv7-linux-androideabi/release/deps/liblog-554c0b6d6266c31e.rlib" "/root/Build-cURL-nghttp2-quiche-android/quiche/quiche/target/armv7-linux-androideabi/release/deps/libcfg_if-8d4059eec5da8f00.rlib" "-Wl,--start-group" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-linux-androideabi/lib/libstd-ffe1a9c82e8d0a37.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-linux-androideabi/lib/libpanic_unwind-b61988b77188c509.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-linux-androideabi/lib/libminiz_oxide-76d7decce4314924.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-linux-androideabi/lib/libadler-a9b5c759ff5f3e5d.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-linux-androideabi/lib/libobject-0f6fa2a52d18133c.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-linux-androideabi/lib/libaddr2line-d180190ac46df7a8.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-linux-androideabi/lib/libgimli-ae3a96c61c235370.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-linux-androideabi/lib/librustc_demangle-4722f4b30a8f0e62.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-linux-androideabi/lib/libhashbrown-30409a3091b641e2.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-linux-androideabi/lib/librustc_std_workspace_alloc-798c8a258c7ab78f.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-linux-androideabi/lib/libunwind-25082c63e78556bb.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-linux-androideabi/lib/libcfg_if-d50746acbc55f58a.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-linux-androideabi/lib/liblibc-855a8e0617c7b54b.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-linux-androideabi/lib/liballoc-57b276aed8dc9153.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-linux-androideabi/lib/librustc_std_workspace_core-e6c8d358effa5150.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-linux-androideabi/lib/libcore-dda962065ef151e7.rlib" "-Wl,--end-group" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-linux-androideabi/lib/libcompiler_builtins-33461f6f25fbfeb0.rlib" "-Wl,-Bdynamic" "-ldl" "-llog" "-lgcc" "-lc" "-lm"
  = note: /tmp/android-ndk-r20b/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /root/Build-cURL-nghttp2-quiche-android/quiche/quiche/target/armv7-linux-androideabi/release/deps/libring-49986a660d8f2351.rlib(chacha-armv4-linux32.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
          /tmp/android-ndk-r20b/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /root/Build-cURL-nghttp2-quiche-android/quiche/quiche/target/armv7-linux-androideabi/release/deps/libring-49986a660d8f2351.rlib(sha256-armv4-linux32.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
          /tmp/android-ndk-r20b/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /root/Build-cURL-nghttp2-quiche-android/quiche/quiche/target/armv7-linux-androideabi/release/deps/libring-49986a660d8f2351.rlib(sha512-armv4-linux32.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by briansmith** [comment] 2020-11-19 08:40
Thanks for the report. #1109 is my WIP fix. Closing this as a duplicate of #1106.

**Closed** 2020-11-19 19:06 UTC

**Comment by briansmith** [comment] 2020-11-26 19:43
PR #1127, in 0.16.18 that I just released, fixes another case, for ARMv8:
```
 ld.lld: error: relocation R_AARCH64_ADR_PREL_PG_HI21 cannot be used against symbol GFp_armcap_P
; recompile with -fPIC
chacha-armv8-linux64.o:(GFp_ChaCha20_ctr32) in archive libring-core/android_arm64_armv8-a_static/libring-core.a
```

I double-checked the remaining code and this should be the last one.
