### ISSUE TITLE
I can't compile

### ISSUE THREAD

**Issue by crocwolf** [briansmith/ring#780] opened 2019-01-30 21:54 UTC
failed to run custom build command for `ring v0.14.3`
process didn't exit successfully: `/home/user/Bureau/streaming/target/debug/build/ring-9626c0d8b2787aba/build-script-build` (exit code: 101)
--- stdout
CARGO: /home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo
CARGO_CFG_DEBUG_ASSERTIONS: 
CARGO_CFG_PROC_MACRO: 
CARGO_CFG_TARGET_ARCH: wasm32
CARGO_CFG_TARGET_ENDIAN: little
CARGO_CFG_TARGET_ENV: 
CARGO_CFG_TARGET_HAS_ATOMIC: 16,32,64,8,cas,ptr
CARGO_CFG_TARGET_OS: unknown
CARGO_CFG_TARGET_POINTER_WIDTH: 32
CARGO_CFG_TARGET_VENDOR: unknown
CARGO_FEATURE_DEFAULT: 1
CARGO_FEATURE_DEV_URANDOM_FALLBACK: 1
CARGO_FEATURE_USE_HEAP: 1
CARGO_HOME: /home/user/.cargo
CARGO_MAKEFLAGS: --jobserver-fds=5,14 -j --jobserver-auth=5,14 -j
CARGO_MANIFEST_DIR: /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.3
CARGO_MANIFEST_LINKS: ring-asm
CARGO_PKG_AUTHORS: Brian Smith <brian@briansmith.org>
CARGO_PKG_DESCRIPTION: Safe, fast, small crypto using Rust.
CARGO_PKG_HOMEPAGE: 
CARGO_PKG_NAME: ring
CARGO_PKG_REPOSITORY: https://github.com/briansmith/ring
CARGO_PKG_VERSION: 0.14.3
CARGO_PKG_VERSION_MAJOR: 0
CARGO_PKG_VERSION_MINOR: 14
CARGO_PKG_VERSION_PATCH: 3
CARGO_PKG_VERSION_PRE: 
CARGO_WEB_TARGET: wasm32-unknown-unknown
CARGO_WEB_TARGET_DIR: /home/user/Bureau/streaming/target
CLUTTER_IM_MODULE: xim
COMPILING_UNDER_CARGO_WEB: 1
COMPIZ_CONFIG_PROFILE: ubuntu
DBUS_SESSION_BUS_ADDRESS: unix:abstract=/tmp/dbus-BZbw0a3HxZ
DEBUG: true
DEFAULTS_PATH: /usr/share/gconf/ubuntu.default.path
DESKTOP_SESSION: ubuntu
DISPLAY: :0
GDMSESSION: ubuntu
GDM_LANG: fr_FR
GNOME_DESKTOP_SESSION_ID: this-is-deprecated
GNOME_KEYRING_CONTROL: 
GNOME_KEYRING_PID: 
GPG_AGENT_INFO: /home/user/.gnupg/S.gpg-agent:0:1
GTK2_MODULES: overlay-scrollbar
GTK_IM_MODULE: ibus
GTK_MODULES: gail:atk-bridge:unity-gtk-module
HOME: /home/user
HOST: x86_64-unknown-linux-gnu
IM_CONFIG_PHASE: 1
INSTANCE: Unity
JOB: gnome-session
LANG: fr_FR.UTF-8
LANGUAGE: fr_FR
LD_LIBRARY_PATH: /home/user/Bureau/streaming/target/debug/deps:/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib:/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib:/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib
LESSCLOSE: /usr/bin/lesspipe %s %s
LESSOPEN: | /usr/bin/lesspipe %s
LOGNAME: m
LS_COLORS: rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
MANDATORY_PATH: /usr/share/gconf/ubuntu.mandatory.path
NUM_JOBS: 8
OLDPWD: /home/user
OPT_LEVEL: 0
OUT_DIR: /home/user/Bureau/streaming/target/wasm32-unknown-unknown/debug/build/ring-609fd7f173f289e7/out
PATH: /home/user/.cargo/bin:/home/user/.cargo/bin:/home/user/.cargo/bin:/home/user/bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
PROFILE: debug
PWD: /home/user/Bureau/streaming
QT4_IM_MODULE: xim
QT_ACCESSIBILITY: 1
QT_IM_MODULE: ibus
QT_LINUX_ACCESSIBILITY_ALWAYS_ON: 1
QT_QPA_PLATFORMTHEME: appmenu-qt5
RUSTC: rustc
RUSTDOC: rustdoc
RUSTFLAGS: 
RUSTUP_HOME: /home/user/.rustup
RUSTUP_TOOLCHAIN: nightly-x86_64-unknown-linux-gnu
RUST_RECURSION_COUNT: 2
SESSIONTYPE: gnome-session
SHELL: /bin/bash
SHLVL: 1
SSH_AUTH_SOCK: /run/user/1000/keyring/ssh
SSL_CERT_DIR: /usr/lib/ssl/certs
SSL_CERT_FILE: /usr/lib/ssl/certs/ca-certificates.crt
TARGET: wasm32-unknown-unknown
TERM: xterm-256color
UPSTART_EVENTS: started starting
UPSTART_INSTANCE: 
UPSTART_JOB: unity-settings-daemon
UPSTART_SESSION: unix:abstract=/com/ubuntu/upstart-session/1000/1703
USER: m
VTE_VERSION: 4205
WINDOWID: 58720266
XAUTHORITY: /home/user/.Xauthority
XDG_CONFIG_DIRS: /etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg
XDG_CURRENT_DESKTOP: Unity
XDG_DATA_DIRS: /usr/share/ubuntu:/usr/share/gnome:/usr/local/share:/usr/share:/var/lib/snapd/desktop:/var/lib/snapd/desktop
XDG_GREETER_DATA_DIR: /var/lib/lightdm-data/m
XDG_RUNTIME_DIR: /run/user/1000
XDG_SEAT: seat0
XDG_SEAT_PATH: /org/freedesktop/DisplayManager/Seat0
XDG_SESSION_DESKTOP: ubuntu
XDG_SESSION_ID: c2
XDG_SESSION_PATH: /org/freedesktop/DisplayManager/Session0
XDG_SESSION_TYPE: x11
XDG_VTNR: 7
XMODIFIERS: @im=ibus
_: /home/user/.cargo/bin/cargo

--- stderr
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:355:21
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by briansmith** [comment] 2019-01-31 00:53
Thanks for the report. This is a duplicate of #657.

**Closed by briansmith** 2019-01-31 00:53 UTC
