### ISSUE TITLE
Build fails on i386: evaluation of constant value failed

### ISSUE THREAD

**Issue by yurivict** [briansmith/ring#2006] opened 2024-03-28 17:39 UTC
```
error[E0080]: evaluation of constant value failed
  --> /wrkdirs/usr/ports/devel/ruff/work/ruff-0.3.3/cargo-crates/ring-0.17.8/src/cpu/intel.rs:28:9
   |
28 |         assert!(cfg!(target_feature = "sse") && cfg!(target_feature = "sse2"));
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the evaluated program panicked at 'assertion failed: cfg!(target_feature = "sse") && cfg!(target_feature = "sse2")', /wrkdirs/usr/ports/devel/ruff/work/ruff-0.3.3/cargo-crates/ring-0.17.8/src/cpu/intel.rs:28:9
   |
   = note: this error originates in the macro `assert` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0080`.
error: could not compile `ring` (lib) due to 1 previous error
```

[log](https://pkg-status.freebsd.org/beefy15/data/132i386-default/9ee7b88dab05/logs/ruff-0.3.3_1.log)

**Comment by briansmith** [comment] 2024-05-06 23:57
Closing as a duplicate of issue #1999.

**Closed by briansmith** 2024-05-06 23:57 UTC
Labels: duplicate
