### ISSUE TITLE
Any tags for version published as crate (0.17.5)

### ISSUE THREAD

**Issue by SebastianSchildt** [briansmith/ring#1820] opened 2023-11-24 11:09 UTC
Hi, 

is there any tag or branch here, that corresponds to the source pushed as https://crates.io/crates/ring/0.17.5 ? I searched but I did not find it/was not obvious to me. 

See also https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/11393

**Comment by SebastianSchildt** [comment] 2023-11-28 10:15
Thank you, the issue I have is, we need to scan/clear the code for license compliance, as we are an Eclipse Foundation project, and license compliance is important to Eclipse. The archive downloaded with cargo-download contains some pre-generated object files in folder pregenerated, and it is not always obvious which file was generated from which asm source, having a reference to the _source_ including the generators might fix that, but I poked in the archive form cargo download, and it is not immediately obvious with GIT hash it is based on

**Comment by briansmith** [comment] 2023-11-28 16:39
Hi, this is a duplicate of #1460. If you want to study how the crates.io releaes are made, check out the `package` job in CI. Recently, it is easy to find the code that corresponds to each release because the commit message is the version number; `git log --grep "0\\.17\\.*"`.

**Closed by briansmith** 2023-11-28 16:39 UTC
Labels: duplicate

**Comment by briansmith** [comment] 2023-11-28 17:07
I left some more comments in #1460.
