### ISSUE TITLE
Fails to cross-compile for aarch64-linux-android

### ISSUE THREAD

**Issue by ralfbiedert** [briansmith/ring#1050] opened 2020-09-01 18:31 UTC
When I run 

```
cargo build --target aarch64-linux-android --release -p my_project
```

I get:

```
   Compiling ring v0.16.15
   Compiling proc-macro-nested v0.1.6
   Compiling httparse v1.3.4
   Compiling idna v0.2.0
   Compiling bitflags v1.2.1
   Compiling encoding_rs v0.8.23
   Compiling generic-array v0.14.4
   Compiling num-traits v0.2.12
   Compiling net2 v0.2.34
   Compiling crossbeam-utils v0.7.2
   Compiling iovec v0.1.4
   Compiling memoffset v0.5.5
   Compiling getrandom v0.1.14
   Compiling hashbrown v0.8.2
   Compiling num_cpus v1.13.0
error: failed to run custom build command for `ring v0.16.15`

Caused by:
  process didn't exit successfully: `[REDACTED]\target\release\build\ring-56ea584bcbef6faa\build-script-build` (exit code: 101)
  --- stdout
  OPT_LEVEL = Some("3")
  TARGET = Some("aarch64-linux-android")
  HOST = Some("x86_64-pc-windows-msvc")
  CC_aarch64-linux-android = None
  CC_aarch64_linux_android = None
  TARGET_CC = None
  CC = None
  CFLAGS_aarch64-linux-android = None
  CFLAGS_aarch64_linux_android = None
  TARGET_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")

  --- stderr

  [SOME SETTINGS HAVE BEEN REDACTED]

  ENV =::=::\
  ENV ALLUSERSPROFILE=C:\ProgramData
  ENV APPDATA=C:\Users\rb\AppData\Roaming
  ENV BASH=C:/Program Files/Git/usr/bin/bash
  ENV CARGO=\\?\C:\Users\rb\.rustup\toolchains\stable-x86_64-pc-windows-msvc\bin\cargo.exe
  ENV CARGO_CFG_TARGET_ARCH=aarch64
  ENV CARGO_CFG_TARGET_ENDIAN=little
  ENV CARGO_CFG_TARGET_ENV=
  ENV CARGO_CFG_TARGET_FAMILY=unix
  ENV CARGO_CFG_TARGET_OS=android
  ENV CARGO_CFG_TARGET_POINTER_WIDTH=64
  ENV CARGO_CFG_TARGET_VENDOR=unknown
  ENV CARGO_CFG_UNIX=
  ENV CARGO_FEATURE_ALLOC=1
  ENV CARGO_FEATURE_DEFAULT=1
  ENV CARGO_FEATURE_DEV_URANDOM_FALLBACK=1
  ENV CARGO_FEATURE_ONCE_CELL=1
  ENV CARGO_HOME=C:\Users\rb\.cargo
  ENV CARGO_MAKEFLAGS=--jobserver-fds=__rust_jobserver_semaphore_3494836018 --jobserver-auth=__rust_jobserver_semaphore_3494836018
  ENV CARGO_MANIFEST_DIR=C:\Users\rb\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.16.15
  ENV CARGO_MANIFEST_LINKS=ring-asm
  ENV CARGO_PKG_AUTHORS=Brian Smith <brian@briansmith.org>
  ENV CARGO_PKG_DESCRIPTION=Safe, fast, small crypto using Rust.
  ENV CARGO_PKG_HOMEPAGE=
  ENV CARGO_PKG_LICENSE=
  ENV CARGO_PKG_LICENSE_FILE=LICENSE
  ENV CARGO_PKG_NAME=ring
  ENV CARGO_PKG_REPOSITORY=https://github.com/briansmith/ring
  ENV CARGO_PKG_VERSION=0.16.15
  ENV CARGO_PKG_VERSION_MAJOR=0
  ENV CARGO_PKG_VERSION_MINOR=16
  ENV CARGO_PKG_VERSION_PATCH=15
  ENV CARGO_PKG_VERSION_PRE=
  ENV CC_AARCH64_ANDROID=C:\Users\rb\.ndk\android-ndk-r21d\toolchains\llvm\prebuilt\windows-x86_64\bin\aarch64-linux-android21-clang.cmd
  ENV HOST=x86_64-pc-windows-msvc
  ENV LD_LIBRARY_PATH=C:\Users\rb\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib
  ENV MSYSTEM=MINGW64
  ENV NUMBER_OF_PROCESSORS=16
  ENV NUM_JOBS=16
  ENV OPT_LEVEL=3
  ENV OS=Windows_NT
  ENV OUT_DIR=[REDACTED]\target\aarch64-linux-android\release\build\ring-21b73a0de35ea3e7\out
  ENV PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
  ENV POWERSHELL=1
  ENV PROCESSOR_ARCHITECTURE=AMD64
  ENV PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 158 Stepping 12, GenuineIntel
  ENV PROCESSOR_LEVEL=6
  ENV PROCESSOR_REVISION=9e0c
  ENV PROFILE=release
  ENV PROGRAMDATA=C:\ProgramData
  ENV PROGRAMFILES=C:\Program Files
  ENV PROGRAMFILES(X86)=C:\Program Files (x86)
  ENV PROGRAMW6432=C:\Program Files
  ENV PROMPT=$P$G
  ENV RUSTC=rustc
  ENV RUSTC_LINKER=C:/Users/rb/.ndk/android-ndk-r21d/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android21-clang.cmd
  ENV RUSTDOC=rustdoc
  ENV RUSTUP_HOME=C:\Users\rb\.rustup
  ENV RUSTUP_TOOLCHAIN=stable-x86_64-pc-windows-msvc
  ENV RUST_RECURSION_COUNT=1
  ENV TARGET=aarch64-linux-android
  ENV TEMP=C:\Users\rb\AppData\Local\Temp
  ENV TERM=cygwin
  ENV TMP=C:\Users\rb\AppData\Local\Temp
  ENV UNITY201930=C:\Program Files\Unity\Hub\Editor\2019.3.5f1
  ENV UNITY201940=C:\Program Files\Unity\Hub\Editor\2019.4.0f1
  ENV WINDIR=C:\Windows
  ENV _=C:/Users/rb/.cargo/bin/cargo
  running "aarch64-linux-android-clang" "-O3" "-DANDROID" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=aarch64-linux-android" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-DNDEBUG" "-c" "-o[REDACTED]\\target\\aarch64-linux-android\\release\\build\\ring-21b73a0de35ea3e7\\out\\aesv8-armx-linux64.o" "C:\\Users\\rb\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\ring-0.16.15\\pregenerated\\aesv8-armx-linux64.S"
  thread 'main' panicked at 'failed to execute ["aarch64-linux-android-clang" "-O3" "-DANDROID" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=aarch64-linux-android" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-DNDEBUG" "-c" "-o[REDACTED]\\target\\aarch64-linux-android\\release\\build\\ring-21b73a0de35ea3e7\\out\\aesv8-armx-linux64.o" "C:\\Users\\rb\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\ring-0.16.15\\pregenerated\\aesv8-armx-linux64.S"]: The system cannot find the file specified. (os error 2)', C:\Users\rb\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.16.15\build.rs:661:9
```

Using,  `rustc 1.46.0 (04488afe3 2020-08-24)`,

**Comment by Darkspirit** [comment] 2020-09-03 13:07
I've seen such errors here and it successfully compiled at the end: https://github.com/seanmonstar/reqwest/issues/1014#issuecomment-678776743

https://github.com/briansmith/ring/blob/98e25317b3a3dd9a71c07255f5c84e9a2ecef0be/BUILDING.md#cross-compiling

> When you build ring for a target that is different than the one you are using for the build process you need to install the rust tool chain and a C/C++ compiler that can produce binaries for the intended target.
> Besides the required dependencies you need to set the environment variables TARGET_CC and TARGET_AR to the full path of the cross-compiler and the cross-archiver respectively.

You need to find the correct path within the NDK, it's something like this:
```
$ export TARGET_AR=/path/to/.NDK/arm64/bin/aarch64-linux-android-ar
$ export TARGET_CC=/path/to/.NDK/arm64/bin/aarch64-linux-android-clang
$ cargo build --target aarch64-linux-android --release
```

The first comment mentions this, just search a bit around:
>   ENV CC_AARCH64_ANDROID=C:\Users\rb\.ndk\android-ndk-r21d\toolchains\llvm\prebuilt\windows-x86_64\bin\aarch64-linux-android21-clang.cmd

**Comment by little-dude** [comment] 2020-09-04 07:36
Thanks a lot @Darkspirit that helped. I am settings these:

```
export TARGET_CC=/nix/store/5p5zlzc7h33ab44vw6qf91c02zffz1da-ndk-bundle-18.1.5063045/libexec/android-sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc               
export TARGET_AR=/nix/store/5p5zlzc7h33ab44vw6qf91c02zffz1da-ndk-bundle-18.1.5063045/libexec/android-sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-ar
export CC_AARCH64_LINUX_ANDROID=$TARGET_CC
export AR_AARCH64_LINUX_ANDROID=$TARGET_AR
export CARGO_TARGET_AR_AARCH64_LINUX_ANDROID_LINKER=$TARGET_CC
export CARGO_TARGET_AR_AARCH64_LINUX_ANDROID_AR=$TARGET_AR
```

However now I'm running into:

```
  running "/nix/store/5p5zlzc7h33ab44vw6qf91c02zffz1da-ndk-bundle-18.1.5063045/libexec/android-sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-DNDEBUG" "-c" "-o/home/little-dude/code/cross-compile-reqwest/target/aarch64-linux-android/debug/build/ring-4c09cef695fad7d8/out/aesv8-armx-linux64.o" "/home/little-dude/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.15/pregenerated/aesv8-armx-linux64.S"
  running "/nix/store/5p5zlzc7h33ab44vw6qf91c02zffz1da-ndk-bundle-18.1.5063045/libexec/android-sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-DNDEBUG" "-c" "-o/home/little-dude/code/cross-compile-reqwest/target/aarch64-linux-android/debug/build/ring-4c09cef695fad7d8/out/ghashv8-armx-linux64.o" "/home/little-dude/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.15/pregenerated/ghashv8-armx-linux64.S"
  running "/nix/store/5p5zlzc7h33ab44vw6qf91c02zffz1da-ndk-bundle-18.1.5063045/libexec/android-sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-DNDEBUG" "-c" "-o/home/little-dude/code/cross-compile-reqwest/target/aarch64-linux-android/debug/build/ring-4c09cef695fad7d8/out/vpaes-armv8-linux64.o" "/home/little-dude/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.15/pregenerated/vpaes-armv8-linux64.S"
  running "/nix/store/5p5zlzc7h33ab44vw6qf91c02zffz1da-ndk-bundle-18.1.5063045/libexec/android-sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-DNDEBUG" "-c" "-o/home/little-dude/code/cross-compile-reqwest/target/aarch64-linux-android/debug/build/ring-4c09cef695fad7d8/out/armv8-mont-linux64.o" "/home/little-dude/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.15/pregenerated/armv8-mont-linux64.S"
  running "/nix/store/5p5zlzc7h33ab44vw6qf91c02zffz1da-ndk-bundle-18.1.5063045/libexec/android-sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-DNDEBUG" "-c" "-o/home/little-dude/code/cross-compile-reqwest/target/aarch64-linux-android/debug/build/ring-4c09cef695fad7d8/out/chacha-armv8-linux64.o" "/home/little-dude/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.15/pregenerated/chacha-armv8-linux64.S"
  running "/nix/store/5p5zlzc7h33ab44vw6qf91c02zffz1da-ndk-bundle-18.1.5063045/libexec/android-sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-DNDEBUG" "-c" "-o/home/little-dude/code/cross-compile-reqwest/target/aarch64-linux-android/debug/build/ring-4c09cef695fad7d8/out/ecp_nistz256-armv8-linux64.o" "/home/little-dude/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.15/pregenerated/ecp_nistz256-armv8-linux64.S"
  running "/nix/store/5p5zlzc7h33ab44vw6qf91c02zffz1da-ndk-bundle-18.1.5063045/libexec/android-sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-DNDEBUG" "-c" "-o/home/little-dude/code/cross-compile-reqwest/target/aarch64-linux-android/debug/build/ring-4c09cef695fad7d8/out/ghash-neon-armv8-linux64.o" "/home/little-dude/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.15/pregenerated/ghash-neon-armv8-linux64.S"
  running "/nix/store/5p5zlzc7h33ab44vw6qf91c02zffz1da-ndk-bundle-18.1.5063045/libexec/android-sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-DNDEBUG" "-c" "-o/home/little-dude/code/cross-compile-reqwest/target/aarch64-linux-android/debug/build/ring-4c09cef695fad7d8/out/poly1305-armv8-linux64.o" "/home/little-dude/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.15/pregenerated/poly1305-armv8-linux64.S"
  running "/nix/store/5p5zlzc7h33ab44vw6qf91c02zffz1da-ndk-bundle-18.1.5063045/libexec/android-sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-DNDEBUG" "-c" "-o/home/little-dude/code/cross-compile-reqwest/target/aarch64-linux-android/debug/build/ring-4c09cef695fad7d8/out/sha512-armv8-linux64.o" "/home/little-dude/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.15/pregenerated/sha512-armv8-linux64.S"
  running "/nix/store/5p5zlzc7h33ab44vw6qf91c02zffz1da-ndk-bundle-18.1.5063045/libexec/android-sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-DNDEBUG" "-c" "-o/home/little-dude/code/cross-compile-reqwest/target/aarch64-linux-android/debug/build/ring-4c09cef695fad7d8/out/sha256-armv8-linux64.o" "/home/little-dude/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.15/pregenerated/sha256-armv8-linux64.S"
  running "/nix/store/5p5zlzc7h33ab44vw6qf91c02zffz1da-ndk-bundle-18.1.5063045/libexec/android-sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-I" "include" "-Wall" "-Wextra" "-std=c1x" "-Wbad-function-cast" "-Wnested-externs" "-Wstrict-prototypes" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-DNDEBUG" "-c" "-o/home/little-dude/code/cross-compile-reqwest/target/aarch64-linux-android/debug/build/ring-4c09cef695fad7d8/out/aes_nohw.o" "crypto/fipsmodule/aes/aes_nohw.c"
  crypto/fipsmodule/aes/aes_nohw.c:18:10: fatal error: 'string.h' file not found
  #include <string.h>
           ^~~~~~~~~~
  1 error generated.
  thread 'main' panicked at 'execution failed', /home/little-dude/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.15/build.rs:664:9
```

Not sure if this is due to NixOS or the fact that I'm using an old NDK (18.1). Should I open another issue for this? FWIW I reproduced on a small repo: https://github.com/little-dude/ring-cross-compilation-fail

**Comment by briansmith** [comment] 2020-11-10 17:41
This is what I'm using in CI:

```
PATH=${ANDROID_SDK_ROOT}/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH \
CC_aarch64_linux_android=aarch64-linux-android21-clang \
CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER=aarch64-linux-android21-clang \
cargo test --no-run -vv --target=aarch64-linux-android
```

**Comment by briansmith** [comment] 2020-11-10 17:42
>  I'm using an old NDK (18.1)

Can you upgrade to a newer SDK/NDK? I'm not super eager to try to support those older ones.

**Comment by briansmith** [comment] 2020-11-11 03:09
Closing this since it is working fine in several build systems I work on.

**Closed by briansmith** 2020-11-11 03:09 UTC
