### ISSUE TITLE
Add doctests and documentation for `ring::aead`

### ISSUE THREAD

**Issue by foxsin10** [briansmith/ring#1496] opened 2022-05-20 16:04 UTC
Hi, I'm new to Rust and learning `AES-GCM` now. I found this great project to learn from.
But there is a problem, as the title mentioned, the official documentation [here](https://briansmith.org/rustdoc/ring/aead/index.html) for `aead` part, shows no example, can we have some examples?

**Comment by briansmith** [comment] 2023-10-14 15:30
Closing as a duplicate of #418.

**Closed by briansmith** 2023-10-14 15:30 UTC
Labels: duplicate
