### ISSUE TITLE
Can't build for mips-unknown-linux-musl (big endian platforms)

### ISSUE THREAD

**Issue by darrint** [briansmith/ring#361] opened 2016-11-29 00:48 UTC
```
$ cargo build --target mips-unknown-linux-musl   Compiling ring v0.4.3
   Compiling url v1.2.3
   Compiling openssl-sys-extras v0.7.14
   Compiling regex v0.1.80
error: macro undefined: 'u32x2!'
   --> /home/de-user/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.4.3/src/digest/digest.rs:326:9
    |
326 |         u32x2!(0x67452301u32, 0xefcdab89u32),
    |         ^^^^^

error: macro undefined: 'u32x2!'
   --> /home/de-user/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.4.3/src/digest/digest.rs:327:9
    |
327 |         u32x2!(0x98badcfeu32, 0x10325476u32),
    |         ^^^^^

$ cargo --version
cargo 0.13.0-nightly (eca9e15 2016-11-01)

$ rustc --version
rustc 1.13.0 (2c6933acc 2016-11-07)

```

**Comment by briansmith** [comment] 2016-11-29 01:00
If you look at the source code for the `u32x2` macro you'll see that it is only defined when the target endianness is little-endian. Therefore, we need somebody to contribute a big-endian implementation in order for this code to *compile*, which should be easy.

After that, in order to get the code to *link*, we'd need to get the MIPS assembly source code for all the assembly language modules from OpenSSL. BoringSSL removed all the MIPS assembly language code and *ring* removed all the non-assembly language code. This second task is quite a bit of work.

**Comment by darrint** [comment] 2016-11-29 01:22
Thanks for the info.

**Comment by briansmith** [comment] 2016-11-29 01:32
If somebody's interested in getting *ring* to work on MIPS, I'm happy to assist. At least getting things to compile for big-endian should be easy.

**Comment by briansmith** [comment] 2017-10-03 22:50
Closing this as a dupe of #562.

**Closed by briansmith** 2017-10-03 22:50 UTC
Labels: duplicate, good-first-bug
