### ISSUE TITLE
Solution for #461 and #491

### ISSUE THREAD

**Issue by Draphar** [briansmith/ring#860] opened 2019-06-24 14:23 UTC
According to #491, you (@briansmith) want to make it possible to use the properties of the algorithms at compile time. Today, `const fn` functions can be used to achieve this. If you want, I can open a pull request with `const` accessor functions for both `aead::Algorithm` and `digest::Algorithm`.

**Comment by briansmith** [comment] 2019-07-12 18:45
I would like to do something like this but not immediately. I'm going to close this as a duplicate of the other issues.

**Closed by briansmith** 2019-07-12 18:45 UTC

**Comment by Draphar** [comment] 2019-07-19 15:04
Ok. Feel free to message me if you have decided.
