### ISSUE TITLE
Allow long-lived keys for non-interactive ECDH

### ISSUE THREAD

**Issue by h4x3rotab** [briansmith/ring#959] opened 2020-03-02 18:24 UTC
Currently the ECDH keys are ephemeral (`EphemeralPrivateKey`), which is usually a good idea for interactive communication. However in case the communication is one-way non-interactive, it becomes a pain.

Consider a simple email encryption scenario. Alice want to send Bob an email. Alice has Bob's public key. So she just derive a secret by ECDH, encrypt the message, and send it along with the public key to Bob. Theoretically Bob can derive the same secret by ECDH, because he has the private key and Alice's public key.

However, because ECDH keys are ephemeral in ring, Bob can't reuse the private key, nor save the key to a database for future use.

In my case, the ECDH key pairs are generated by a key management system and distributed to the worker nodes on demand. The communication is done on a blockchain, which means it's pretty expensive to send messages between the peers back and forth. We would like to make it as non-interactive as possible.

Maybe I was wrong and there's a better way without weakening the key lifetime constraint. I always want to learn the best practice. Any suggestions are welcome.

**Comment by 0xbe7a** [comment] 2020-03-12 13:53
Duplicate of https://github.com/briansmith/ring/issues/331

**Comment by briansmith** [comment] 2020-03-27 17:08
> Duplicate of #331

Thanks!

**Closed by briansmith** 2020-03-27 17:08 UTC
Labels: duplicate
