### ISSUE TITLE
Document how to get SubjectPublicKey form from SubjectPublicKeyInfo

### ISSUE THREAD

**Issue by lawliet89** [briansmith/ring#476] opened 2017-03-07 03:17 UTC
I guess this is similar to https://github.com/briansmith/ring/issues/470.

I have computed an EC private key: `openssl ecparam -name prime256v1 -genkey -noout -outform der -out ecdsa_private_key.der` and the corresponding public key: `openssl ec -in ecdsa_private_key.der -inform der -pubout -out ecdsa_public_key.der -outform der`.

As far as I can tell, (by converting the `DER` public key to `PEM`), the public key from this is in `SubjectPublicKeyInfo`.  I understand that `ring` works with the "traditional" form (is this PKCS#1?) 

Is there any command line tool I could use to perform this conversion? `openssl ec` does not seem to have the `RSAPublicKey_{in|out}` analogue.

**Comment by briansmith** [comment] 2017-03-07 03:36
I don't know. It's better to ask on openssl-users; see https://www.openssl.org/community/mailinglists.html.

Once #378 is fixed, you'll be able to parse a `SubjectPublicKeyInfo` in *ring* to get the raw `SubjectPublicKey` that `sing::signature::verify()` uses.

**Comment by briansmith** [comment] 2023-10-14 16:52
Closing as a duplicate of #378.

**Closed by briansmith** 2023-10-14 16:52 UTC
