### ISSUE TITLE
Error: no such instruction: vbroadcasti128 etc.

### ISSUE THREAD

**Issue by Boscop** [briansmith/ring#551] opened 2017-05-31 09:45 UTC
When trying to compile my project on CentOS I get:
```
running "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-I" "include" "-std=c1x" "-Wbad-function
-cast" "-Wmissing-prototypes" "-Wnested-externs" "-Wstrict-prototypes" "-fdata-sections" "-ffunction-sections" "-pedanti
c" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Win
line" "-Winvalid-pch" "-Wmissing-declarations" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decl
s" "-Wshadow" "-Wsign-compare" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden
" "-Wno-cast-align" "-fstack-protector" "-g3" "-D_XOPEN_SOURCE=700" "-c" "-o/home/me/server/target/debug/build/ring-5d28e63d6fe2f47c/out/ecp_nistz.o" "crypto/ec/ecp_nistz.c"
running: "ar" "crs" "/home/me/server/target/debug/build/ring-5d28e63d6fe2f47c/out/libring-test.a" "/home/me/server/target/debug/build/ring-5d28e63d6fe2f47c/out/constant_time_test.o"
exit code: 0
cargo:rustc-link-lib=static=ring-test

--- stderr
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S: Assembler messages:
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1002: Error: no
such instruction: `vbroadcasti128 .Lsigma(%rip),%ymm11'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1003: Error: no
such instruction: `vbroadcasti128 (%rcx),%ymm3'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1004: Error: no
such instruction: `vbroadcasti128 16(%rcx),%ymm15'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1005: Error: no
such instruction: `vbroadcasti128 (%r8),%ymm7'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1011: Error: suf
fix or operands invalid for `vpshufd'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1012: Error: suf
fix or operands invalid for `vpshufd'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1014: Error: suf
fix or operands invalid for `vpshufd'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1016: Error: suf
fix or operands invalid for `vpshufd'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1020: Error: suf
fix or operands invalid for `vpshufd'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1021: Error: suf
fix or operands invalid for `vpshufd'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1023: Error: suf
fix or operands invalid for `vpshufd'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1025: Error: suf
fix or operands invalid for `vpshufd'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1029: Error: suf
fix or operands invalid for `vpshufd'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1030: Error: suf
fix or operands invalid for `vpshufd'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1032: Error: suf
fix or operands invalid for `vpshufd'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1034: Error: /ho
me/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/poly1305-x86_64-elf.S: Assembler messag
es:
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/poly1305-x86_64-elf.S:1469: Error: n
o such instruction: `vpermq $0x15,%ymm9,%ymm9'
suffix or operands invalid for `vpshufd'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1038: Error: suf
fix or operands invalid for `vpshufd'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1039: Error: suf
fix or operands invalid for `vpshufd'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1040: Error: suf
fix or operands invalid for `vpaddd'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1041: Error: suf
fix or operands invalid for `vpshufd'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1043: Error: suf
fix or operands invalid for `vpshufd'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/poly1305-x86_64-elf.S:1471: Error: /
home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1067: Error: suff
ix or operands invalid for `vpaddd'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1072: Error: no
such instruction: `vbroadcasti128 (%r10),%ymm15'
no such instruction: `vpermq $0x15,%ymm10,%ymm10'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1079: Error: suf
fix or operands invalid for `vpaddd'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1080: Error: suf
fix or operands invalid for `vpxor'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1081: Error: suf
fix or operands invalid for `vpshufb'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1082: /home/frui
t/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/poly1305-x86_64-elf.S:1472: Error: suffix or o
perands invalid for `vpshufd'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/poly1305-x86_64-elf.S:1474: Error: n
o such instruction: `vpermq $0x15,%ymm6,%ymm6'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/poly1305-x86_64-elf.S:1475: Error: s
uffix or operands invalid for `vpshufd'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/poly1305-x86_64-elf.S:1477: Error: s
uffix or operands invalid for `vpaddd'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1083: Error: suf
fix or operands invalid for `vpxor'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1084: Error: suf
fix or operands invalid for `vpshufb'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1085: Error: suf
fix or operands invalid for `vpaddd'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1086: Error: suf
fix or operands invalid for `vpxor'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1087: Error: suf
fix or operands invalid for `vpslld'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1088: Error: suf
fix or operands invalid for `vpsrld'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1089: Error: suf
fix or operands invalid for `vpor'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1090: Error: no
such instruction: `vbroadcasti128 (%r11),%ymm14'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1091: Error: suf
fix or operands invalid for `vpaddd'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1092: Error: suf
fix or operands invalid for `vpxor'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1093: Error: suf
fix or operands invalid for `vpslld'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1094: Error: suf
fix or operands invalid for `vpsrld'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1095: Error: suf
fix or operands invalid for `vpor'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1096: Error: suf
fix or operands invalid for `vpaddd'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1097: Error: suf
fix or operands invalid for `vpxor'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1098: Error: suf
fix or operands invalid for `vpshufb'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1099: Error: suf
fix or operands invalid for `vpaddd'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1100: Error: suf
fix or operands invalid for `vpxor'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1101: Error: suf
fix or operands invalid for `vpshufb'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1102: Error: suf
fix or operands invalid for `vpaddd'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1103: Error: suf
fix or operands invalid for `vpxor'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1104: Error: suf
fix or operands invalid for `vpslld'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1105: Error: suf
fix or operands invalid for `vpsrld'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1106: Error: suf
fix or operands invalid for `vpor'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1107: Error: no
such instruction: `vbroadcasti128 (%r10),%ymm15'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1108: Error: suf
fix or operands invalid for `vpaddd'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1109: Error: no
such instruction: `vpermq $0x15,%ymm11,%ymm11'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/poly1305-x86_64-elf.S:1478: Error: s
uffix or operands invalid for `vpshufd'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/poly1305-x86_64-elf.S:1480: Error: n
o such instruction: `vpermq $0x15,%ymm12,%ymm12'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/poly1305-x86_64-elf.S:1481: Error: s
uffix or operands invalid for `vpshufd'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/poly1305-x86_64-elf.S:1483: Error: n
o such instruction: `vpermq $0x15,%ymm13,%ymm13'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/poly1305-x86_64-elf.S:1484: Error: s
uffix or operands invalid for `vpshufd'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/poly1305-x86_64-elf.S:1486: Error: n
o such instruction: `vpermq $0x15,%ymm14,%ymm14'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/poly1305-x86_64-elf.S:1487: Error: s
uffix or operands invalid for `vpshufd'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/poly1305-x86_64-elf.S:1489: Error: n
o such instruction: `vpermq $0x15,%ymm15,%ymm15'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/poly1305-x86_64-elf.S:1490: Error: s
uffix or operands invalid for `vpshufd'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/poly1305-x86_64-elf.S:1492: Error: s
uffix or operands invalid for `vpxor'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1110: Error: suf
fix or operands invalid for `vpslld'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1111: Error: suf
fix or operands invalid for `vpsrld'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1112: Error: suf
fix or operands invalid for `vpor'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1117: Error: suf
fix or operands invalid for `vpaddd'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1118: Error: suf
fix or operands invalid for `vpxor'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1119: Error: suf
fix or operands invalid for `vpshufb'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1120: Error: suf
fix or operands invalid for `vpaddd'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1121: Error: suf
fix or operands invalid for `vpxor'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1122: Error: suf
fix or operands invalid for `vpshufb'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1123: Error: suf
fix or operands invalid for `vpaddd'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1124: Error: suf
fix or operands invalid for `vpxor'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1125: Error: suf
fix or operands invalid for `vpslld'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1126: Error: suf
fix or operands invalid for `vpsrld'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1127: Error: suf
fix or operands invalid for `vpor'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1128: Error: no
such instruction: `vbroadcasti128 (%r11),%ymm14'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1129: Error: suf
fix or operands invalid for `vpaddd'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1130: Error: suf
fix or operands invalid for `vpxor'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1131: Error: suf
fix or operands invalid for `vpslld'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1132: Error: suf
fix or operands invalid for `vpsrld'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1133: Error: suf
fix or operands invalid for `vpor'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1134: Error: suf
fix or operands invalid for `vpaddd'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1135: Error: suf
fix or operands invalid for `vpxor'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1136: Error: suf
fix or operands invalid for `vpshufb'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1137: Error: suf
fix or operands invalid for `vpaddd'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1138: Error: suf
fix or operands invalid for `vpxor'
/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.9.7/pregenerated/chacha-x86_64-elf.S:1139: Error: suf
fix or operands invalid for `vpshufb'
...
```

How can I get this to compile?

**Comment by briansmith** [comment] 2017-05-31 18:34
What versions of gcc, g++, gas, and/or clang are you using? The most likely reason for this build failure is the use of an ancient assembler.

**Comment by Boscop** [comment] 2017-05-31 19:52
The thing is, the installed gcc version on this server is 4.4.7 (I don't have root so I can't update). There are more recent versions in `/package/host/localhost/`, I'm using the `gcc` exe from 4.9.2 now and created a symlink in ~/bin/cc to that version of gcc but I'm not sure how to use the assembler from gcc 4.9.2:
```
$ gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18)
export PATH=/package/host/localhost/gcc-4/bin:$PATH
$ gcc --version
gcc (GCC) 4.9.2
```
With this, `cargo build` fails with the above errors.
These are the available exes, do I have to create more symlinks in ~/bin? I don't see a `gas` exe.
```
$ ls /package/host/localhost/gcc-4/bin
c++  gcc     gcc-ranlib                    x86_64-unknown-linux-gnu-g++        x86_64-unknown-linux-gnu-gcc-ar
cpp  gcc-ar  gcov                          x86_64-unknown-linux-gnu-gcc        x86_64-unknown-linux-gnu-gcc-nm
g++  gcc-nm  x86_64-unknown-linux-gnu-c++  x86_64-unknown-linux-gnu-gcc-4.9.2  x86_64-unknown-linux-gnu-gcc-ranlib
```

Btw, these are the available gcc versions in `/package/host/localhost/`:
```gcc-4/     gcc-4.9/   gcc-4.9.2/ gcc-5/     gcc-5.2/   gcc-5.2.0/```

**Comment by pietro** [comment] 2017-06-01 16:17
Does it work if you set `CC` to the full path of the compiler you want to use?

**Comment by Boscop** [comment] 2017-06-02 00:15
I added a symlink `~/bin/cc` to the gcc 4.9.2 from `/package/host/localhost/gcc-4/bin` and it is in `PATH` but I still get the assembler errors somehow. 
How can I also override `as` in `PATH`? There is no `as` or `gas` in `/package/host/localhost/gcc-4/bin`.

**Comment by briansmith** [comment] 2017-06-02 00:26
Can you try setting the CC environment variable to the new GCC before buiding, instead of using the symlink stuff, and see if that helps?

**Comment by Boscop** [comment] 2017-06-02 02:49
I tried `CC=/package/host/localhost/gcc-5/bin/gcc cargo build`, but I still get assembler errors, 
but for different instructions now:
```
running "/package/host/localhost/gcc-5/bin/gcc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-I" "
include" "-fdata-sections" "-ffunction-sections" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast
-qual" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-declarations" "-Wmissing-fiel
d-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wundef" "-Wuninitialized" "-W
write-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-Wno-cast-align" "-fstack-protector" "-g3" "-Werror" "-D_XO
PEN_SOURCE=700" "-c" "-o/home/me/ring/target/debug/build/ring-9adc2e0e5d0ed5c4/out/sha256-x86_64-elf.o" "/home/me/
ring/target/debug/build/ring-9adc2e0e5d0ed5c4/out/sha256-x86_64-elf.S"
exit code: 0
cargo:rustc-link-lib=static=ring-test

--- stderr
/home/me/ring/target/debug/build/ring-9adc2e0e5d0ed5c4/out/poly1305-x86_64-elf.S: Assembler messages:
/home/me/ring/target/debug/build/ring-9adc2e0e5d0ed5c4/out/poly1305-x86_64-elf.S:1469: Error: no such instruction: `v
permq $0x15,%ymm9,%ymm9'
/home/me/ring/target/debug/build/ring-9adc2e0e5d0ed5c4/out/poly1305-x86_64-elf.S:1471: Error: no such instruction: `v
permq $0x15,%ymm10,%ymm10'
/home/me/ring/target/debug/build/ring-9adc2e0e5d0ed5c4/out/poly1305-x86_64-elf.S:1472: Error: suffix or operands inva
lid for `vpshufd'
/home/me/ring/target/debug/build/ring-9adc2e0e5d0ed5c4/out/poly1305-x86_64-elf.S:1474: Error: no such instruction: `v
permq $0x15,%ymm6,%ymm6'
/home/me/ring/target/debug/build/ring-9adc2e0e5d0ed5c4/out/poly1305-x86_64-elf.S:1475: Error: suffix or operands inva
lid for `vpshufd'
/home/me/ring/target/debug/build/ring-9adc2e0e5d0ed5c4/out/poly1305-x86_64-elf.S:1477: Error: no such instruction: `v
permq $0x15,%ymm11,%ymm11'
/home/me/ring/target/debug/build/ring-9adc2e0e5d0ed5c4/out/poly1305-x86_64-elf.S:1478: Error: suffix or operands inva
lid for `vpshufd'
/home/me/ring/target/debug/build/ring-9adc2e0e5d0ed5c4/out/chacha-x86_64-elf.S: Assembler messages:
/home/me/ring/target/debug/build/ring-9adc2e0e5d0ed5c4/out/poly1305-x86_64-elf.S:1480: Error: no such instruction: `v
permq $0x15,%ymm12,%ymm12'
/home/me/ring/target/debug/build/ring-9adc2e0e5d0ed5c4/out/poly1305-x86_64-elf.S:1481: Error: suffix or operands inva
lid for `vpshufd'
/home/me/ring/target/debug/build/ring-9adc2e0e5d0ed5c4/out/poly1305-x86_64-elf.S:1483: Error: no such instruction: `v
permq $0x15,%ymm13,%ymm13'
/home/me/ring/target/debug/build/ring-9adc2e0e5d0ed5c4/out/poly1305-x86_64-elf.S:1484: Error: suffix or operands inva
lid for `vpshufd'
/home/me/ring/target/debug/build/ring-9adc2e0e5d0ed5c4/out/poly1305-x86_64-elf.S:1486: Error: no such instruction: `v
permq $0x15,%ymm14,%ymm14'
...
```

What else can I try?

**Comment by pietro** [comment] 2017-06-02 02:59
@Boscop what version of `binutils` are you using? `as` comes from it and you may have a version that's too old to understand the AVX instructions.

**Comment by Boscop** [comment] 2017-06-02 03:13
```
$ ld -v
GNU ld version 2.20.51.0.2-5.47.el6_9.1 20100205
$ as --version
GNU assembler version 2.20.51.0.2-5.47.el6_9.1 20100205
Copyright 2009 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or later.
This program has absolutely no warranty.
This assembler was configured for a target of `x86_64-redhat-linux'.
```

But I don't see it calling `as` anywhere in the `cargo build` output.

**Comment by pietro** [comment] 2017-06-02 03:24
GCC uses it under the hood. You need binutils 2.22 or newer.

**Comment by Boscop** [comment] 2017-06-02 03:33
Yeah but I'm not root so I can't update. I can only use the alternative packages from `/package/host/localhost/`. But there is no `as` in `/package/host/localhost/gcc-5/bin/`

**Comment by pietro** [comment] 2017-06-02 03:38
Do you have a `/package/host/localhost/binutils`? Can you compile/install it on your home dir?

**Comment by Boscop** [comment] 2017-06-02 03:59
I don't have `/package/host/localhost/binutils`. 
I'll try compiling binutils locally, should I use the one from here?
https://github.com/bminor/binutils-gdb

**Comment by pietro** [comment] 2017-06-02 04:15
I'd just use the upstream repository.

**Comment by Boscop** [comment] 2017-06-02 06:16
That repo is a mirror of the upstream repo, and I get the same result :(

**Comment by pietro** [comment] 2017-06-02 16:27
@Boscop try to find on the bintutils documentation how to skip the `makeinfo` step when building it.

@briansmith [BoringSSL build doc](https://boringssl.googlesource.com/boringssl/+/master/BUILDING.md) mentions the need for bintuils 2.22 or newer on x86 and x86_84.

**Comment by briansmith** [comment] 2017-06-10 01:21
I'm going to close this since I think things are working as intended.

If you are having trouble with binutils and friends you might also try with Clang as CC, instead of GCC. I think Clang's internal assembler would be used in that case.

**Closed by briansmith** 2017-06-10 01:21 UTC
