### ISSUE TITLE
much more : undefined references 

### ISSUE THREAD

**Issue by kirana1996** [briansmith/ring#1430] opened 2021-11-23 07:42 UTC
Hi,
when I build ring, it can cargo build pass! (My platform: riscv64gc)
But, when I cargo test, much more undefined reference occurred. How can I resolve this issue on riscv platform?

Compiling ring v0.17.0-not-released-yet (/home/root/kiran/ring)
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.1d3u8b0hihe8ssaw.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.1f5my7ipwli65nfz.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.1isg4khfmgdt43w2.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.1ixle9zu37e8hhjl.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.1nb66jof0ipsd8lm.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.1uj4rp32uz1hoe2x.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.1vbyxfwzd343rag3.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.20tgtuyc8fly6hkk.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.22a9tg4966u44t4m.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.26ca5kontz8wlonq.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.2bq7dnnu6jud2jsg.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.2chvwdxbqnzeyz6b.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.2t6agvqt7c38qp7i.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.2vpmqbcql1qsp1ve.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.2vr30hb7tk8bl2rt.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.2xf4h6w8fxgm7ewb.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.37grvd2y07g68bt1.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.3bkezqd33glg6gut.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.3bkwxesb2zw8buy3.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.3dgxd1ilf7xv7h0s.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.3efv3pzsbm4d203c.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.3qh3ojbpb9rpl91e.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.3rtuox8ghqr2sg6k.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.3urhlkhr8396w2cp.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.3zavb6qqzc2k48j1.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.3zpiyu6men8bvt9e.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.41l6a5k8q0tlnauu.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.46aa19i1zl7fg8rv.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.49vfao9o24go5cu9.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.4blj0bj8r24r5tbr.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.4equi7j0qim1b3ww.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.4fdgiwxgd576zfs3.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.4lxj7dyype5ylsao.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.4u0yymd38002to21.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.4w5j94uaofva63uy.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.4wwxa4oq78uk7gia.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.4zgvvyjk27ib68ph.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.5374b4xb47nlqsa5.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.53nr0fpid1yuesbn.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.5dhfxajeqdpgp130.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.5e4xvylitrn8au5n.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.5no85261esc390u.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.7gsvxt1zoy0zr4l.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.96xcll6n3eyci4o.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.dmc947pkzc8t1ac.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.h4gm7frths14lzl.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.i8ctk5f4jnxt2zm.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.mvyvj3od6gy5vav.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.o2n0tingd8o2x7o.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.pvlx0dd5kwiletd.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.rej36fly0n99t80.rcgu.o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca.55995nj2ldgfbrqb.rcgu.o" "-Wl,--as-needed" "-L" "/home/root/kiran/ring/target/debug/deps" "-L" "/home/root/kiran/ring/target/debug/build/ring-95cd5e8ef9e76475/out" "-L" "/home/root/.rustup/toolchains/stable-riscv64gc-unknown-linux-gnu/lib/rustlib/riscv64gc-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/home/root/.rustup/toolchains/stable-riscv64gc-unknown-linux-gnu/lib/rustlib/riscv64gc-unknown-linux-gnu/lib/libtest-12efc6e077c196c7.rlib" "/home/root/.rustup/toolchains/stable-riscv64gc-unknown-linux-gnu/lib/rustlib/riscv64gc-unknown-linux-gnu/lib/libgetopts-e5a3e9f59aa94dac.rlib" "/home/root/.rustup/toolchains/stable-riscv64gc-unknown-linux-gnu/lib/rustlib/riscv64gc-unknown-linux-gnu/lib/libunicode_width-8dc80f0df126f5d9.rlib" "/home/root/.rustup/toolchains/stable-riscv64gc-unknown-linux-gnu/lib/rustlib/riscv64gc-unknown-linux-gnu/lib/librustc_std_workspace_std-849128e48f4c4752.rlib" "/home/root/kiran/ring/target/debug/deps/libring-292da16f8573ce81.rlib" "/home/root/kiran/ring/target/debug/deps/liblibc-b2e9de3d40892c56.rlib" "/home/root/kiran/ring/target/debug/deps/libuntrusted-9c1932a768c916ec.rlib" "/home/root/kiran/ring/target/debug/deps/libonce_cell-9fa70ca044be127f.rlib" "-Wl,--start-group" "/home/root/.rustup/toolchains/stable-riscv64gc-unknown-linux-gnu/lib/rustlib/riscv64gc-unknown-linux-gnu/lib/libstd-fe656636140528b7.rlib" "/home/root/.rustup/toolchains/stable-riscv64gc-unknown-linux-gnu/lib/rustlib/riscv64gc-unknown-linux-gnu/lib/libpanic_unwind-7858de1acee1a1c7.rlib" "/home/root/.rustup/toolchains/stable-riscv64gc-unknown-linux-gnu/lib/rustlib/riscv64gc-unknown-linux-gnu/lib/libminiz_oxide-ded21f57982cd92c.rlib" "/home/root/.rustup/toolchains/stable-riscv64gc-unknown-linux-gnu/lib/rustlib/riscv64gc-unknown-linux-gnu/lib/libadler-4d87b96fa00a887f.rlib" "/home/root/.rustup/toolchains/stable-riscv64gc-unknown-linux-gnu/lib/rustlib/riscv64gc-unknown-linux-gnu/lib/libobject-e30c011c1996cd88.rlib" "/home/root/.rustup/toolchains/stable-riscv64gc-unknown-linux-gnu/lib/rustlib/riscv64gc-unknown-linux-gnu/lib/libmemchr-82a4df0daea2c257.rlib" "/home/root/.rustup/toolchains/stable-riscv64gc-unknown-linux-gnu/lib/rustlib/riscv64gc-unknown-linux-gnu/lib/libaddr2line-0c36a2ef33fcb15c.rlib" "/home/root/.rustup/toolchains/stable-riscv64gc-unknown-linux-gnu/lib/rustlib/riscv64gc-unknown-linux-gnu/lib/libgimli-d8b048b5c7208952.rlib" "/home/root/.rustup/toolchains/stable-riscv64gc-unknown-linux-gnu/lib/rustlib/riscv64gc-unknown-linux-gnu/lib/libstd_detect-4928c2aad49e465b.rlib" "/home/root/.rustup/toolchains/stable-riscv64gc-unknown-linux-gnu/lib/rustlib/riscv64gc-unknown-linux-gnu/lib/librustc_demangle-ba061a1012259fb8.rlib" "/home/root/.rustup/toolchains/stable-riscv64gc-unknown-linux-gnu/lib/rustlib/riscv64gc-unknown-linux-gnu/lib/libhashbrown-e5698e1952743135.rlib" "/home/root/.rustup/toolchains/stable-riscv64gc-unknown-linux-gnu/lib/rustlib/riscv64gc-unknown-linux-gnu/lib/librustc_std_workspace_alloc-5eec3b05d8afbedd.rlib" "/home/root/.rustup/toolchains/stable-riscv64gc-unknown-linux-gnu/lib/rustlib/riscv64gc-unknown-linux-gnu/lib/libunwind-fa37e7f3dfc1fec3.rlib" "/home/root/.rustup/toolchains/stable-riscv64gc-unknown-linux-gnu/lib/rustlib/riscv64gc-unknown-linux-gnu/lib/libcfg_if-761273d9282eb44a.rlib" "/home/root/.rustup/toolchains/stable-riscv64gc-unknown-linux-gnu/lib/rustlib/riscv64gc-unknown-linux-gnu/lib/liblibc-8033f19ec64bf432.rlib" "/home/root/.rustup/toolchains/stable-riscv64gc-unknown-linux-gnu/lib/rustlib/riscv64gc-unknown-linux-gnu/lib/liballoc-cf3e646508106b81.rlib" "/home/root/.rustup/toolchains/stable-riscv64gc-unknown-linux-gnu/lib/rustlib/riscv64gc-unknown-linux-gnu/lib/librustc_std_workspace_core-2bb5719decb22083.rlib" "/home/root/.rustup/toolchains/stable-riscv64gc-unknown-linux-gnu/lib/rustlib/riscv64gc-unknown-linux-gnu/lib/libcore-077f3fd24617398a.rlib" "-Wl,--end-group" "/home/root/.rustup/toolchains/stable-riscv64gc-unknown-linux-gnu/lib/rustlib/riscv64gc-unknown-linux-gnu/lib/libcompiler_builtins-bcbdeb4f27335228.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/home/root/.rustup/toolchains/stable-riscv64gc-unknown-linux-gnu/lib/rustlib/riscv64gc-unknown-linux-gnu/lib" "-o" "/home/root/kiran/ring/target/debug/deps/ecdsa_tests-439597e965c5d0ca" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs"
  = note: /usr/lib/gcc/riscv64-oe-linux/10.2.0/../../../../riscv64-oe-linux/bin/ld: /home/root/kiran/ring/target/debug/deps/libring-292da16f8573ce81.rlib(ring-292da16f8573ce81.4jm7xnh3j1246cgk.rcgu.o): in function `ring::ec::suite_b::ops::p256::p256_point_mul_base_impl':
          /home/root/kiran/ring/src/ec/suite_b/ops/p256.rs:135: undefined reference to `ring_core_0_17_0_not_released_yet_p256_point_mul_base'
          /usr/lib/gcc/riscv64-oe-linux/10.2.0/../../../../riscv64-oe-linux/bin/ld: /home/root/kiran/ring/target/debug/deps/libring-292da16f8573ce81.rlib(ring-292da16f8573ce81.4jm7xnh3j1246cgk.rcgu.o): in function `ring::ec::suite_b::ops::p256::p256_scalar_inv_to_mont::mul':
          /home/root/kiran/ring/src/ec/suite_b/ops/p256.rs:187: undefined reference to `ring_core_0_17_0_not_released_yet_p256_scalar_mul_mont'
          /usr/lib/gcc/riscv64-oe-linux/10.2.0/../../../../riscv64-oe-linux/bin/ld: /home/root/kiran/ring/target/debug/deps/libring-292da16f8573ce81.rlib(ring-292da16f8573ce81.4jm7xnh3j1246cgk.rcgu.o): in function `ring::ec::suite_b::ops::p256::p256_scalar_inv_to_mont::sqr':
          /home/root/kiran/ring/src/ec/suite_b/ops/p256.rs:193: undefined reference to `ring_core_0_17_0_not_released_yet_p256_scalar_sqr_rep_mont'
          /usr/lib/gcc/riscv64-oe-linux/10.2.0/../../../../riscv64-oe-linux/bin/ld: /home/root/kiran/ring/target/debug/deps/libring-292da16f8573ce81.rlib(ring-292da16f8573ce81.4jm7xnh3j1246cgk.rcgu.o): in function `ring::ec::suite_b::ops::p256::p256_scalar_inv_to_mont::sqr_mul':
          /home/root/kiran/ring/src/ec/suite_b/ops/p256.rs:201: undefined reference to `ring_core_0_17_0_not_released_yet_p256_scalar_sqr_rep_mont'
          /usr/lib/gcc/riscv64-oe-linux/10.2.0/../../../../riscv64-oe-linux/bin/ld: /home/root/kiran/ring/target/debug/deps/libring-292da16f8573ce81.rlib(ring-292da16f8573ce81.4jm7xnh3j1246cgk.rcgu.o): in function `ring::ec::suite_b::ops::p256::p256_scalar_inv_to_mont::sqr_mul_acc':
          /home/root/kiran/ring/src/ec/suite_b/ops/p256.rs:208: undefined reference to `ring_core_0_17_0_not_released_yet_p256_scalar_sqr_rep_mont'
          /usr/lib/gcc/riscv64-oe-linux/10.2.0/../../../../riscv64-oe-linux/bin/ld: /home/root/kiran/ring/src/ec/suite_b/ops/p256.rs:209: undefined reference to `ring_core_0_17_0_not_released_yet_p256_scalar_mul_mont'
          /usr/lib/gcc/riscv64-oe-linux/10.2.0/../../../../riscv64-oe-linux/bin/ld: /home/root/kiran/ring/target/debug/deps/libring-292da16f8573ce81.rlib(ring-292da16f8573ce81.4jm7xnh3j1246cgk.rcgu.o): in function `ring::ec::suite_b::ops::p256::p256_scalar_inv_to_mont::to_mont':
          /home/root/kiran/ring/src/ec/suite_b/ops/p256.rs:221: undefined reference to `ring_core_0_17_0_not_released_yet_p256_scalar_mul_mont'
          /usr/lib/gcc/riscv64-oe-linux/10.2.0/../../../../riscv64-oe-linux/bin/ld: /home/root/kiran/ring/target/debug/deps/libring-292da16f8573ce81.rlib(ring-292da16f8573ce81.4jm7xnh3j1246cgk.rcgu.o):(.data.rel.ro._ZN4ring2ec7suite_b3ops4p25610COMMON_OPS17ha559aaac09b159eaE+0xf8): undefined reference to `ring_core_0_17_0_not_released_yet_p256_mul_mont'
          /usr/lib/gcc/riscv64-oe-linux/10.2.0/../../../../riscv64-oe-linux/bin/ld: /home/root/kiran/ring/target/debug/deps/libring-292da16f8573ce81.rlib(ring-292da16f8573ce81.4jm7xnh3j1246cgk.rcgu.o):(.data.rel.ro._ZN4ring2ec7suite_b3ops4p25610COMMON_OPS17ha559aaac09b159eaE+0x100): undefined reference to `ring_core_0_17_0_not_released_yet_p256_sqr_mont'
          /usr/lib/gcc/riscv64-oe-linux/10.2.0/../../../../riscv64-oe-linux/bin/ld: /home/root/kiran/ring/target/debug/deps/libring-292da16f8573ce81.rlib(ring-292da16f8573ce81.4jm7xnh3j1246cgk.rcgu.o):(.data.rel.ro._ZN4ring2ec7suite_b3ops4p25610COMMON_OPS17ha559aaac09b159eaE+0x108): undefined reference to `ring_core_0_17_0_not_released_yet_p256_point_add'
          /usr/lib/gcc/riscv64-oe-linux/10.2.0/../../../../riscv64-oe-linux/bin/ld: /home/root/kiran/ring/target/debug/deps/libring-292da16f8573ce81.rlib(ring-292da16f8573ce81.4jm7xnh3j1246cgk.rcgu.o):(.data.rel.ro._ZN4ring2ec7suite_b3ops4p25615PRIVATE_KEY_OPS17habff113e7632b4ddE+0x18): undefined reference to `ring_core_0_17_0_not_released_yet_p256_point_mul'
          /usr/lib/gcc/riscv64-oe-linux/10.2.0/../../../../riscv64-oe-linux/bin/ld: /home/root/kiran/ring/target/debug/deps/libring-292da16f8573ce81.rlib(ring-292da16f8573ce81.4jm7xnh3j1246cgk.rcgu.o):(.data.rel.ro._ZN4ring2ec7suite_b3ops4p25610SCALAR_OPS17hb15010c61e757606E+0x10): undefined reference to `ring_core_0_17_0_not_released_yet_p256_scalar_mul_mont'
          /usr/lib/gcc/riscv64-oe-linux/10.2.0/../../../../riscv64-oe-linux/bin/ld: /home/root/kiran/ring/target/debug/deps/libring-292da16f8573ce81.rlib(ring-292da16f8573ce81.2b5mcncoefsfghsi.rcgu.o): in function `ring::ec::suite_b::ops::PrivateKeyOps::point_mul':
          /home/root/kiran/ring/src/ec/suite_b/ops.rs:192: undefined reference to `ring_core_0_17_0_not_released_yet_nistz384_point_mul'
          /usr/lib/gcc/riscv64-oe-linux/10.2.0/../../../../riscv64-oe-linux/bin/ld: /home/root/kiran/ring/target/debug/deps/libring-292da16f8573ce81.rlib(ring-292da16f8573ce81.2b5mcncoefsfghsi.rcgu.o): in function `ring::ec::suite_b::ops::p384::p384_scalar_inv_to_mont::mul':
          /home/root/kiran/ring/src/ec/suite_b/ops/p384.rs:204: undefined reference to `ring_core_0_17_0_not_released_yet_p384_scalar_mul_mont'
          /usr/lib/gcc/riscv64-oe-linux/10.2.0/../../../../riscv64-oe-linux/bin/ld: /home/root/kiran/ring/target/debug/deps/libring-292da16f8573ce81.rlib(ring-292da16f8573ce81.2b5mcncoefsfghsi.rcgu.o): in function `ring::ec::suite_b::ops::p384::p384_scalar_inv_to_mont::sqr':
          /home/root/kiran/ring/src/ec/suite_b/ops/p384.rs:208: undefined reference to `ring_core_0_17_0_not_released_yet_p384_scalar_mul_mont'
          /usr/lib/gcc/riscv64-oe-linux/10.2.0/../../../../riscv64-oe-linux/bin/ld: /home/root/kiran/ring/target/debug/deps/libring-292da16f8573ce81.rlib(ring-292da16f8573ce81.2b5mcncoefsfghsi.rcgu.o): in function `ring::ec::suite_b::ops::p384::p384_scalar_inv_to_mont::sqr_mut':
          /home/root/kiran/ring/src/ec/suite_b/ops/p384.rs:212: undefined reference to `ring_core_0_17_0_not_released_yet_p384_scalar_mul_mont'
          /usr/lib/gcc/riscv64-oe-linux/10.2.0/../../../../riscv64-oe-linux/bin/ld: /home/root/kiran/ring/target/debug/deps/libring-292da16f8573ce81.rlib(ring-292da16f8573ce81.2b5mcncoefsfghsi.rcgu.o): in function `ring::ec::suite_b::ops::p384::p384_scalar_inv_to_mont::sqr_mul_acc':
          /home/root/kiran/ring/src/ec/suite_b/ops/p384.rs:231: undefined reference to `ring_core_0_17_0_not_released_yet_p384_scalar_mul_mont'
          /usr/lib/gcc/riscv64-oe-linux/10.2.0/../../../../riscv64-oe-linux/bin/ld: /home/root/kiran/ring/target/debug/deps/libring-292da16f8573ce81.rlib(ring-292da16f8573ce81.2b5mcncoefsfghsi.rcgu.o): in function `ring::ec::suite_b::ops::p384::p384_scalar_inv_to_mont::to_mont':
          /home/root/kiran/ring/src/ec/suite_b/ops/p384.rs:240: undefined reference to `ring_core_0_17_0_not_released_yet_p384_scalar_mul_mont'
          /usr/lib/gcc/riscv64-oe-linux/10.2.0/../../../../riscv64-oe-linux/bin/ld: /home/root/kiran/ring/target/debug/deps/libring-292da16f8573ce81.rlib(ring-292da16f8573ce81.2b5mcncoefsfghsi.rcgu.o): in function `ring::ec::suite_b::ops::p384::p384_elem_sqr_mont':
          /home/root/kiran/ring/src/ec/suite_b/ops/p384.rs:332: undefined reference to `ring_core_0_17_0_not_released_yet_p384_elem_mul_mont'
          /usr/lib/gcc/riscv64-oe-linux/10.2.0/../../../../riscv64-oe-linux/bin/ld: /home/root/kiran/ring/target/debug/deps/libring-292da16f8573ce81.rlib(ring-292da16f8573ce81.2b5mcncoefsfghsi.rcgu.o):(.data.rel.ro._ZN4ring2ec7suite_b3ops4p38410COMMON_OPS17hd5d6b9d1ff88cb08E+0xf8): undefined reference to `ring_core_0_17_0_not_released_yet_p384_elem_mul_mont'
          /usr/lib/gcc/riscv64-oe-linux/10.2.0/../../../../riscv64-oe-linux/bin/ld: /home/root/kiran/ring/target/debug/deps/libring-292da16f8573ce81.rlib(ring-292da16f8573ce81.2b5mcncoefsfghsi.rcgu.o):(.data.rel.ro._ZN4ring2ec7suite_b3ops4p38410COMMON_OPS17hd5d6b9d1ff88cb08E+0x108): undefined reference to `ring_core_0_17_0_not_released_yet_nistz384_point_add'
          /usr/lib/gcc/riscv64-oe-linux/10.2.0/../../../../riscv64-oe-linux/bin/ld: /home/root/kiran/ring/target/debug/deps/libring-292da16f8573ce81.rlib(ring-292da16f8573ce81.2b5mcncoefsfghsi.rcgu.o):(.data.rel.ro._ZN4ring2ec7suite_b3ops4p38415PRIVATE_KEY_OPS17h103cd94870fefb0fE+0x18): undefined reference to `ring_core_0_17_0_not_released_yet_nistz384_point_mul'
          /usr/lib/gcc/riscv64-oe-linux/10.2.0/../../../../riscv64-oe-linux/bin/ld: /home/root/kiran/ring/target/debug/deps/libring-292da16f8573ce81.rlib(ring-292da16f8573ce81.2b5mcncoefsfghsi.rcgu.o):(.data.rel.ro._ZN4ring2ec7suite_b3ops4p38410SCALAR_OPS17h34349204dfdb2bc7E+0x10): undefined reference to `ring_core_0_17_0_not_released_yet_p384_scalar_mul_mont'
          collect2: error: ld returned 1 exit status
          
  = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

error: could not compile `ring` due to previous error

Can resolve this....

**Comment by briansmith** [comment] 2021-12-09 01:14
Closing this as a duplicate of #1419. See that issue.

**Comment by svenstaro** [comment] 2022-09-14 01:59
@briansmith did you forget to close this?

**Closed** 2022-09-20 15:34 UTC
