### ISSUE TITLE
No Continuous Testing (CT) setup for SGX

### ISSUE THREAD

**Issue by jethrogb** [briansmith/ring#778] opened 2019-01-30 12:51 UTC
While the `x86_64-fortanix-unknown-sgx` is built in CI, the tests are not run. Running the tests requires an SGX-enabled environment which is not available in Travis.

**Comment by briansmith** [comment] 2023-10-31 00:28
Closing as a duplicate of #775.

**Closed by briansmith** 2023-10-31 00:28 UTC
Labels: duplicate
