### ISSUE TITLE
could not compile the crate "ring" using cargo wasi

### ISSUE THREAD

**Issue by Hanifff** [briansmith/ring#1322] opened 2021-06-28 09:32 UTC
Hi, I try to build a project using cargo wasi with the ```cargo wasi build``` command to generate wasm files.
But it returnes with the following error:
```Compiling typenum v1.13.0
   Compiling version_check v0.9.3
   Compiling rand_core v0.6.3
   Compiling cc v1.0.68
   Compiling subtle v2.4.0
   Compiling protobuf v2.24.1
   Compiling untrusted v0.7.1
   Compiling generic-array v0.14.4
   Compiling ring v0.16.20
error[E0432]: unresolved import `super::sysrand_chunk`
   --> /home/hanif/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/src/rand.rs:306:16
    |
306 |     use super::sysrand_chunk::chunk;
    |                ^^^^^^^^^^^^^ could not find `sysrand_chunk` in `super`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `ring`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed```


The content of cargo.toml file is as follows:
````
[package]
name = "echo_server"
version = "0.1.0"
authors = ["hanifff <me@me.no>"]
edition = "2018"

[lib]
crate-type = ['cdylib']

[dependencies]
protobuf = "2.24.1"
ecdsa = "0.12.2"
ring = "0.16.20"
````

Rust verison: 

```rustc 1.55.0-nightly (2021-06-24)````

Cargo version:

```
cargo 1.55.0-nightly (2021-06-22)
```

Cargo-wasi version:

```
cargo-wasi 0.1.22 (2020-04-23)
````

The project can be build by ```cargo build``` command. Does ring support [cargo wasi](https://bytecodealliance.github.io/cargo-wasi/)?

**Comment by briansmith** [comment] 2021-06-28 16:18
This is a duplicate of issue #1043. Let's continue the discussion there.

**Closed by briansmith** 2021-06-28 16:18 UTC
