### ISSUE TITLE
cannot compile ring 0.11 on latest nightly on msvc

### ISSUE THREAD

**Issue by tinaun** [briansmith/ring#585] opened 2017-10-20 06:35 UTC
i keep getting this repeated sequence of errors

```
.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.11.0\crypto\curve25519\../internal.h(189) : warning C4431: missing type specifier - int assumed. Note: C no longer supports default-int
.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.11.0\crypto\curve25519\../internal.h(189) : error C2054: expected '(' to follow 'inline'
.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.11.0\crypto\curve25519\../internal.h(189) : error C2085: 'constant_time_msb_unsigned' : not in formal parameter list
.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.11.0\crypto\curve25519\../internal.h(189) : error C2143: syntax error : missing ';' before '{'
```

for basically every header file used in ring. i have vs2015 installed and updated. 
```
Microsoft Visual Studio Community 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.7.02556
```

**Comment by briansmith** [comment] 2017-12-23 21:36
@tinaun ring 0.11 isn't supported any more. Only *ring* 0.12.1 is supported currently. Soon we'll release 0.13 which will be the only supported version.

FWIW, I can't reproduce the issue using the latest git checkout for *ring* w/ the lateset MSVC 2017. I know this is quite different than the configuration you tried. However, we also build with MSVC 2015 on AppVeyor and it's been passing for quite a while.

I suggest waiting ~1 more week for the *ring* 0.13 release and then try again.

**Comment by tinaun** [comment] 2017-12-23 21:51
yeah, i'm only on 0.11 because of older libraries that depend on it.

hopefully everything with nightly atm gets sorted out quickly and i can use the most recent versions of everything without it breaking on me

**Comment by briansmith** [comment] 2018-05-15 03:27
I've been building on MSVC (2017) and it's been working great. I'm not sure if MSVC 2015 still works or not, but I think so, since the AppVeyor configurations seem to be using it.

I'm going to close this. Please add a comment if the master branch or ring-0.13.0-alpha2 fail to build with whatever version of MSVC you are using (as long as it's MSVC 2015 update 2 or later).

**Closed by briansmith** 2018-05-15 03:27 UTC
