### ISSUE TITLE
Reproducibility issue in 0.17.5

### ISSUE THREAD

**Issue by DFINITYManu** [briansmith/ring#1788] opened 2023-11-01 13:50 UTC
After 0.16.20 which was perfectly reproducible no matter the path to the project including ring, 0.17.5 has reproducibility issues.

![image](https://github.com/briansmith/ring/assets/123385598/53271ace-39d3-48e3-8683-14fe994fdbce)

What you are looking at is the same program built under directories `metrics-proxy` and `petrics-mroxy`, but with the `RUSTFLAGS='--remap-path-prefix=/home/manuel/src/petrics-mroxy=/home/manuel/src/metrics-proxy'` which ensures both should be identical -- and they are, so long as the ring version is 0.16.20, but not with 0.17.5.

We have mitigated using the `CFLAGS` trick mentioned in https://github.com/briansmith/ring/issues/715 but we would prefer not to have to do this.

Thanks in advance!

**Comment by briansmith** [comment] 2023-11-01 15:37
Closing as a duplicate of #715. I don't know why/how 0.16.20 didn't have the same issue, BTW.

**Closed by briansmith** 2023-11-01 15:37 UTC
Labels: duplicate

**Comment by DFINITYManu** [comment] 2023-11-01 15:49
I found the reason why 0.16.20 here was working... the CFLAGS trick was being used and I did not notice it.  Thanks.
