### ISSUE TITLE
Fail build on windows 10

### ISSUE THREAD

**Issue by heckad** [briansmith/ring#940] opened 2020-01-24 21:00 UTC
```
error: failed to run custom build command for `ring v0.13.5`

Caused by:
  process didn't exit successfully: `C:\Users\Asus\Documents\Projects\rust\python_questions_website\target\debug\build\ring-998d70eddb5ca50d\build-script-build` (exit code: 101)
--- stdout
=::: ::\
ALLUSERSPROFILE: C:\ProgramData
APPDATA: C:\Users\Asus\AppData\Roaming
CARGO: \\?\C:\Users\Asus\.rustup\toolchains\nightly-x86_64-pc-windows-gnu\bin\cargo.exe
CARGO_CFG_DEBUG_ASSERTIONS: 
CARGO_CFG_PROC_MACRO: 
CARGO_CFG_TARGET_ARCH: x86_64
CARGO_CFG_TARGET_ENDIAN: little
CARGO_CFG_TARGET_ENV: gnu
CARGO_CFG_TARGET_FAMILY: windows
CARGO_CFG_TARGET_FEATURE: fxsr,mmx,sse,sse2
CARGO_CFG_TARGET_HAS_ATOMIC: 16,32,64,8,ptr
CARGO_CFG_TARGET_HAS_ATOMIC_LOAD_STORE: 16,32,64,8,ptr
CARGO_CFG_TARGET_OS: windows
CARGO_CFG_TARGET_POINTER_WIDTH: 64
CARGO_CFG_TARGET_VENDOR: pc
CARGO_CFG_WINDOWS: 
CARGO_FEATURE_DEFAULT: 1
CARGO_FEATURE_DEV_URANDOM_FALLBACK: 1
CARGO_FEATURE_USE_HEAP: 1
CARGO_HOME: C:\Users\Asus\.cargo
CARGO_MAKEFLAGS: --jobserver-fds=__rust_jobserver_semaphore_2450166508 --jobserver-auth=__rust_jobserver_semaphore_2450166508
CARGO_MANIFEST_DIR: C:\Users\Asus\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.13.5
CARGO_MANIFEST_LINKS: ring-asm
CARGO_PKG_AUTHORS: Brian Smith <brian@briansmith.org>
CARGO_PKG_DESCRIPTION: Safe, fast, small crypto using Rust.
CARGO_PKG_HOMEPAGE: 
CARGO_PKG_NAME: ring
CARGO_PKG_REPOSITORY: https://github.com/briansmith/ring
CARGO_PKG_VERSION: 0.13.5
CARGO_PKG_VERSION_MAJOR: 0
CARGO_PKG_VERSION_MINOR: 13
CARGO_PKG_VERSION_PATCH: 5
CARGO_PKG_VERSION_PRE: 
CHOCOLATEYINSTALL: C:\ProgramData\chocolatey
CHOCOLATEYLASTPATHUPDATE: 132128450861841904
COMMONPROGRAMFILES: C:\Program Files\Common Files
COMMONPROGRAMFILES(X86): C:\Program Files (x86)\Common Files
COMMONPROGRAMW6432: C:\Program Files\Common Files
COMPOSE_CONVERT_WINDOWS_PATHS: true
COMPUTERNAME: HECKAD
COMSPEC: C:\WINDOWS\system32\cmd.exe
DEBUG: true
DOCKER_CERT_PATH: C:\Users\Asus\.docker\machine\machines\default
DOCKER_HOST: tcp://192.168.99.110:2376
DOCKER_MACHINE_NAME: default
DOCKER_TLS_VERIFY: 1
DOCKER_TOOLBOX_INSTALL_PATH: C:\Program Files\Docker Toolbox
DRIVERDATA: C:\Windows\System32\Drivers\DriverData
FPS_BROWSER_APP_PROFILE_STRING: Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING: Default
GAMEFIRST: C:\Program Files (x86)\ASUS\GameFirst V\
HOMEDRIVE: C:
HOMEPATH: \Users\Asus
HOST: x86_64-pc-windows-gnu
IDEA_INITIAL_DIRECTORY: C:\Users\Asus\AppData\Local\JetBrains\Toolbox\apps\CLion\ch-0\193.6015.37\bin
JAVA_HOME: C:\Program Files\Java\jdk-11.0.2
LD_LIBRARY_PATH: C:\Users\Asus\.rustup\toolchains\nightly-x86_64-pc-windows-gnu\lib
LOCALAPPDATA: C:\Users\Asus\AppData\Local
LOGONSERVER: \\HECKAD
MSMPI_BIN: C:\Program Files\Microsoft MPI\Bin\
NO_PROXY: 192.168.99.102,192.168.99.110
NUMBER_OF_PROCESSORS: 12
NUM_JOBS: 12
ONEDRIVE: C:\Users\Asus\OneDrive
ONEDRIVECONSUMER: C:\Users\Asus\OneDrive
OPENSSL_CONF: C:\ProgramData\Anaconda3\openssl.cnf
OPENSSL_INCLUDE_DIR: C:\ProgramData\Anaconda3
OPENSSL_ROOT_DIR: C:\ProgramData\Anaconda3
OPT_LEVEL: 0
OS: Windows_NT
OUT_DIR: C:\Users\Asus\Documents\Projects\rust\python_questions_website\target\debug\build\ring-02b6371541a14225\out
PATH: C:\Users\Asus\Documents\Projects\rust\python_questions_website\target\debug\deps;C:\Users\Asus\.rustup\toolchains\nightly-x86_64-pc-windows-gnu\bin;C:\Users\Asus\.cargo\bin;C:\Users\Asus\.rustup\toolchains\nightly-x86_64-pc-windows-gnu\bin;C:\Program Files\Python38\Scripts\;C:\Program Files\Python38\;C:\Program Files\Microsoft MPI\Bin\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Bitvise SSH Client;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\CMake\bin;C:\Program Files\LLVM\bin;C:\Program Files\Git\bin;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Сhromedriver;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64;C:\Users\Asus\.cargo\bin;D:\GnuWin32\bin;C:\Program Files (x86)\Google\Chrome\Driver;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Kubernetes\Minikube;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs\;C:\Program Files\Microsoft Network Monitor 3\;C:\Program Files\Docker Toolbox;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\Hostx64\x64;C:\Users\Asus\Documents\Projects\work\trading_servive_group\ui\node_modules\.bin;C:\Program Files\Python38\Scripts\;C:\Program Files\Python38\;C:\Program Files\Microsoft MPI\Bin\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Bitvise SSH Client;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\CMake
PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW
PROCESSOR_ARCHITECTURE: AMD64
PROCESSOR_IDENTIFIER: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
PROCESSOR_LEVEL: 6
PROCESSOR_REVISION: 9e0a
PROFILE: debug
PROGRAMDATA: C:\ProgramData
PROGRAMFILES: C:\Program Files
PROGRAMFILES(X86): C:\Program Files (x86)
PROGRAMW6432: C:\Program Files
PSMODULEPATH: ;C:\Users\Asus\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\PowerShell
PUBLIC: C:\Users\Public
PYTHONUTF8: 1
RUSTC: rustc
RUSTDOC: rustdoc
RUSTUP_HOME: C:\Users\Asus\.rustup
RUSTUP_TOOLCHAIN: nightly-x86_64-pc-windows-gnu
RUST_BACKTRACE: short
RUST_RECURSION_COUNT: 1
SESSIONNAME: Console
SYSTEMDRIVE: C:
SYSTEMROOT: C:\WINDOWS
TARGET: x86_64-pc-windows-gnu
TEMP: C:\Users\Asus\AppData\Local\Temp
TERM: ansi
TMP: C:\Users\Asus\AppData\Local\Temp
USERDOMAIN: HECKAD
USERDOMAIN_ROAMINGPROFILE: HECKAD
USERNAME: Asus
USERPROFILE: C:\Users\Asus
VBOX_MSI_INSTALL_PATH: C:\Program Files\Oracle\VirtualBox\
VS140COMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
WINDIR: C:\WINDOWS
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CC_x86_64-pc-windows-gnu = None
CC_x86_64_pc_windows_gnu = None
HOST_CC = None
CC = None
CFLAGS_x86_64-pc-windows-gnu = None
CFLAGS_x86_64_pc_windows_gnu = None
HOST_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("true")
CARGO_CFG_TARGET_FEATURE = Some("fxsr,mmx,sse,sse2")
running "gcc.exe" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "include" "-Wall" "-Wextra" "-std=c1x" "-Wbad-function-cast" "-Wmissing-prototypes" "-Wnested-externs" "-Wstrict-prototypes" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-declarations" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-Wno-cast-align" "-g3" "-D_XOPEN_SOURCE=700" "-c" "-oC:\\Users\\Asus\\Documents\\Projects\\rust\\python_questions_website\\target\\debug\\build\\ring-02b6371541a14225\\out\\aes.o" "crypto/fipsmodule/aes/aes.c"

--- stderr
thread 'main' panicked at 'failed to execute ["gcc.exe" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "include" "-Wall" "-Wextra" "-std=c1x" "-Wbad-function-cast" "-Wmissing-prototypes" "-Wnested-externs" "-Wstrict-prototypes" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-declarations" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-Wno-cast-align" "-g3" "-D_XOPEN_SOURCE=700" "-c" "-oC:\\Users\\Asus\\Documents\\Projects\\rust\\python_questions_website\\target\\debug\\build\\ring-02b6371541a14225\\out\\aes.o" "crypto/fipsmodule/aes/aes.c"]: Не удается найти указанный файл. (os error 2)', C:\Users\Asus\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.13.5\build.rs:642:9
stack backtrace:
   0: backtrace::backtrace::dbghelp::trace
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace/dbghelp.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src\libstd\sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src\libstd\sys_common/backtrace.rs:59
   4: core::fmt::write
             at src\libcore\fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src\libstd\io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src\libstd\sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src\libstd\sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src\libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src\libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src\libstd/panicking.rs:472
  11: rust_begin_unwind
             at src\libstd/panicking.rs:380
  12: std::panicking::begin_panic_fmt
             at src\libstd/panicking.rs:334
  13: build_script_build::run_command::{{closure}}
             at .\build.rs:642
  14: core::result::Result<T,E>::unwrap_or_else
             at /rustc/41f41b2354778375dc72f7ed1d9323626580dc4d\src\libcore/result.rs:847
  15: build_script_build::run_command
             at .\build.rs:641
  16: build_script_build::compile
             at .\build.rs:522
  17: build_script_build::build_library::{{closure}}
             at .\build.rs:460
  18: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/41f41b2354778375dc72f7ed1d9323626580dc4d\src\libcore\ops/function.rs:285
  19: core::option::Option<T>::map
             at /rustc/41f41b2354778375dc72f7ed1d9323626580dc4d\src\libcore/option.rs:449
  20: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/41f41b2354778375dc72f7ed1d9323626580dc4d\src\libcore\iter\adapters/mod.rs:791
  21: alloc::vec::Vec<T>::extend_desugared
             at /rustc/41f41b2354778375dc72f7ed1d9323626580dc4d\src\liballoc/vec.rs:2131
  22: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend
             at /rustc/41f41b2354778375dc72f7ed1d9323626580dc4d\src\liballoc/vec.rs:2024
  23: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
             at /rustc/41f41b2354778375dc72f7ed1d9323626580dc4d\src\liballoc/vec.rs:2019
  24: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/41f41b2354778375dc72f7ed1d9323626580dc4d\src\liballoc/vec.rs:1919
  25: core::iter::traits::iterator::Iterator::collect
             at /rustc/41f41b2354778375dc72f7ed1d9323626580dc4d\src\libcore\iter\traits/iterator.rs:1558
  26: build_script_build::build_library
             at .\build.rs:456
  27: build_script_build::build_c_code::{{closure}}
             at .\build.rs:433
  28: core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at /rustc/41f41b2354778375dc72f7ed1d9323626580dc4d\src\libcore\iter\traits/iterator.rs:652
  29: core::iter::traits::iterator::Iterator::fold::ok::{{closure}}
             at /rustc/41f41b2354778375dc72f7ed1d9323626580dc4d\src\libcore\iter\traits/iterator.rs:1900
  30: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/41f41b2354778375dc72f7ed1d9323626580dc4d\src\libcore\iter\traits/iterator.rs:1776
  31: core::iter::traits::iterator::Iterator::fold
             at /rustc/41f41b2354778375dc72f7ed1d9323626580dc4d\src\libcore\iter\traits/iterator.rs:1903
  32: core::iter::traits::iterator::Iterator::for_each
             at /rustc/41f41b2354778375dc72f7ed1d9323626580dc4d\src\libcore\iter\traits/iterator.rs:655
  33: build_script_build::build_c_code
             at .\build.rs:431
  34: build_script_build::ring_build_rs_main
             at .\build.rs:301
  35: build_script_build::main
             at .\build.rs:263
  36: std::rt::lang_start::{{closure}}
             at /rustc/41f41b2354778375dc72f7ed1d9323626580dc4d\src\libstd/rt.rs:67
  37: std::rt::lang_start_internal::{{closure}}
             at src\libstd/rt.rs:52
  38: std::panicking::try::do_call
             at src\libstd/panicking.rs:305
  39: __rust_maybe_catch_panic
             at src\libpanic_unwind/lib.rs:86
  40: std::panicking::try
             at src\libstd/panicking.rs:281
  41: std::panic::catch_unwind
             at src\libstd/panic.rs:394
  42: std::rt::lang_start_internal
             at src\libstd/rt.rs:51
  43: std::rt::lang_start
             at /rustc/41f41b2354778375dc72f7ed1d9323626580dc4d\src\libstd/rt.rs:67
  44: main
  45: _tmainCRTStartup
  46: mainCRTStartup
  47: unit_addrs_search
  48: unit_addrs_search
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by LingMan** [comment] 2020-01-25 14:13
`error: failed to run custom build command for `ring v0.13.5``
That version is well over a year old. Does the same happen with master or even the current 0.16.9?

**Comment by briansmith** [comment] 2020-01-25 15:54
> `error: failed to run custom build command for ring v0.13.5`
> That version is well over a year old. Does the same happen with master or even the current 0.16.9?

Yes, please reproduce with the latest version.

Also, what version of GCC are you using?

**Comment by heckad** [comment] 2020-01-25 16:24
I tried to build [`rocket`](https://rocket.rs/v0.4/guide/quickstart/) project and this version bind with the latest version of the rocket. 

GCC version 8.1.0

**Comment by briansmith** [comment] 2020-01-28 16:41
> I tried to build [`rocket`](https://rocket.rs/v0.4/guide/quickstart/) project, and it's latest version bind with the v0.13.5 version of `ring`.

OK, I'm going to close this, since I only support 0.16.9+ right now. Rocket should upgrade to a supported version.

**Closed by briansmith** 2020-01-28 16:41 UTC
