### ISSUE TITLE
SHA-1 is slower than system sha1sum

### ISSUE THREAD

**Issue by glandium** [briansmith/ring#410] opened 2017-01-13 03:04 UTC
I was measuring the speed of the sha1 crate, and found that it's much slower than the sha1sum program one can find on Linux distros, which I'm not even sure is the fastest one can find. I ran the same test with ring, and while it appears to fare better than the sha1 crate, it's not on par with sha1sum.

However, it blasts sha256sum, sha384sum and sha512sum.

Here are the stats I got from running a small testcase, derived from the one I pasted in https://github.com/mitsuhiko/rust-sha1/issues/18 , with a 800+MB file:
```
sha1sum program: 518.83 MB/s
ring crate SHA-1: 276.76 MB/s
sha256sum program: 209.08 MB/s
ring crate SHA-256: 452.28 MB/s
sha384sum program: 332.02 MB/s
ring crate SHA-384: 667.66 MB/s
sha512sum program: 331.34 MB/s
ring crate SHA-512: 675.10 MB/s
```

I understand that SHA1 is deprecated, but there are still usecases for it, and it would be better if those could be fulfilled with a fast implementation.

**Comment by briansmith** [comment] 2017-01-13 06:23
Which specific use cases?

**Comment by glandium** [comment] 2017-01-13 06:35
git, to give just one.

**Comment by briansmith** [comment] 2017-01-13 06:41
If some *ring*-using Git application shares a benchmark where a useful, frequently-used, latency-sensitive operation is shown to be meaningfully faster using the x86-64 asm implementation, we can resurrect the x86-64 asm code for it.

**Comment by briansmith** [comment] 2017-02-01 01:09
I'm going to close this as "works as intended." We're purposely not trying to help people implement sha1sum. Like I mentioned above, if there is a benchmark that shows a more interesting application like Git is significantly affected by the performance, we'll consider fixing it.

**Closed by briansmith** 2017-02-01 01:09 UTC
