### ISSUE TITLE
no such instruction: adoxq, adcxq, mulxq, etc.

### ISSUE THREAD

**Issue by lilydjwg** [briansmith/ring#689] opened 2018-08-15 05:53 UTC
I get these errors when compiling:

```
ring-0.13.2/pregenerated/x86_64-mont-elf.S:1129: Error: no such instruction: `
adoxq %r15,%r11'
....
```

It seems to be because the CPU `Intel(R) Xeon(R) CPU E5-2407 0 @ 2.20GHz` doesn't have the adx flag.

**Comment by briansmith** [comment] 2018-08-16 18:52
Is it possible that your version of gcc and/or binutils is too old? Are you using GCC 4.7 or later?

**Comment by lilydjwg** [comment] 2018-08-17 07:45
Yes, they are old: gcc is 4.4.7 and binutils is 2.20.51.0.2. It's a CentOS 6 system. Is this system not supported?

**Comment by crusty-dave** [comment] 2018-09-27 05:36
ring-0.13.2 on Ubuntu has the same problem, is there a solution?

Is anyone working on being able to build with clang instead of gnu?

```
lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                10
On-line CPU(s) list:   0-9
Thread(s) per core:    1
Core(s) per socket:    10
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 42
Stepping:              1
CPU MHz:               2294.686
BogoMIPS:              4589.37
Virtualization:        VT-x
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
NUMA node0 CPU(s):     0-9
```

```
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 4.6.3-1ubuntu5' --with-bugurl=file:///usr/share/doc/gcc-4.6/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.6 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.6 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --disable-werror --with-arch-32=i686 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) 
```

```
ld -v
GNU ld (GNU Binutils for Ubuntu) 2.22
```

**Comment by crusty-dave** [comment] 2018-09-27 06:42
I am running Ubuntu 16.04 on WSL, so I am going to try installing clang-4.0 which will pull in binutils 2.26

**Comment by crusty-dave** [comment] 2018-09-27 07:48
OK, ring builds on Ubuntu 16.04 with the following toolchains:

```
ld -V
GNU ld (GNU Binutils for Ubuntu) 2.26.1
  Supported emulations:
   elf_x86_64
   elf32_x86_64
   elf_i386
   elf_iamcu
   i386linux
   elf_l1om
   elf_k1om
   i386pep
   i386pe

clang -v
clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/6.0.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.0.0
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0
Candidate multilib: .;@m64
Selected multilib: .;@m64

```

**Comment by briansmith** [comment] 2018-10-05 01:16
If the issue is only the ADX instructions then the maybe we could ask upstream OpenSSL to make the code work for assemblers that are missing ADX support. Usually that would be done by hacking the PerlAsm translator.

Alternatively, if there is a Rust crate that exposes clang's assembler for use by build scripts, then we could depend on that crate for Linux builds.

**Comment by briansmith** [comment] 2018-10-05 01:30
This was reported already as #673. I'm closing this as a duplicate of that issue because the other issue documents a workaround.

**Closed by briansmith** 2018-10-05 01:30 UTC
