### ISSUE TITLE
Does not build on ppc64le

### ISSUE THREAD

**Issue by anengineer1** [briansmith/ring#1222] opened 2021-03-21 18:08 UTC
`Caused by:
  process didn't exit successfully: /home/yamira/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/target/debug/build/ring-af74af5a84c4e342/build-script-build (exit code: 101)
  --- stderr
  thread 'main' panicked at 'called 'Option::unwrap()' on a 'None value', build.rs:358:10
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
     1: core::panicking::panic_fmt
               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
     2: core::panicking::panic
               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:50:5
     3: core::option::Option<T>::unwrap
               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/option.rs:386:21
     4: build_script_build::build_c_code
               at ./build.rs:352:34
     5: build_script_build::ring_build_rs_main
               at ./build.rs:279:5
     6: build_script_build::main
               at ./build.rs:240:13
     7: core::ops::function::FnOnce::call_once
               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/ops/function.rs:227:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.`

I also ran it with full backtrace in case it helps more:

`Caused by:
  process didn't exit successfully: '/home/yamira/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/target/debug/build/ring-af74af5a84c4e342/build-script-build' (exit code: 101)
  --- stderr
  thread 'main' panicked at 'called 'Option::unwrap()' on a 'None value', build.rs:358:10
  stack backtrace:
     0:       0xfb59f8cdac - std::backtrace_rs::backtrace::libunwind::trace::h7f0da5021228b9e6
                                 at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
     1:       0xfb59f8cdac - std::backtrace_rs::backtrace::trace_unsynchronized::h682efff1d985fe48
                                 at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:       0xfb59f8cdac - std::sys_common::backtrace::_print_fmt::hcc5fe2d584084ec9
                                 at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:67:5
     3:       0xfb59f8cdac - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h95dad73aa44f3fd4
                                 at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:46:22
     4:       0xfb59fc3ef4 - core::fmt::write::ha2eff7aa810eebbe
                                 at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/fmt/mod.rs:1078:17
     5:       0xfb59f864f4 - std::io::Write::write_fmt::h71fe16a670755101
                                 at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/io/mod.rs:1517:15
     6:       0xfb59f90068 - std::sys_common::backtrace::_print::h56abfe37c9153cc0
                                 at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:49:5
     7:       0xfb59f90068 - std::sys_common::backtrace::print::hcd9ed52fa2c699c7
                                 at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:36:9
     8:       0xfb59f90068 - std::panicking::default_hook::{{closure}}::hf90c3192f4397f72
                                 at /rustc/cb75ad5db027 \`83e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:208:50
     9:       0xfb59f8fa74 - std::panicking::default_hook::h26bf94ae2d372d62
                                 at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:225:9
    10:       0xfb59f90bf0 - std::panicking::rust_panic_with_hook::hc7cdf1c6424727d4
                                 at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:591:17
    11:       0xfb59f904b0 - std::panicking::begin_panic_handler::{{closure}}::hd7e810fe7c5bf4c0
                                 at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:495:13
    12:       0xfb59f8d400 - std::sys_common::backtrace::__rust_end_short_backtrace::h7808ce2079587a52
                                 at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:141:18
    13:       0xfb59f9040c - rust_begin_unwind
                                 at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
    14:       0xfb59fc069c - core::panicking::panic_fmt::h4b5496de4069501a
                                 at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
    15:       0xfb59fc05b0 - core::panicking::panic::h966511542b6275e3
                                 at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:50:5
    16:       0xfb59ef43dc - core::option::Option<T>::unwrap::h691147767d6f008e
                                 at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/option.rs:386:21
    17:       0xfb59eef698 - build_script_build::build_c_code::ha00ecba7caf6048c
                                 at /home/yamira/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/build.rs:352:34
    18:       0xfb59eeebf4 - build_script_build::ring_build_rs_main::h7adf52552a8480b9
                                 at /home/yamira/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/build.rs:279:5
    19:       0xfb59eee63c - build_script_build::main::h3502e6b10368899f
                                 at /home/yamira/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/build.rs:240:13
    20:       0xfb59ee645c - core::ops::function::FnOnce::call_once::hc4fafe55ebf6b3a1
                                 at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/ops/function.rs:227:5
    21:       0xfb59edd35c - std::sys_common::backtrace::__rust_begin_short_backtrace::hda298a1406941326
                                 at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:125:18
    22:       0xfb59eeb3f0 - std::rt::lang_start::{{closure}}::hc117e600d49a7f98
                                 at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/rt.rs:66:18
    23:       0xfb59f910b0 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hfed37f712be0e542
                                 at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/ops/function.rs:259:13
    24:       0xfb59f910b0 - std::panicking::try::do_call::h1d5dbc402941246d
                                 at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:379:40
    25:       0xfb59f910b0 - std::panicking::try::hb8fa9e78fd60a1e4
                                 at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:343:19
    26:       0xfb59f910b0 - std::panic::catch_unwind::h158872802db7a267
                                 at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panic.rs:396:14
    27:       0xfb59f910b0 - std::rt::lang_start_internal::h670aa132e113da47
                                 at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/rt.rs:51:25
    28:       0xfb59eeb39c - std::rt::lang_start::h09acefab99966462
                                 at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/rt.rs:65:5
    29:       0xfb59ef3270 - main
    30:     0x3f201c303cdc - generic_start_main
                                 at /builddir/glibc-2.32/csu/../csu/libc-start.c:314:16
    31:     0x3f201c303ec0 - __libc_start_main
                                 at /builddir/glibc-2.32/csu/../sysdeps/unix/sysv/linux/powerpc/libc-start.c:98:10
    32:                0x0 - <unknown>\`

**Comment by andrewtj** [comment] 2021-03-21 20:37
Have you seen #389?

**Comment by briansmith** [comment] 2021-03-23 17:11
Closing as a dupe of #389.

**Closed by briansmith** 2021-03-23 17:11 UTC

**Comment by anengineer1** [comment] 2021-03-23 17:42
my apologies I will be more thotough on my searchs from now on!

Take care
