### ISSUE TITLE
Cross Compiling from x86_64-unknown-linux-gnu to x86_64-pc-windows-gnu

### ISSUE THREAD

**Issue by tiagolobocastro** [briansmith/ring#1451] opened 2022-01-15 01:34 UTC
Hi,

When cross compiling a simple library that pulls in rustls (0.20.2)  from x86_64-unknown-linux-gnu to x86_64-pc-windows-gnu I get an error when linking that is related to ring:

```
error: linking with `/nix/store/naazmcwxidyy9iap0w77lkrqbfwirznk-x86_64-w64-mingw32-clang-wrapper-12.0.1/bin/x86_64-w64-mingw32-cc` failed: exit status: 1
  |
  = note: "/nix/store/naazmcwxidyy9iap0w77lkrqbfwirznk-x86_64-w64-mingw32-clang-wrapper-12.0.1/bin/x86_64-w64-mingw32-cc" "-fno-use-linker-plugin" "-Wl,--dynamicbase" "-Wl,--disable-auto-image-base" "-m64" "-Wl,--high-entropy-va" "-Wl,--nxcompat" "/nix/store/n5crx5mc0b39cm1hs7xnl48clqjf8jm4-rust-default-1.53.0/lib/rustlib/x86_64-pc-windows-gnu/lib/rsbegin.o" "-L" "/nix/store/n5crx5mc0b39cm1hs7xnl48clqjf8jm4-rust-default-1.53.0/lib/rustlib/x86_64-pc-windows-gnu/lib" "/build/chief/out/x86_64-pc-windows-gnu/debug/deps/windows-ced8aae052f0165b.windows.278ce2ys-cgu.0.rcgu.o" "/build/chief/out/x86_64-pc-windows-gnu/debug/deps/windows-ced8aae052f0165b.windows.278ce2ys-cgu.1.rcgu.o" "/build/chief/out/x86_64-pc-windows-gnu/debug/deps/windows-ced8aae052f0165b.windows.278ce2ys-cgu.2.rcgu.o" "/build/chief/out/x86_64-pc-windows-gnu/debug/deps/windows-ced8aae052f0165b.windows.278ce2ys-cgu.3.rcgu.o" "/build/chief/out/x86_64-pc-windows-gnu/debug/deps/windows-ced8aae052f0165b.windows.278ce2ys-cgu.4.rcgu.o" "/build/chief/out/x86_64-pc-windows-gnu/debug/deps/windows-ced8aae052f0165b.windows.278ce2ys-cgu.5.rcgu.o" "/build/chief/out/x86_64-pc-windows-gnu/debug/deps/windows-ced8aae052f0165b.windows.278ce2ys-cgu.6.rcgu.o" "-o" "/build/chief/out/x86_64-pc-windows-gnu/debug/deps/windows-ced8aae052f0165b.exe" "/build/chief/out/x86_64-pc-windows-gnu/debug/deps/windows-ced8aae052f0165b.1qppk7kfqasrajn4.rcgu.o" "-Wl,--gc-sections" "-nodefaultlibs" "-L" "/build/chief/out/x86_64-pc-windows-gnu/debug/deps" "-L" "/build/chief/out/debug/deps" "-L" "/nix/store/n5crx5mc0b39cm1hs7xnl48clqjf8jm4-rust-default-1.53.0/lib" "-L" "/nix/store/lk3sjjczw27p37nd4xhsfdy2j8an0xj0-jq-1.6-lib/lib" "-L" "/nix/store/lk3sjjczw27p37nd4xhsfdy2j8an0xj0-jq-1.6-lib/lib" "-L" "/nix/store/l3s53c0s6d5jb2c5ga8fz25sg39wv96w-mingw-w64-x86_64-w64-mingw32-9.0.0-pthreads-x86_64-w64-mingw32/lib" "-L" "/nix/store/l3s53c0s6d5jb2c5ga8fz25sg39wv96w-mingw-w64-x86_64-w64-mingw32-9.0.0-pthreads-x86_64-w64-mingw32/lib" "-L" "/nix/store/a4j4xj6jsaiqsalqqjkr0jhz604g4g2x-pthreads-w32-x86_64-w64-mingw32-2.9.1/lib" "-L" "/nix/store/a4j4xj6jsaiqsalqqjkr0jhz604g4g2x-pthreads-w32-x86_64-w64-mingw32-2.9.1/lib" "-L" "/nix/store/n5crx5mc0b39cm1hs7xnl48clqjf8jm4-rust-default-1.53.0/lib" "-L" "/nix/store/n5crx5mc0b39cm1hs7xnl48clqjf8jm4-rust-default-1.53.0/lib" "-L" "/nix/store/lk3sjjczw27p37nd4xhsfdy2j8an0xj0-jq-1.6-lib/lib" "-L" "/nix/store/lk3sjjczw27p37nd4xhsfdy2j8an0xj0-jq-1.6-lib/lib" "-L" "/nix/store/l3s53c0s6d5jb2c5ga8fz25sg39wv96w-mingw-w64-x86_64-w64-mingw32-9.0.0-pthreads-x86_64-w64-mingw32/lib" "-L" "/nix/store/l3s53c0s6d5jb2c5ga8fz25sg39wv96w-mingw-w64-x86_64-w64-mingw32-9.0.0-pthreads-x86_64-w64-mingw32/lib" "-L" "/nix/store/a4j4xj6jsaiqsalqqjkr0jhz604g4g2x-pthreads-w32-x86_64-w64-mingw32-2.9.1/lib" "-L" "/nix/store/a4j4xj6jsaiqsalqqjkr0jhz604g4g2x-pthreads-w32-x86_64-w64-mingw32-2.9.1/lib" "-L" "/build/chief/out/x86_64-pc-windows-gnu/debug/build/ring-e48a03f26dc57e37/out" "-L" "/nix/store/qmm63qq941rcwza4fbx8x9x46l3wp3va-crates-io/winapi-x86_64-pc-windows-gnu-0.4.0/lib" "-L" "/nix/store/n5crx5mc0b39cm1hs7xnl48clqjf8jm4-rust-default-1.53.0/lib/rustlib/x86_64-pc-windows-gnu/lib" "-Wl,-Bstatic" "/build/chief/out/x86_64-pc-windows-gnu/debug/deps/librustls-949d0d48ea41e208.rlib" "/build/chief/out/x86_64-pc-windows-gnu/debug/deps/libsct-0e1341e021a1fd31.rlib" "/build/chief/out/x86_64-pc-windows-gnu/debug/deps/libwebpki-10803a816423ad08.rlib" "/build/chief/out/x86_64-pc-windows-gnu/debug/deps/libring-63c531a041865fa0.rlib" "/build/chief/out/x86_64-pc-windows-gnu/debug/deps/libspin-cbbc91977dd22c3e.rlib" "/build/chief/out/x86_64-pc-windows-gnu/debug/deps/libuntrusted-b4b2bf86128f2285.rlib" "/build/chief/out/x86_64-pc-windows-gnu/debug/deps/libwinapi-53952dc860a443a6.rlib" "/build/chief/out/x86_64-pc-windows-gnu/debug/deps/liblog-0fc004ad7db0fcc0.rlib" "/build/chief/out/x86_64-pc-windows-gnu/debug/deps/libcfg_if-8d3af7a565990b8c.rlib" "-Wl,--start-group" "/nix/store/rv0a1nm9cakrk4z61wxjklwkaisdcsar-rust-std-1.53.0/lib/rustlib/x86_64-pc-windows-gnu/lib/libstd-fd55ee3d3a94e250.rlib" "/nix/store/rv0a1nm9cakrk4z61wxjklwkaisdcsar-rust-std-1.53.0/lib/rustlib/x86_64-pc-windows-gnu/lib/libpanic_abort-5133a82c4da9bc63.rlib" "/nix/store/rv0a1nm9cakrk4z61wxjklwkaisdcsar-rust-std-1.53.0/lib/rustlib/x86_64-pc-windows-gnu/lib/libobject-dd5d3577818ca454.rlib" "/nix/store/rv0a1nm9cakrk4z61wxjklwkaisdcsar-rust-std-1.53.0/lib/rustlib/x86_64-pc-windows-gnu/lib/libaddr2line-765f86da5fd3a5dd.rlib" "/nix/store/rv0a1nm9cakrk4z61wxjklwkaisdcsar-rust-std-1.53.0/lib/rustlib/x86_64-pc-windows-gnu/lib/libgimli-8c95dc6d40504aae.rlib" "/nix/store/rv0a1nm9cakrk4z61wxjklwkaisdcsar-rust-std-1.53.0/lib/rustlib/x86_64-pc-windows-gnu/lib/libstd_detect-96809e08edf0bd5c.rlib" "/nix/store/rv0a1nm9cakrk4z61wxjklwkaisdcsar-rust-std-1.53.0/lib/rustlib/x86_64-pc-windows-gnu/lib/librustc_demangle-ccb97c75f9cda6f4.rlib" "/nix/store/rv0a1nm9cakrk4z61wxjklwkaisdcsar-rust-std-1.53.0/lib/rustlib/x86_64-pc-windows-gnu/lib/libhashbrown-4e1bc8a6ee521048.rlib" "/nix/store/rv0a1nm9cakrk4z61wxjklwkaisdcsar-rust-std-1.53.0/lib/rustlib/x86_64-pc-windows-gnu/lib/librustc_std_workspace_alloc-1fc9001eeb2a3308.rlib" "/nix/store/rv0a1nm9cakrk4z61wxjklwkaisdcsar-rust-std-1.53.0/lib/rustlib/x86_64-pc-windows-gnu/lib/libunwind-0c88b4178a59c981.rlib" "/nix/store/rv0a1nm9cakrk4z61wxjklwkaisdcsar-rust-std-1.53.0/lib/rustlib/x86_64-pc-windows-gnu/lib/libcfg_if-c8dd50c1ab9b223c.rlib" "/nix/store/rv0a1nm9cakrk4z61wxjklwkaisdcsar-rust-std-1.53.0/lib/rustlib/x86_64-pc-windows-gnu/lib/liblibc-356ab79e0ba5ac08.rlib" "/nix/store/rv0a1nm9cakrk4z61wxjklwkaisdcsar-rust-std-1.53.0/lib/rustlib/x86_64-pc-windows-gnu/lib/liballoc-5e8cdcafbc9e5594.rlib" "/nix/store/rv0a1nm9cakrk4z61wxjklwkaisdcsar-rust-std-1.53.0/lib/rustlib/x86_64-pc-windows-gnu/lib/librustc_std_workspace_core-4609944e229e275c.rlib" "/nix/store/rv0a1nm9cakrk4z61wxjklwkaisdcsar-rust-std-1.53.0/lib/rustlib/x86_64-pc-windows-gnu/lib/libcore-6b9d36f25f521ae9.rlib" "-Wl,--end-group" "/nix/store/rv0a1nm9cakrk4z61wxjklwkaisdcsar-rust-std-1.53.0/lib/rustlib/x86_64-pc-windows-gnu/lib/libcompiler_builtins-9e865fe37e5c5e07.rlib" "-Wl,-Bdynamic" "-lwinapi_advapi32" "-lwinapi_credui" "-lwinapi_kernel32" "-lwinapi_secur32" "-ladvapi32" "-lws2_32" "-luserenv" "-L/nix/store/n5crx5mc0b39cm1hs7xnl48clqjf8jm4-rust-default-1.53.0/lib" "-lgcc_eh" "-l:libpthread.a" "-lmsvcrt" "-lmingwex" "-lmingw32" "-lgcc" "-lmsvcrt" "-luser32" "-lkernel32" "/nix/store/n5crx5mc0b39cm1hs7xnl48clqjf8jm4-rust-default-1.53.0/lib/rustlib/x86_64-pc-windows-gnu/lib/rsend.o"
  = note: /nix/store/wa52bmw62lbzkbjbf2mhkn5y38xczas2-x86_64-w64-mingw32-binutils-2.35.1/bin/x86_64-w64-mingw32-ld: /build/chief/out/x86_64-pc-windows-gnu/debug/deps/libring-63c531a041865fa0.rlib(ring-63c531a041865fa0.ring.4s52g1qr-cgu.11.rcgu.o): in function `ring::cpu::features::{{closure}}':
          /nix/store/qmm63qq941rcwza4fbx8x9x46l3wp3va-crates-io/ring-0.16.20/src/cpu.rs:46: 
undefined reference to `GFp_cpuid_setup'
          /nix/store/wa52bmw62lbzkbjbf2mhkn5y38xczas2-x86_64-w64-mingw32-binutils-2.35.1/bin/x86_64-w64-mingw32-ld: /build/chief/out/x86_64-pc-windows-gnu/debug/deps/libring-63c531a041865fa0.rlib(ring-63c531a041865fa0.ring.4s52g1qr-cgu.11.rcgu.o): in function `ring::ec::suite_b::ops::p256::p256_point_mul_base_impl':
          /nix/store/qmm63qq941rcwza4fbx8x9x46l3wp3va-crates-io/ring-0.16.20/src/ec/suite_b/ops/p256.rs:142: 
undefined reference to `GFp_nistz256_point_mul_base'
          /nix/store/wa52bmw62lbzkbjbf2mhkn5y38xczas2-x86_64-w64-mingw32-binutils-2.35.1/bin/x86_64-w64-mingw32-ld: /build/chief/out/x86_64-pc-windows-gnu/debug/deps/libring-63c531a041865fa0.rlib(ring-63c531a041865fa0.ring.4s52g1qr-cgu.11.rcgu.o): in function `ring::ec::suite_b::ops::p256::p256_scalar_inv_to_mont::sqr':
          /nix/store/qmm63qq941rcwza4fbx8x9x46l3wp3va-crates-io/ring-0.16.20/src/ec/suite_b/ops/p256.rs:232: 
undefined reference to `GFp_p256_scalar_sqr_mont'
          /nix/store/wa52bmw62lbzkbjbf2mhkn5y38xczas2-x86_64-w64-mingw32-binutils-2.35.1/bin/x86_64-w64-mingw32-ld: /build/chief/out/x86_64-pc-windows-gnu/debug/deps/libring-63c531a041865fa0.rlib(ring-63c531a041865fa0.ring.4s52g1qr-cgu.11.rcgu.o): in function `ring::ec::suite_b::ops::PrivateKeyOps::point_mul':
          /nix/store/qmm63qq941rcwza4fbx8x9x46l3wp3va-crates-io/ring-0.16.20/src/ec/suite_b/ops.rs:188: 
undefined reference to `GFp_nistz384_point_mul'
          /nix/store/wa52bmw62lbzkbjbf2mhkn5y38xczas2-x86_64-w64-mingw32-binutils-2.35.1/bin/x86_64-w64-mingw32-ld: /build/chief/out/x86_64-pc-windows-gnu/debug/deps/libring-63c531a041865fa0.rlib(ring-63c531a041865fa0.ring.4s52g1qr-cgu.11.rcgu.o): in function `ring::ec::suite_b::ops::p384::p384_scalar_inv_to_mont::mul':
          /nix/store/qmm63qq941rcwza4fbx8x9x46l3wp3va-crates-io/ring-0.16.20/src/ec/suite_b/ops/p384.rs:205: 
undefined reference to `GFp_p384_scalar_mul_mont'
          /nix/store/wa52bmw62lbzkbjbf2mhkn5y38xczas2-x86_64-w64-mingw32-binutils-2.35.1/bin/x86_64-w64-mingw32-ld: /build/chief/out/x86_64-pc-windows-gnu/debug/deps/libring-63c531a041865fa0.rlib(ring-63c531a041865fa0.ring.4s52g1qr-cgu.11.rcgu.o): in function `ring::ec::suite_b::ops::p384::p384_scalar_inv_to_mont::sqr':
          /nix/store/qmm63qq941rcwza4fbx8x9x46l3wp3va-crates-io/ring-0.16.20/src/ec/suite_b/ops/p384.rs:209:
 undefined reference to `GFp_p384_scalar_mul_mont'
          /nix/store/wa52bmw62lbzkbjbf2mhkn5y38xczas2-x86_64-w64-mingw32-binutils-2.35.1/bin/x86_64-w64-mingw32-ld: /build/chief/out/x86_64-pc-windows-gnu/debug/deps/libring-63c531a041865fa0.rlib(ring-63c531a041865fa0.ring.4s52g1qr-cgu.11.rcgu.o): in function `ring::ec::suite_b::ops::p384::p384_scalar_inv_to_mont::sqr_mut':
          /nix/store/qmm63qq941rcwza4fbx8x9x46l3wp3va-crates-io/ring-0.16.20/src/ec/suite_b/ops/p384.rs:213: 
undefined reference to `GFp_p384_scalar_mul_mont'
          /nix/store/wa52bmw62lbzkbjbf2mhkn5y38xczas2-x86_64-w64-mingw32-binutils-2.35.1/bin/x86_64-w64-mingw32-ld: /build/chief/out/x86_64-pc-windows-gnu/debug/deps/libring-63c531a041865fa0.rlib(ring-63c531a041865fa0.ring.4s52g1qr-cgu.11.rcgu.o): in function `ring::ec::suite_b::ops::p384::p384_scalar_inv_to_mont::sqr_mul_acc':
          /nix/store/qmm63qq941rcwza4fbx8x9x46l3wp3va-crates-io/ring-0.16.20/src/ec/suite_b/ops/p384.rs:232: 
undefined reference to `GFp_p384_scalar_mul_mont'
          /nix/store/wa52bmw62lbzkbjbf2mhkn5y38xczas2-x86_64-w64-mingw32-binutils-2.35.1/bin/x86_64-w64-mingw32-ld: /build/chief/out/x86_64-pc-windows-gnu/debug/deps/libring-63c531a041865fa0.rlib(ring-63c531a041865fa0.ring.4s52g1qr-cgu.11.rcgu.o): in function `ring::ec::suite_b::ops::p384::p384_scalar_inv_to_mont::to_mont':
          /nix/store/qmm63qq941rcwza4fbx8x9x46l3wp3va-crates-io/ring-0.16.20/src/ec/suite_b/ops/p384.rs:241: 
undefined reference to `GFp_p384_scalar_mul_mont'
.........
```

Any clues at what could be going on?

Thanks

**Comment by briansmith** [comment] 2023-10-14 03:46
Closing as a duplicate of #1363. I recommend targeting -msvc anyway.

**Closed by briansmith** 2023-10-14 03:46 UTC
Labels: duplicate
