### ISSUE TITLE
`less-safe-getrandom-custom-or-rdrand` not working on target `x86_64-fortanix-unknown-sgx`

### ISSUE THREAD

**Issue by DragonDev1906** [briansmith/ring#2043] opened 2024-05-02 13:53 UTC
I'm not sure about the current state of support for this target (see #775), but I'm not sure if you know about this already, hence this issue:

The `x86_64-fortanix-unknown-sgx` target has `target_os = "unknown"` instead of `none` for some reason. This means that although ring compiles for this target there is no way to use ring with RDRAND. The following feature flag + line works for embedded devices but not in SGX.

```rust
all(feature = "less-safe-getrandom-custom-or-rdrand", target_os = "none"),
```

Thus `SystemRandom` can never implement `SecureRandom` on that target.

Also see [#744](https://github.com/briansmith/ring/issues/744#issuecomment-1756037111)

**Comment by briansmith** [comment] 2024-05-02 18:52
Closing this as a dupe of #775. I think now we're in a good position to do the SGX port, but it requires more work than getting  `ring::rand` to build.

**Closed by briansmith** 2024-05-02 18:52 UTC
