### ISSUE TITLE
Cannot parse RSA private keys generated with cfssl

### ISSUE THREAD

**Issue by joshlf** [briansmith/ring#635] opened 2018-03-12 08:13 UTC
When compiling with the `rsa_signing` feature, RSA keys that are produced by the [cfssl](https://github.com/cloudflare/cfssl/) tool fail to be parsed with `RSAKeyPair::from_pkcs8`.

Steps to reproduce:

- Run `echo '{"key":{"algo":"rsa","size":4096}}' | cfssl genkey - | cfssljson -bare cfssl` to generate an RSA private key with cfssl (the private key will be in `cfssl-key.pem`)
- Run `openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:4096 | openssl pkcs8 -topk8 -nocrypt -outform pem > openssl.key` to generate an RSA private key with openssl
- Run [this code](https://play.rust-lang.org/?gist=3de4d37f14fa2d50f71ef69364bbfedb&version=stable) with `ring`'s `rsa_signing` feature enabled (you can't run directly on the playground because of this requirement), and you will see that both `RSAKeyPair::from_der` and `RSAKeyPair::from_pkcs8` fail for the cfssl key while `from_pkcs8` succeeds for the openssl key

The example code tries both `from_der` and `from_pkcs8` because that's how it's done in [rustls (source code link)](https://github.com/ctz/rustls/blob/master/src/sign.rs#L155), and that's where I originally discovered this issue.

**Comment by farcaller** [comment] 2018-03-28 23:37
I've stumbled on this too while debugging https://github.com/databricks/click/issues/33. cfssl generates keys that have `p < q`, e.g. [this one](https://lapo.it/asn1js/#308209290201000282020100ABA40220031C52BF4A89636A9F7D4D1D299650FD9306DFE6250D388FA8DE02770DA87D8FAEDB29B29502305B039DF0E60BA7B8964A4A1FFA3982BD6FA771376E831E50763258297098B79A94CC6F7F8CA69C8E1EC6BEC02D4A82A48B869C18BEE2C629D090B20BC752EE95B4C42B52018F8C7CCB15A9F2B49C69FA804B5AECEAE317FE03D7B73FDE6981F11BA59A994C621DB7273BDB2BAD122E897ABEC603D8F281D229B953ED0230D1C9F9E24E38744EB20F04ADBDB0106E0F2F0943C26EE23466CA8F9C6EA1254F1B1051C1AFBC53A794015689E763DC032B81E8E052D4D607DB20E27F25BD8B92CB16853E34365EE1B9533DC654A7BD6530F16EBB8DED0FE85614E5461D81283B2DF20BFB5BE3CD0D1823F8F3B0CE920CFDF3FCF51D439BD391930C62A061520017A4E41E6F42384D0C94D974B7FB38CC94B325ED8859ADB5C300C62E30C631A89653F0649C142449986F3ECF484525132E5BF8AC1133B9318843451EEC2995CB64DC496CC00E481CA2B03E9D81947C1D1D1BED93670CC65FB95576802F13E281816BE96254476F1E421DED477048B3D2CF538D30A9CCCDC6B27BBACCC141CD2EC836143AD35C6161E2D77F6572A85031C0183D7FE49D64634AD0CED97C3984CB945830903EEBE7AA9C81DF850C9E51798DEC9C8E41146BF39116C4AA37A7DA8BF7862147057ACB8B9F184D42CC0EAC6743D8AC2F7640D302030100010282020026619B740B1E0746ED65018D3332F2CE85A12E6535BE80CCD71638C2AF314DFDCF591112D33801000520232E0706077B79B9BCA626E0A27BF2E650742A4E3FE5FF7E04E21969EB8259341D660EBD1419A09C3B8F9843C9779744D584B9CA28226F557EBE3BCD04A342E1452AD1FF19EC6D6C2DEFBFDD6BFF85469194A4C5255B7502C57398864ACAF26EF33A8A72A2BB18E9AA2E24CD62DBE5C7F0483966D02F7033258ADCFD6E6F61F957A000421B8FAE955494684195A066EC10499314647542E085854DA6D37423575AF3DD4AEDE30B0326B5724B02E28CF6EAAAE796BE2F4A3C6F0317099A741E943969FC39F2BA8EE14142FC19AC14C70F05BE0C44B570CE6986E70FE1C131E236DB4B66EDD1DB2A964E7B5B7A4C229440992D2B92B3872F83AB628728CC7CFB661B7AC6EADD1C6573671B2D8D4BD91AB10BEADCCAF796824B64EE42D086372B56D4841A1B0FB253B4B3DCA3CAFAA1DAA3E77B3FED1C5CEB542DAB7925806922C18EFB77170E3F654BA7148096ECAE08524745BCE675F7E581529A77B1F9D5E3A13FBA24B79D17FDABAABBE4DCF23388625E50406C865EA2199241D30D30542FCAE407E899581B5B48B41E5C3AD78C903BE45FA9578A6661765BED0C858529B025034ADFD42BD9B9AC7BD105AD2BFBE436C5D1E583773F0C49A997FEECC8751C8A04518F3F40A404A243419226D7CBF58CF38BD86EB4190282010100CB48767F2F55B7E7000331E058B7A487CB45421037F3F4F54A237B5E9388A4B5071FC0061C533FE63F28E3BA3988F5DB6F76EA676E72C3DFF7F166670558AC98C7587E762C3B94A30F9179DD761E9028A142F959F819C4F2C0B6123BE5A48CFA7998C6614F5FD71CC41628F838CDAA4A89D7D20A122939338DE870DEA32ABBDDF36DA10005D402C0DE73ED02469EB128C11B2EAF1863FCB068BBF59967ED9450649D024812E52B1D7974274D8CFC4F959C80FC681425F2AA39D30994283906D02E0D4EA9A57884D78AA591C21EE4C0B5D4A50673D6B0A0DE69AAFA0563F25FE72C19DC3C688DE59D687F0E2BC7F015D7EDFC2B82FB2C602F1C6CFC95605167CD0282010100D826DF6378F4CD0D415F71AE235CD704E54900BAB4682FF18BD3207E935539D93E0B5FA8D39017DE97D865A60497F824928B31462F472A69D16751EB009C2EF388A10F1D3B391C40398064254C2BB263D0991B1ABC99F1149EFC61DBCF346A56AE8DA1320528C281141DFC4CC83A328C04E0C45076F3B757C63E4CE73650C61D69FC6E668AA0E9F8319347BF7FE0AAE086E85B036D4EF01A7F5622FC474357B8787E08C5111D4631A767972C559A3F5AD92354493804EF83A11992DED5F6AC0C8CEB3E2230D7BE43683084C977FD4B6CFE04A9874A43041F0D88BD7096D0A8363FCB1D39E6C757F6719F44BB3F2B79F6205D86573541D78FA9BF34ACD4186B1F0282010100C83E4823BECFF448C3556253397124CC732A750A1EE3DC1FA7F94DB47B25F60130D450C6742E795A684AF210664E88C8B082F6220EC554379238A403C55B752145F4E115AD3ABF8EE46E0C1A6019792DDCB46985FB83FEE2957C8477A61DB295A5241DFE8B3EC05A60B9E77FA40CCBBB830F2AA2AB031A8AB3360DC0F1FFCD71B432008F522E66CBF01547999F5100F8414872731E5697FA7A20F4AC3998E9294C02F1D5676F814A167299A8A5C180EFC26BB8B71969CC216CB67AD00BD328E7F7053AC097F420FF655EF536C051DB9701B1D1AA5808435EF3BDED6D53E7D41A96F19E658F247FD3CFB4A093F5EE84C5E0732FB565906FEAD8586F73019F0EDD02820101008E5001B24F77F5EDAD45F6E5ED387A052A25078AE5AED72A14A27BF97A6D9979D3E4CF25ABAD6A59CEE5D5FF1975291683398BC6A6E8171FB6946D15E9BFEB15C2B62FEA520CC6F1EE29FF45A341FDE0C3FD9A1FDF5F07A04910E8293DE247C52C85E944B2AAE46CF1DED0378978EFC0CA91660F8851EC3BA9356992AD6B3F152CABDBD03DA3B68807B3ED8042E49BFCDA35EF7E712090EB113D98293B8E361A2992E9993E2C6503DA315512068659022A869D3EDBD83C0E112A724DAED80AECF47709E09F01DCAE2AD20F0B4AAA05580C62EB6F3CD0A4CD012F2F730A88F4C74AF72315F540F8443508E4CAD7CB7B30369CFD0F3BEC4ECDB2B846292837AF87028201000AE1F80289A71FE91F0E28F61F8BE1A3043BE769890D9C19444E02EAA4369315915E318AF9DC1780187910862297DBC7BC8EA7988F7E2DC605C5AC66C5D67D293F96E2E55754E66077B8640BCC5CDA078CB1F17DF7116EF5EA4044F118DE0BC0CC708CD9FFD66C6957051BE3944E4397A39AED53DA509BBB1C0E19C60526DA5791CE3C7C87213420E4F7BEC53F80240A75BA1E57F52947319E15BEFA37EC33EB14E9AA0A1057DB9DAB1BEDCCE282F5BFFD3F3F95C754495A6C9A10D5660684E84380215BBF06F13678F294D17AC7BD9A3275930E16CC405271994F0A07A8FE53B4D87D17F2AA597959DB891392E312F065E27F9BAAFDD5E32DEB4AE0073853A8).

**Comment by joshlf** [comment] 2018-03-28 23:39
Oh fascinating. If `p > q`, but otherwise the encoding is the same, does it parse properly? Have you tried? The reason I ask is that I spent some time tracing through the code and I figured out that it was very likely a parsing issue (cfssl generates DER structures differently from openssl), but it wasn't definitive enough that I felt confident posting it here in case it was misleading.

**Comment by farcaller** [comment] 2018-03-28 23:40
I'd say that this is exactly the case when `error::Unspecified` should have had more details; specifically stating that it's a problem of ring itself, not the payload it tries to process.

**Comment by farcaller** [comment] 2018-03-28 23:42
> Oh fascinating. If p > q, but otherwise the encoding is the same, does it parse properly?

I've traced the run up to `try!(q.verify_less_than(&p))` failing. I don't think I can just mingle p to be > q and expect the key to still be valid — but it does work with p < q cases so this is clearly one of the problems.

**Comment by joshlf** [comment] 2018-03-28 23:49
I don't have everything set up to test this right now, but if I've traced the code properly, you should be able to add some logic at [this line](https://github.com/cloudflare/cfssl/blob/master/csr/csr.go#L207) in cfssl to ensure that `p > q`.

**Comment by briansmith** [comment] 2018-03-28 23:50
Thanks for investigating this. I'm going to close this as a dupe of #220 and I'll review that PR as soon as I have some free time.

**Closed by briansmith** 2018-03-28 23:50 UTC

**Comment by joshlf** [comment] 2018-03-29 00:05
OK, I've confirmed that this seems to be the issue. When I run the original code, it outputs:

```text
cfssl der: false
cfssl pkcs8: false
openssl der: false
openssl pkcs8: true
```

When I modify cfssl to ensure that `p > q`, generate a new key, and run the code again, I get:

```text
cfssl der: true
cfssl pkcs8: true
openssl der: false
openssl pkcs8: true
```
