### ISSUE TITLE
When I use ring on WASM: Error came out with 'Missing import: `env`.`ring_core_0_17_0_alpha_10_LIMBS_add_mod`'

### ISSUE THREAD

**Issue by zouxyan** [briansmith/ring#1372] opened 2021-09-01 02:27 UTC
## Can ring be used on WASM ? 
The code using ring can be complied to .wasm file successfully. But when try to run the .wasm file, the error came out.
M new guy for Rust and WASM. I need a crypto lib of Rust which can be used on WASM. 
**Any help is appreciated.**

**Comment by maxcountryman** [comment] 2022-02-13 17:32
I believe I'm facing a similar issue, altho in my case the error is less descriptive: `Uncaught TypeError: Error resolving module specifier “env”. Relative module specifiers must start with “./”, “../” or “/”.`

**Comment by briansmith** [comment] 2022-11-09 20:42
I'm closing this as a duplicate of #918 which is about the more general issue that not all features are provided when targeting wasm32.

**Closed by briansmith** 2022-11-09 20:42 UTC
