### ISSUE TITLE
Add riscv64 Support 

### ISSUE THREAD

**Issue by liberodark** [briansmith/ring#2022] opened 2024-04-08 08:10 UTC
Hi,

Have build issue related to ring from : 
https://gitlab.com/veloren/veloren/-/issues/1972
More info : 
https://paste.yunohost.org/opecoqopep.vbs
Also i can give you access on risc-v if you need.

**How to build :** 

```
#!/bin/bash

apt install -y git curl
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
git clone https://github.com/briansmith/ring
cd ring
source "$HOME/.cargo/env"
cargo build
```
Log : https://paste.yunohost.org/kavasaqawo.rust
That work on my side with `ring 0.17.8`

Best Regards

**Comment by liberodark** [comment] 2024-04-08 09:56
https://github.com/quinn-rs/quinn/issues/1812

**Comment by liberodark** [comment] 2024-04-08 10:43
Related to : https://github.com/quinn-rs/quinn/issues/1812

**Comment by liberodark** [comment] 2024-04-08 10:44
I would like to leave the issue until it is merge/corrected in case it is necessary to take other actions.

**Comment by briansmith** [comment] 2024-05-06 23:57
riscv64 is already supported and riscv64gc-unknown-linux-gnu is already tested in CI so there's nothing more to do. Closing as a duplicate of #1376. PLMK if I am overlooking something.

**Closed by briansmith** 2024-05-06 23:57 UTC
Labels: duplicate
